package main

import (
	"tetra_language/tools/validators/surface"
)

func runMinimalToolkitScenario(mode string) headlessScenario {
	beforeFrame := renderMinimalToolkitFrameRGBA(0, 0, -1, 0, 0, 0, 320, 200)
	textFrame := renderMinimalToolkitFrameRGBA(2, 2, 4, 0, 0, 0, 320, 200)
	submitFrame := renderMinimalToolkitFrameRGBA(1, 1, 6, 1, 0, 1, 320, 200)
	afterFrame := renderMinimalToolkitFrameRGBA(0, 0, 4, 1, 1, 2, 400, 240)
	scenario := headlessScenario{
		Components: []surface.ComponentReport{
			{
				ID:        "ToolkitFormApp",
				Type:      "examples.surface_toolkit_form.ToolkitFormApp",
				Bounds:    surface.RectReport{X: 0, Y: 0, W: 400, H: 240},
				Abilities: []string{"measure", "layout", "draw", "event", "focus", "text", "accessibility"},
				State:     map[string]string{"focused_id": "4", "submit_count": "1", "reset_count": "1", "status_code": "2", "width": "400", "height": "240", "accessibility_role": "none"},
			},
			{
				ID:        "Panel",
				Type:      "lib.core.widgets.Panel",
				Parent:    "ToolkitFormApp",
				Bounds:    surface.RectReport{X: 0, Y: 0, W: 400, H: 240},
				Abilities: []string{"measure", "layout", "draw", "event", "focus", "text", "accessibility"},
				State:     map[string]string{"padding": "12", "accessibility_role": "none"},
			},
			{
				ID:        "Column",
				Type:      "lib.core.widgets.Column",
				Parent:    "Panel",
				Bounds:    surface.RectReport{X: 12, Y: 12, W: 376, H: 216},
				Abilities: []string{"measure", "layout", "draw", "event", "focus", "text", "accessibility"},
				State:     map[string]string{"child_count": "4", "accessibility_role": "none"},
			},
			{
				ID:        "NameLabel",
				Type:      "lib.core.widgets.Text",
				Parent:    "Column",
				Bounds:    surface.RectReport{X: 20, Y: 20, W: 360, H: 24},
				Abilities: []string{"measure", "layout", "draw", "event", "focus", "text", "accessibility"},
				State:     map[string]string{"role": "label", "text_len": "4", "accessibility_role": "label"},
			},
			{
				ID:        "TextBox",
				Type:      "lib.core.widgets.TextBox",
				Parent:    "Column",
				Bounds:    surface.RectReport{X: 20, Y: 52, W: 360, H: 44},
				Abilities: []string{"measure", "layout", "draw", "event", "focus", "text", "accessibility"},
				State:     map[string]string{"focused": "true", "buffer": "", "text_len": "0", "caret": "0", "backspace_count": "1", "delete_count": "1", "accessibility_role": "label"},
			},
			{
				ID:        "ButtonRow",
				Type:      "lib.core.widgets.Row",
				Parent:    "Column",
				Bounds:    surface.RectReport{X: 20, Y: 108, W: 360, H: 44},
				Abilities: []string{"measure", "layout", "draw", "event", "focus", "text", "accessibility"},
				State:     map[string]string{"child_count": "2", "accessibility_role": "none"},
			},
			{
				ID:        "SubmitButton",
				Type:      "lib.core.widgets.Button",
				Parent:    "ButtonRow",
				Bounds:    surface.RectReport{X: 20, Y: 108, W: 132, H: 44},
				Abilities: []string{"measure", "layout", "draw", "event", "focus", "text", "accessibility"},
				State:     map[string]string{"focused": "false", "press_count": "1", "action": "submit", "accessibility_role": "button"},
			},
			{
				ID:        "ResetButton",
				Type:      "lib.core.widgets.Button",
				Parent:    "ButtonRow",
				Bounds:    surface.RectReport{X: 164, Y: 108, W: 132, H: 44},
				Abilities: []string{"measure", "layout", "draw", "event", "focus", "text", "accessibility"},
				State:     map[string]string{"focused": "false", "press_count": "1", "action": "reset", "accessibility_role": "button"},
			},
			{
				ID:        "StatusText",
				Type:      "lib.core.widgets.Text",
				Parent:    "Column",
				Bounds:    surface.RectReport{X: 20, Y: 160, W: 360, H: 24},
				Abilities: []string{"measure", "layout", "draw", "event", "focus", "text", "accessibility"},
				State:     map[string]string{"role": "status", "status_code": "2", "accessibility_role": "label"},
			},
		},
		ComponentTree: &surface.ComponentTreeReport{
			Schema:       "tetra.surface.component-tree.v1",
			DynamicLevel: "minimal-toolkit-widget-tree",
			RootID:       0,
			NodeCount:    9,
			FocusedID:    4,
			Nodes: []surface.ComponentTreeNodeReport{
				{ID: 0, Name: "ToolkitFormApp", Kind: "root", ParentID: -1, ChildIndex: 0, FirstChild: 1, ChildCount: 1, Focusable: false, Bounds: surface.RectReport{X: 0, Y: 0, W: 400, H: 240}},
				{ID: 1, Name: "Panel", Kind: "panel", ParentID: 0, ChildIndex: 0, FirstChild: 2, ChildCount: 1, Focusable: false, Bounds: surface.RectReport{X: 0, Y: 0, W: 400, H: 240}},
				{ID: 2, Name: "Column", Kind: "column", ParentID: 1, ChildIndex: 0, FirstChild: 3, ChildCount: 4, Focusable: false, Bounds: surface.RectReport{X: 12, Y: 12, W: 376, H: 216}},
				{ID: 3, Name: "NameLabel", Kind: "text", ParentID: 2, ChildIndex: 0, FirstChild: -1, ChildCount: 0, Focusable: false, Bounds: surface.RectReport{X: 20, Y: 20, W: 360, H: 24}},
				{ID: 4, Name: "TextBox", Kind: "textbox", ParentID: 2, ChildIndex: 1, FirstChild: -1, ChildCount: 0, Focusable: true, Bounds: surface.RectReport{X: 20, Y: 52, W: 360, H: 44}},
				{ID: 5, Name: "ButtonRow", Kind: "row", ParentID: 2, ChildIndex: 2, FirstChild: 6, ChildCount: 2, Focusable: false, Bounds: surface.RectReport{X: 20, Y: 108, W: 360, H: 44}},
				{ID: 6, Name: "SubmitButton", Kind: "button", ParentID: 5, ChildIndex: 0, FirstChild: -1, ChildCount: 0, Focusable: true, Bounds: surface.RectReport{X: 20, Y: 108, W: 132, H: 44}},
				{ID: 7, Name: "ResetButton", Kind: "button", ParentID: 5, ChildIndex: 1, FirstChild: -1, ChildCount: 0, Focusable: true, Bounds: surface.RectReport{X: 164, Y: 108, W: 132, H: 44}},
				{ID: 8, Name: "StatusText", Kind: "text", ParentID: 2, ChildIndex: 3, FirstChild: -1, ChildCount: 0, Focusable: false, Bounds: surface.RectReport{X: 20, Y: 160, W: 360, H: 24}},
			},
			LayoutPasses: []surface.ComponentTreeLayoutPassReport{
				{ComponentID: 4, Pass: "initial", Bounds: surface.RectReport{X: 20, Y: 52, W: 280, H: 44}, Measured: surface.SizeReport{W: 280, H: 44}},
				{ComponentID: 4, Pass: "resize", Bounds: surface.RectReport{X: 20, Y: 52, W: 360, H: 44}, Measured: surface.SizeReport{W: 360, H: 44}},
				{ComponentID: 8, Pass: "status-update", Bounds: surface.RectReport{X: 20, Y: 160, W: 360, H: 24}, Measured: surface.SizeReport{W: 360, H: 24}},
			},
			DrawOrder:  []int{0, 1, 2, 3, 4, 5, 6, 7, 8},
			FocusOrder: []int{4, 6, 7},
			DispatchPaths: []surface.ComponentTreeDispatchPathReport{
				{Event: "click", TargetID: 4, X: 40, Y: 72, Path: []int{0, 1, 2, 4}},
				{Event: "click", TargetID: 6, X: 40, Y: 124, Path: []int{0, 1, 2, 5, 6}},
				{Event: "click", TargetID: 7, X: 180, Y: 124, Path: []int{0, 1, 2, 5, 7}},
			},
		},
		ComponentTreeAPI: minimalToolkitComponentTreeAPIReport(),
		Toolkit:          minimalToolkitReport(),
		Events: []surface.EventReport{
			{Order: 1, Kind: "mouse_up", TargetComponent: "TextBox", DispatchPath: []string{"ToolkitFormApp", "Panel", "Column", "TextBox"}, Handled: true, Pass: true, X: 40, Y: 72, Width: 320, Height: 200, BufferSlots: []int{5, 40, 72, 1, 0, 320, 200, 0, 0}, BeforeState: map[string]string{"ToolkitFormApp.focused_id": "-1", "TextBox.focused": "false"}, AfterState: map[string]string{"ToolkitFormApp.focused_id": "4", "TextBox.focused": "true"}},
			{Order: 2, Kind: "text_input", TargetComponent: "TextBox", DispatchPath: []string{"ToolkitFormApp", "Panel", "Column", "TextBox"}, Handled: true, Pass: true, Width: 320, Height: 200, TimestampMS: 1, TextLen: 2, TextBytesHex: "4f4b", BufferSlots: []int{8, 0, 0, 0, 0, 320, 200, 1, 2}, BeforeState: map[string]string{"TextBox.buffer": "", "TextBox.caret": "0", "TextBox.text_len": "0"}, AfterState: map[string]string{"TextBox.buffer": "OK", "TextBox.caret": "2", "TextBox.text_len": "2"}},
			{Order: 3, Kind: "key_down", TargetComponent: "TextBox", DispatchPath: []string{"ToolkitFormApp", "Panel", "Column", "TextBox"}, Handled: true, Pass: true, Key: 37, Width: 320, Height: 200, TimestampMS: 2, BufferSlots: []int{6, 0, 0, 0, 37, 320, 200, 2, 0}, BeforeState: map[string]string{"TextBox.buffer": "OK", "TextBox.caret": "2"}, AfterState: map[string]string{"TextBox.buffer": "OK", "TextBox.caret": "1"}},
			{Order: 4, Kind: "key_down", TargetComponent: "TextBox", DispatchPath: []string{"ToolkitFormApp", "Panel", "Column", "TextBox"}, Handled: true, Pass: true, Key: 8, Width: 320, Height: 200, TimestampMS: 3, BufferSlots: []int{6, 0, 0, 0, 8, 320, 200, 3, 0}, BeforeState: map[string]string{"TextBox.buffer": "OK", "TextBox.caret": "1"}, AfterState: map[string]string{"TextBox.buffer": "K", "TextBox.caret": "0"}},
			{Order: 5, Kind: "key_down", TargetComponent: "TextBox", DispatchPath: []string{"ToolkitFormApp", "Panel", "Column", "TextBox"}, Handled: true, Pass: true, Key: 46, Width: 320, Height: 200, TimestampMS: 4, BufferSlots: []int{6, 0, 0, 0, 46, 320, 200, 4, 0}, BeforeState: map[string]string{"TextBox.buffer": "K", "TextBox.caret": "0"}, AfterState: map[string]string{"TextBox.buffer": "", "TextBox.caret": "0"}},
			{Order: 6, Kind: "text_input", TargetComponent: "TextBox", DispatchPath: []string{"ToolkitFormApp", "Panel", "Column", "TextBox"}, Handled: true, Pass: true, Width: 320, Height: 200, TimestampMS: 5, TextLen: 1, TextBytesHex: "5a", BufferSlots: []int{8, 0, 0, 0, 0, 320, 200, 5, 1}, BeforeState: map[string]string{"TextBox.buffer": "", "TextBox.caret": "0", "TextBox.text_len": "0"}, AfterState: map[string]string{"TextBox.buffer": "Z", "TextBox.caret": "1", "TextBox.text_len": "1"}},
			{Order: 7, Kind: "key_down", TargetComponent: "ToolkitFormApp", DispatchPath: []string{"ToolkitFormApp"}, Handled: true, Pass: true, Key: 9, Width: 320, Height: 200, TimestampMS: 6, BufferSlots: []int{6, 0, 0, 0, 9, 320, 200, 6, 0}, BeforeState: map[string]string{"ToolkitFormApp.focused_id": "4"}, AfterState: map[string]string{"ToolkitFormApp.focused_id": "6"}},
			{Order: 8, Kind: "key_down", TargetComponent: "SubmitButton", DispatchPath: []string{"ToolkitFormApp", "Panel", "Column", "ButtonRow", "SubmitButton"}, Handled: true, Pass: true, Key: 32, Width: 320, Height: 200, TimestampMS: 7, BufferSlots: []int{6, 0, 0, 0, 32, 320, 200, 7, 0}, BeforeState: map[string]string{"ToolkitFormApp.focused_id": "6", "ToolkitFormApp.submit_count": "0", "StatusText.status_code": "0", "TextBox.buffer": "Z"}, AfterState: map[string]string{"ToolkitFormApp.focused_id": "6", "ToolkitFormApp.submit_count": "1", "StatusText.status_code": "1", "TextBox.buffer": "Z"}},
			{Order: 9, Kind: "key_down", TargetComponent: "ToolkitFormApp", DispatchPath: []string{"ToolkitFormApp"}, Handled: true, Pass: true, Key: 9, Width: 320, Height: 200, TimestampMS: 8, BufferSlots: []int{6, 0, 0, 0, 9, 320, 200, 8, 0}, BeforeState: map[string]string{"ToolkitFormApp.focused_id": "6"}, AfterState: map[string]string{"ToolkitFormApp.focused_id": "7"}},
			{Order: 10, Kind: "text_input", TargetComponent: "ResetButton", DispatchPath: []string{"ToolkitFormApp", "Panel", "Column", "ButtonRow", "ResetButton"}, Handled: true, Pass: true, Width: 320, Height: 200, TimestampMS: 9, TextLen: 1, TextBytesHex: "58", BufferSlots: []int{8, 0, 0, 0, 0, 320, 200, 9, 1}, BeforeState: map[string]string{"ToolkitFormApp.focused_id": "7", "TextBox.buffer": "Z"}, AfterState: map[string]string{"ToolkitFormApp.focused_id": "7", "TextBox.buffer": "Z"}},
			{Order: 11, Kind: "key_down", TargetComponent: "ResetButton", DispatchPath: []string{"ToolkitFormApp", "Panel", "Column", "ButtonRow", "ResetButton"}, Handled: true, Pass: true, Key: 13, Width: 320, Height: 200, TimestampMS: 10, BufferSlots: []int{6, 0, 0, 0, 13, 320, 200, 10, 0}, BeforeState: map[string]string{"ToolkitFormApp.focused_id": "7", "ToolkitFormApp.reset_count": "0", "StatusText.status_code": "1", "TextBox.buffer": "Z"}, AfterState: map[string]string{"ToolkitFormApp.focused_id": "7", "ToolkitFormApp.reset_count": "1", "StatusText.status_code": "2", "TextBox.buffer": ""}},
			{Order: 12, Kind: "key_down", TargetComponent: "ToolkitFormApp", DispatchPath: []string{"ToolkitFormApp"}, Handled: true, Pass: true, Key: 9, Width: 320, Height: 200, TimestampMS: 11, BufferSlots: []int{6, 0, 0, 0, 9, 320, 200, 11, 0}, BeforeState: map[string]string{"ToolkitFormApp.focused_id": "7"}, AfterState: map[string]string{"ToolkitFormApp.focused_id": "4"}},
			{Order: 13, Kind: "resize", TargetComponent: "ToolkitFormApp", DispatchPath: []string{"ToolkitFormApp"}, Handled: true, Pass: true, Width: 400, Height: 240, TimestampMS: 12, BufferSlots: []int{2, 0, 0, 0, 0, 400, 240, 12, 0}, BeforeState: map[string]string{"ToolkitFormApp.focused_id": "4", "TextBox.bounds.w": "280", "TextBox.buffer": ""}, AfterState: map[string]string{"ToolkitFormApp.focused_id": "4", "TextBox.bounds.w": "360", "TextBox.buffer": ""}},
		},
		Frames: []surface.FrameReport{
			{Order: 1, Width: beforeFrame.Width, Height: beforeFrame.Height, Stride: beforeFrame.Stride, Checksum: checksumRGBA(beforeFrame.Pixels), Presented: true},
			{Order: 2, Width: textFrame.Width, Height: textFrame.Height, Stride: textFrame.Stride, Checksum: checksumRGBA(textFrame.Pixels), Presented: true},
			{Order: 3, Width: submitFrame.Width, Height: submitFrame.Height, Stride: submitFrame.Stride, Checksum: checksumRGBA(submitFrame.Pixels), Presented: true},
			{Order: 4, Width: afterFrame.Width, Height: afterFrame.Height, Stride: afterFrame.Stride, Checksum: checksumRGBA(afterFrame.Pixels), Presented: true},
		},
		StateTransitions: []surface.StateTransitionReport{
			{Order: 1, Component: "ToolkitFormApp", Field: "focused_id", Before: "-1", After: "4", Cause: "mouse_up"},
			{Order: 2, Component: "TextBox", Field: "buffer", Before: "", After: "OK", Cause: "text_input"},
			{Order: 3, Component: "TextBox", Field: "caret", Before: "2", After: "1", Cause: "key_down"},
			{Order: 4, Component: "TextBox", Field: "buffer", Before: "OK", After: "K", Cause: "backspace"},
			{Order: 5, Component: "TextBox", Field: "buffer", Before: "K", After: "", Cause: "delete"},
			{Order: 6, Component: "TextBox", Field: "buffer", Before: "", After: "Z", Cause: "text_input"},
			{Order: 7, Component: "ToolkitFormApp", Field: "focused_id", Before: "4", After: "6", Cause: "tab"},
			{Order: 8, Component: "ToolkitFormApp", Field: "submit_count", Before: "0", After: "1", Cause: "key_down"},
			{Order: 9, Component: "StatusText", Field: "status_code", Before: "0", After: "1", Cause: "submit"},
			{Order: 10, Component: "ToolkitFormApp", Field: "focused_id", Before: "6", After: "7", Cause: "tab"},
			{Order: 11, Component: "TextBox", Field: "buffer", Before: "Z", After: "", Cause: "reset"},
			{Order: 12, Component: "ToolkitFormApp", Field: "reset_count", Before: "0", After: "1", Cause: "key_down"},
			{Order: 13, Component: "StatusText", Field: "status_code", Before: "1", After: "2", Cause: "reset"},
			{Order: 14, Component: "ToolkitFormApp", Field: "focused_id", Before: "7", After: "4", Cause: "tab"},
			{Order: 15, Component: "ToolkitFormApp", Field: "TextBox.bounds.w", Before: "280", After: "360", Cause: "resize"},
		},
		Cases: minimalToolkitBaseCases(),
	}
	switch mode {
	case "headless-minimal-toolkit":
		scenario.Cases = append(scenario.Cases,
			surface.CaseReport{Name: "headless event dispatch", Kind: "positive", Ran: true, Pass: true},
			surface.CaseReport{Name: "headless framebuffer checksum", Kind: "positive", Ran: true, Pass: true},
			surface.CaseReport{Name: "headless actual runner trace", Kind: "positive", Ran: true, Pass: true},
		)
	case "linux-x64-real-window-minimal-toolkit":
		scenario.Cases = append(scenario.Cases,
			surface.CaseReport{Name: "linux-x64 Surface Host ABI open/present/close", Kind: "positive", Ran: true, Pass: true},
			surface.CaseReport{Name: "linux-x64 real-window surface", Kind: "positive", Ran: true, Pass: true},
			surface.CaseReport{Name: "linux-x64 native input event pump", Kind: "positive", Ran: true, Pass: true},
			surface.CaseReport{Name: "linux-x64 real-window resize event", Kind: "positive", Ran: true, Pass: true},
			surface.CaseReport{Name: "linux-x64 real-window close event", Kind: "positive", Ran: true, Pass: true},
		)
	case "wasm32-web-browser-canvas-minimal-toolkit":
		scenario.Frames = nil
		scenario.Cases = append(scenario.Cases,
			surface.CaseReport{Name: "wasm32-web browser canvas surface", Kind: "positive", Ran: true, Pass: true},
			surface.CaseReport{Name: "wasm32-web browser canvas RGBA readback", Kind: "positive", Ran: true, Pass: true},
			surface.CaseReport{Name: "wasm32-web browser canvas pointer input", Kind: "positive", Ran: true, Pass: true},
			surface.CaseReport{Name: "wasm32-web browser canvas keyboard input", Kind: "positive", Ran: true, Pass: true},
			surface.CaseReport{Name: "wasm32-web browser canvas resize input", Kind: "positive", Ran: true, Pass: true},
			surface.CaseReport{Name: "wasm32-web browser canvas text input", Kind: "positive", Ran: true, Pass: true},
			surface.CaseReport{Name: "wasm32-web Surface Host ABI imports", Kind: "positive", Ran: true, Pass: true},
			surface.CaseReport{Name: "compiler-owned wasm Surface loader", Kind: "positive", Ran: true, Pass: true},
			surface.CaseReport{Name: "compiler-owned browser canvas Surface host", Kind: "positive", Ran: true, Pass: true},
		)
	}
	return scenario
}
func runToolkitReuseScenario(mode string) headlessScenario {
	beforeFrame := renderToolkitReuseFrameRGBA(0, 0, -1, 0, 0, 0, 320, 240)
	nameFrame := renderToolkitReuseFrameRGBA(3, 0, 4, 0, 0, 0, 320, 240)
	saveFrame := renderToolkitReuseFrameRGBA(3, 5, 8, 1, 0, 1, 320, 240)
	resetFrame := renderToolkitReuseFrameRGBA(0, 0, 9, 1, 1, 2, 320, 240)
	afterFrame := renderToolkitReuseFrameRGBA(0, 0, 4, 1, 1, 2, 480, 320)
	scenario := headlessScenario{
		Components: []surface.ComponentReport{
			{ID: "ToolkitSettingsApp", Type: "examples.surface_toolkit_settings.ToolkitSettingsApp", Bounds: surface.RectReport{X: 0, Y: 0, W: 480, H: 320}, Abilities: []string{"measure", "layout", "draw", "event", "focus", "text", "accessibility"}, State: map[string]string{"focused_id": "4", "save_count": "1", "reset_count": "1", "status_code": "2", "width": "480", "height": "320", "accessibility_role": "none"}},
			{ID: "Panel", Type: "lib.core.widgets.Panel", Parent: "ToolkitSettingsApp", Bounds: surface.RectReport{X: 0, Y: 0, W: 480, H: 320}, Abilities: []string{"measure", "layout", "draw", "event", "focus", "text", "accessibility"}, State: map[string]string{"padding": "12", "accessibility_role": "none"}},
			{ID: "Column", Type: "lib.core.widgets.Column", Parent: "Panel", Bounds: surface.RectReport{X: 12, Y: 12, W: 456, H: 296}, Abilities: []string{"measure", "layout", "draw", "event", "focus", "text", "accessibility"}, State: map[string]string{"child_count": "6", "accessibility_role": "none"}},
			{ID: "TitleText", Type: "lib.core.widgets.Text", Parent: "Column", Bounds: surface.RectReport{X: 20, Y: 20, W: 440, H: 24}, Abilities: []string{"measure", "layout", "draw", "event", "focus", "text", "accessibility"}, State: map[string]string{"role": "label", "text_len": "8", "accessibility_role": "label"}},
			{ID: "NameTextBox", Type: "lib.core.widgets.TextBox", Parent: "Column", Bounds: surface.RectReport{X: 20, Y: 52, W: 440, H: 44}, Abilities: []string{"measure", "layout", "draw", "event", "focus", "text", "accessibility"}, State: map[string]string{"focused": "true", "buffer": "", "text_len": "0", "caret": "0", "accessibility_role": "label"}},
			{ID: "NameLabel", Type: "lib.core.widgets.Text", Parent: "Column", Bounds: surface.RectReport{X: 20, Y: 104, W: 440, H: 24}, Abilities: []string{"measure", "layout", "draw", "event", "focus", "text", "accessibility"}, State: map[string]string{"role": "label", "text_len": "4", "accessibility_role": "label"}},
			{ID: "EmailTextBox", Type: "lib.core.widgets.TextBox", Parent: "Column", Bounds: surface.RectReport{X: 20, Y: 136, W: 440, H: 44}, Abilities: []string{"measure", "layout", "draw", "event", "focus", "text", "accessibility"}, State: map[string]string{"focused": "false", "buffer": "", "text_len": "0", "caret": "0", "accessibility_role": "label"}},
			{ID: "ButtonRow", Type: "lib.core.widgets.Row", Parent: "Column", Bounds: surface.RectReport{X: 20, Y: 192, W: 440, H: 44}, Abilities: []string{"measure", "layout", "draw", "event", "focus", "text", "accessibility"}, State: map[string]string{"child_count": "2", "accessibility_role": "none"}},
			{ID: "SaveButton", Type: "lib.core.widgets.Button", Parent: "ButtonRow", Bounds: surface.RectReport{X: 20, Y: 192, W: 132, H: 44}, Abilities: []string{"measure", "layout", "draw", "event", "focus", "text", "accessibility"}, State: map[string]string{"focused": "false", "press_count": "1", "action": "save", "accessibility_role": "button"}},
			{ID: "ResetButton", Type: "lib.core.widgets.Button", Parent: "ButtonRow", Bounds: surface.RectReport{X: 164, Y: 192, W: 132, H: 44}, Abilities: []string{"measure", "layout", "draw", "event", "focus", "text", "accessibility"}, State: map[string]string{"focused": "false", "press_count": "1", "action": "reset", "accessibility_role": "button"}},
			{ID: "StatusText", Type: "lib.core.widgets.Text", Parent: "Column", Bounds: surface.RectReport{X: 20, Y: 248, W: 440, H: 24}, Abilities: []string{"measure", "layout", "draw", "event", "focus", "text", "accessibility"}, State: map[string]string{"role": "status", "status_code": "2", "accessibility_role": "label"}},
		},
		ComponentTree: &surface.ComponentTreeReport{
			Schema:       "tetra.surface.component-tree.v1",
			DynamicLevel: "toolkit-reuse-widget-tree",
			RootID:       0,
			NodeCount:    11,
			FocusedID:    4,
			Nodes: []surface.ComponentTreeNodeReport{
				{ID: 0, Name: "ToolkitSettingsApp", Kind: "root", ParentID: -1, ChildIndex: 0, FirstChild: 1, ChildCount: 1, Focusable: false, Bounds: surface.RectReport{X: 0, Y: 0, W: 480, H: 320}},
				{ID: 1, Name: "Panel", Kind: "panel", ParentID: 0, ChildIndex: 0, FirstChild: 2, ChildCount: 1, Focusable: false, Bounds: surface.RectReport{X: 0, Y: 0, W: 480, H: 320}},
				{ID: 2, Name: "Column", Kind: "column", ParentID: 1, ChildIndex: 0, FirstChild: 3, ChildCount: 6, Focusable: false, Bounds: surface.RectReport{X: 12, Y: 12, W: 456, H: 296}},
				{ID: 3, Name: "TitleText", Kind: "text", ParentID: 2, ChildIndex: 0, FirstChild: -1, ChildCount: 0, Focusable: false, Bounds: surface.RectReport{X: 20, Y: 20, W: 440, H: 24}},
				{ID: 4, Name: "NameTextBox", Kind: "textbox", ParentID: 2, ChildIndex: 1, FirstChild: -1, ChildCount: 0, Focusable: true, Bounds: surface.RectReport{X: 20, Y: 52, W: 440, H: 44}},
				{ID: 5, Name: "NameLabel", Kind: "text", ParentID: 2, ChildIndex: 2, FirstChild: -1, ChildCount: 0, Focusable: false, Bounds: surface.RectReport{X: 20, Y: 104, W: 440, H: 24}},
				{ID: 6, Name: "EmailTextBox", Kind: "textbox", ParentID: 2, ChildIndex: 3, FirstChild: -1, ChildCount: 0, Focusable: true, Bounds: surface.RectReport{X: 20, Y: 136, W: 440, H: 44}},
				{ID: 7, Name: "ButtonRow", Kind: "row", ParentID: 2, ChildIndex: 4, FirstChild: 8, ChildCount: 2, Focusable: false, Bounds: surface.RectReport{X: 20, Y: 192, W: 440, H: 44}},
				{ID: 8, Name: "SaveButton", Kind: "button", ParentID: 7, ChildIndex: 0, FirstChild: -1, ChildCount: 0, Focusable: true, Bounds: surface.RectReport{X: 20, Y: 192, W: 132, H: 44}},
				{ID: 9, Name: "ResetButton", Kind: "button", ParentID: 7, ChildIndex: 1, FirstChild: -1, ChildCount: 0, Focusable: true, Bounds: surface.RectReport{X: 164, Y: 192, W: 132, H: 44}},
				{ID: 10, Name: "StatusText", Kind: "text", ParentID: 2, ChildIndex: 5, FirstChild: -1, ChildCount: 0, Focusable: false, Bounds: surface.RectReport{X: 20, Y: 248, W: 440, H: 24}},
			},
			LayoutPasses: []surface.ComponentTreeLayoutPassReport{
				{ComponentID: 4, Pass: "initial", Bounds: surface.RectReport{X: 20, Y: 52, W: 280, H: 44}, Measured: surface.SizeReport{W: 280, H: 44}},
				{ComponentID: 6, Pass: "initial", Bounds: surface.RectReport{X: 20, Y: 136, W: 280, H: 44}, Measured: surface.SizeReport{W: 280, H: 44}},
				{ComponentID: 4, Pass: "resize", Bounds: surface.RectReport{X: 20, Y: 52, W: 440, H: 44}, Measured: surface.SizeReport{W: 440, H: 44}},
				{ComponentID: 6, Pass: "resize", Bounds: surface.RectReport{X: 20, Y: 136, W: 440, H: 44}, Measured: surface.SizeReport{W: 440, H: 44}},
				{ComponentID: 10, Pass: "status-update", Bounds: surface.RectReport{X: 20, Y: 248, W: 440, H: 24}, Measured: surface.SizeReport{W: 440, H: 24}},
			},
			DrawOrder:  []int{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10},
			FocusOrder: []int{4, 6, 8, 9},
			DispatchPaths: []surface.ComponentTreeDispatchPathReport{
				{Event: "click", TargetID: 4, X: 40, Y: 72, Path: []int{0, 1, 2, 4}},
				{Event: "click", TargetID: 6, X: 40, Y: 156, Path: []int{0, 1, 2, 6}},
				{Event: "key", TargetID: 8, X: 40, Y: 208, Path: []int{0, 1, 2, 7, 8}},
				{Event: "key", TargetID: 9, X: 180, Y: 208, Path: []int{0, 1, 2, 7, 9}},
			},
		},
		ComponentTreeAPI: toolkitReuseComponentTreeAPIReport(),
		Toolkit:          toolkitReuseReport(),
		Events: []surface.EventReport{
			{Order: 1, Kind: "mouse_up", TargetComponent: "NameTextBox", DispatchPath: []string{"ToolkitSettingsApp", "Panel", "Column", "NameTextBox"}, Handled: true, Pass: true, X: 40, Y: 72, Width: 320, Height: 240, BufferSlots: []int{5, 40, 72, 1, 0, 320, 240, 0, 0}, BeforeState: map[string]string{"ToolkitSettingsApp.focused_id": "-1", "NameTextBox.focused": "false"}, AfterState: map[string]string{"ToolkitSettingsApp.focused_id": "4", "NameTextBox.focused": "true"}},
			{Order: 2, Kind: "text_input", TargetComponent: "NameTextBox", DispatchPath: []string{"ToolkitSettingsApp", "Panel", "Column", "NameTextBox"}, Handled: true, Pass: true, Width: 320, Height: 240, TimestampMS: 1, TextLen: 3, TextBytesHex: "416461", BufferSlots: []int{8, 0, 0, 0, 0, 320, 240, 1, 3}, BeforeState: map[string]string{"NameTextBox.buffer": "", "NameTextBox.caret": "0", "EmailTextBox.buffer": ""}, AfterState: map[string]string{"NameTextBox.buffer": "Ada", "NameTextBox.caret": "3", "EmailTextBox.buffer": ""}},
			{Order: 3, Kind: "key_down", TargetComponent: "ToolkitSettingsApp", DispatchPath: []string{"ToolkitSettingsApp"}, Handled: true, Pass: true, Key: 9, Width: 320, Height: 240, TimestampMS: 2, BufferSlots: []int{6, 0, 0, 0, 9, 320, 240, 2, 0}, BeforeState: map[string]string{"ToolkitSettingsApp.focused_id": "4"}, AfterState: map[string]string{"ToolkitSettingsApp.focused_id": "6"}},
			{Order: 4, Kind: "text_input", TargetComponent: "EmailTextBox", DispatchPath: []string{"ToolkitSettingsApp", "Panel", "Column", "EmailTextBox"}, Handled: true, Pass: true, Width: 320, Height: 240, TimestampMS: 3, TextLen: 5, TextBytesHex: "7465747261", BufferSlots: []int{8, 0, 0, 0, 0, 320, 240, 3, 5}, BeforeState: map[string]string{"EmailTextBox.buffer": "", "NameTextBox.buffer": "Ada"}, AfterState: map[string]string{"EmailTextBox.buffer": "tetra", "NameTextBox.buffer": "Ada"}},
			{Order: 5, Kind: "key_down", TargetComponent: "ToolkitSettingsApp", DispatchPath: []string{"ToolkitSettingsApp"}, Handled: true, Pass: true, Key: 9, Width: 320, Height: 240, TimestampMS: 4, BufferSlots: []int{6, 0, 0, 0, 9, 320, 240, 4, 0}, BeforeState: map[string]string{"ToolkitSettingsApp.focused_id": "6"}, AfterState: map[string]string{"ToolkitSettingsApp.focused_id": "8"}},
			{Order: 6, Kind: "key_down", TargetComponent: "SaveButton", DispatchPath: []string{"ToolkitSettingsApp", "Panel", "Column", "ButtonRow", "SaveButton"}, Handled: true, Pass: true, Key: 32, Width: 320, Height: 240, TimestampMS: 5, BufferSlots: []int{6, 0, 0, 0, 32, 320, 240, 5, 0}, BeforeState: map[string]string{"ToolkitSettingsApp.focused_id": "8", "ToolkitSettingsApp.save_count": "0", "StatusText.status_code": "0"}, AfterState: map[string]string{"ToolkitSettingsApp.focused_id": "8", "ToolkitSettingsApp.save_count": "1", "StatusText.status_code": "1"}},
			{Order: 7, Kind: "key_down", TargetComponent: "ToolkitSettingsApp", DispatchPath: []string{"ToolkitSettingsApp"}, Handled: true, Pass: true, Key: 9, Width: 320, Height: 240, TimestampMS: 6, BufferSlots: []int{6, 0, 0, 0, 9, 320, 240, 6, 0}, BeforeState: map[string]string{"ToolkitSettingsApp.focused_id": "8"}, AfterState: map[string]string{"ToolkitSettingsApp.focused_id": "9"}},
			{Order: 8, Kind: "key_down", TargetComponent: "ResetButton", DispatchPath: []string{"ToolkitSettingsApp", "Panel", "Column", "ButtonRow", "ResetButton"}, Handled: true, Pass: true, Key: 13, Width: 320, Height: 240, TimestampMS: 7, BufferSlots: []int{6, 0, 0, 0, 13, 320, 240, 7, 0}, BeforeState: map[string]string{"ToolkitSettingsApp.focused_id": "9", "ToolkitSettingsApp.reset_count": "0", "StatusText.status_code": "1", "NameTextBox.buffer": "Ada", "EmailTextBox.buffer": "tetra"}, AfterState: map[string]string{"ToolkitSettingsApp.focused_id": "9", "ToolkitSettingsApp.reset_count": "1", "StatusText.status_code": "2", "NameTextBox.buffer": "", "EmailTextBox.buffer": ""}},
			{Order: 9, Kind: "key_down", TargetComponent: "ToolkitSettingsApp", DispatchPath: []string{"ToolkitSettingsApp"}, Handled: true, Pass: true, Key: 9, Width: 320, Height: 240, TimestampMS: 8, BufferSlots: []int{6, 0, 0, 0, 9, 320, 240, 8, 0}, BeforeState: map[string]string{"ToolkitSettingsApp.focused_id": "9"}, AfterState: map[string]string{"ToolkitSettingsApp.focused_id": "4"}},
			{Order: 10, Kind: "resize", TargetComponent: "ToolkitSettingsApp", DispatchPath: []string{"ToolkitSettingsApp"}, Handled: true, Pass: true, Width: 480, Height: 320, TimestampMS: 9, BufferSlots: []int{2, 0, 0, 0, 0, 480, 320, 9, 0}, BeforeState: map[string]string{"ToolkitSettingsApp.focused_id": "4", "NameTextBox.bounds.w": "280", "EmailTextBox.bounds.w": "280"}, AfterState: map[string]string{"ToolkitSettingsApp.focused_id": "4", "NameTextBox.bounds.w": "440", "EmailTextBox.bounds.w": "440"}},
		},
		Frames: []surface.FrameReport{
			{Order: 1, Width: beforeFrame.Width, Height: beforeFrame.Height, Stride: beforeFrame.Stride, Checksum: checksumRGBA(beforeFrame.Pixels), Presented: true},
			{Order: 2, Width: nameFrame.Width, Height: nameFrame.Height, Stride: nameFrame.Stride, Checksum: checksumRGBA(nameFrame.Pixels), Presented: true},
			{Order: 3, Width: saveFrame.Width, Height: saveFrame.Height, Stride: saveFrame.Stride, Checksum: checksumRGBA(saveFrame.Pixels), Presented: true},
			{Order: 4, Width: resetFrame.Width, Height: resetFrame.Height, Stride: resetFrame.Stride, Checksum: checksumRGBA(resetFrame.Pixels), Presented: true},
			{Order: 5, Width: afterFrame.Width, Height: afterFrame.Height, Stride: afterFrame.Stride, Checksum: checksumRGBA(afterFrame.Pixels), Presented: true},
		},
		StateTransitions: []surface.StateTransitionReport{
			{Order: 1, Component: "ToolkitSettingsApp", Field: "focused_id", Before: "-1", After: "4", Cause: "mouse_up"},
			{Order: 2, Component: "NameTextBox", Field: "buffer", Before: "", After: "Ada", Cause: "text_input"},
			{Order: 3, Component: "ToolkitSettingsApp", Field: "focused_id", Before: "4", After: "6", Cause: "tab"},
			{Order: 4, Component: "EmailTextBox", Field: "buffer", Before: "", After: "tetra", Cause: "text_input"},
			{Order: 5, Component: "ToolkitSettingsApp", Field: "focused_id", Before: "6", After: "8", Cause: "tab"},
			{Order: 6, Component: "ToolkitSettingsApp", Field: "save_count", Before: "0", After: "1", Cause: "key_down"},
			{Order: 7, Component: "StatusText", Field: "status_code", Before: "0", After: "1", Cause: "save"},
			{Order: 8, Component: "ToolkitSettingsApp", Field: "focused_id", Before: "8", After: "9", Cause: "tab"},
			{Order: 9, Component: "NameTextBox", Field: "buffer", Before: "Ada", After: "", Cause: "reset"},
			{Order: 10, Component: "EmailTextBox", Field: "buffer", Before: "tetra", After: "", Cause: "reset"},
			{Order: 11, Component: "ToolkitSettingsApp", Field: "reset_count", Before: "0", After: "1", Cause: "key_down"},
			{Order: 12, Component: "StatusText", Field: "status_code", Before: "1", After: "2", Cause: "reset"},
			{Order: 13, Component: "ToolkitSettingsApp", Field: "focused_id", Before: "9", After: "4", Cause: "tab"},
			{Order: 14, Component: "ToolkitSettingsApp", Field: "NameTextBox.bounds.w", Before: "280", After: "440", Cause: "resize"},
			{Order: 15, Component: "ToolkitSettingsApp", Field: "EmailTextBox.bounds.w", Before: "280", After: "440", Cause: "resize"},
		},
		Cases: toolkitReuseBaseCases(),
	}
	switch mode {
	case "headless-toolkit-reuse":
		scenario.Cases = append(scenario.Cases,
			surface.CaseReport{Name: "headless event dispatch", Kind: "positive", Ran: true, Pass: true},
			surface.CaseReport{Name: "headless framebuffer checksum", Kind: "positive", Ran: true, Pass: true},
			surface.CaseReport{Name: "headless actual runner trace", Kind: "positive", Ran: true, Pass: true},
		)
	case "linux-x64-real-window-toolkit-reuse":
		scenario.Cases = append(scenario.Cases,
			surface.CaseReport{Name: "linux-x64 Surface Host ABI open/present/close", Kind: "positive", Ran: true, Pass: true},
			surface.CaseReport{Name: "linux-x64 real-window surface", Kind: "positive", Ran: true, Pass: true},
			surface.CaseReport{Name: "linux-x64 native input event pump", Kind: "positive", Ran: true, Pass: true},
			surface.CaseReport{Name: "linux-x64 real-window resize event", Kind: "positive", Ran: true, Pass: true},
			surface.CaseReport{Name: "linux-x64 real-window close event", Kind: "positive", Ran: true, Pass: true},
		)
	case "wasm32-web-browser-canvas-toolkit-reuse":
		scenario.Frames = nil
		scenario.Cases = append(scenario.Cases,
			surface.CaseReport{Name: "wasm32-web browser canvas surface", Kind: "positive", Ran: true, Pass: true},
			surface.CaseReport{Name: "wasm32-web browser canvas RGBA readback", Kind: "positive", Ran: true, Pass: true},
			surface.CaseReport{Name: "wasm32-web browser canvas pointer input", Kind: "positive", Ran: true, Pass: true},
			surface.CaseReport{Name: "wasm32-web browser canvas keyboard input", Kind: "positive", Ran: true, Pass: true},
			surface.CaseReport{Name: "wasm32-web browser canvas resize input", Kind: "positive", Ran: true, Pass: true},
			surface.CaseReport{Name: "wasm32-web browser canvas text input", Kind: "positive", Ran: true, Pass: true},
			surface.CaseReport{Name: "wasm32-web Surface Host ABI imports", Kind: "positive", Ran: true, Pass: true},
			surface.CaseReport{Name: "compiler-owned wasm Surface loader", Kind: "positive", Ran: true, Pass: true},
			surface.CaseReport{Name: "compiler-owned browser canvas Surface host", Kind: "positive", Ran: true, Pass: true},
		)
	}
	return scenario
}
func runAccessibilityMetadataScenario(mode string) headlessScenario {
	beforeFrame := renderAccessibilityMetadataFrameRGBA(0, 0, -1, 0, 0, 0, 320, 240)
	nameFrame := renderAccessibilityMetadataFrameRGBA(3, 0, 5, 0, 0, 0, 320, 240)
	saveFrame := renderAccessibilityMetadataFrameRGBA(3, 5, 9, 1, 0, 1, 320, 240)
	resetFrame := renderAccessibilityMetadataFrameRGBA(0, 0, 10, 1, 1, 2, 320, 240)
	afterFrame := renderAccessibilityMetadataFrameRGBA(0, 0, 5, 1, 1, 2, 480, 320)
	scenario := headlessScenario{
		Components: []surface.ComponentReport{
			{ID: "AccessibilitySettingsApp", Type: "examples.surface_accessibility_settings.AccessibilitySettingsApp", Bounds: surface.RectReport{X: 0, Y: 0, W: 480, H: 320}, Abilities: []string{"measure", "layout", "draw", "event", "focus", "text", "accessibility"}, State: map[string]string{"focused_id": "5", "save_count": "1", "reset_count": "1", "status_code": "2", "width": "480", "height": "320", "accessibility_role": "root"}},
			{ID: "Panel", Type: "lib.core.widgets.Panel", Parent: "AccessibilitySettingsApp", Bounds: surface.RectReport{X: 0, Y: 0, W: 480, H: 320}, Abilities: []string{"measure", "layout", "draw", "event", "focus", "text", "accessibility"}, State: map[string]string{"padding": "12", "accessibility_role": "panel"}},
			{ID: "Column", Type: "lib.core.widgets.Column", Parent: "Panel", Bounds: surface.RectReport{X: 12, Y: 12, W: 456, H: 296}, Abilities: []string{"measure", "layout", "draw", "event", "focus", "text", "accessibility"}, State: map[string]string{"child_count": "7", "accessibility_role": "column"}},
			{ID: "TitleText", Type: "lib.core.widgets.Text", Parent: "Column", Bounds: surface.RectReport{X: 20, Y: 20, W: 440, H: 24}, Abilities: []string{"measure", "layout", "draw", "event", "focus", "text", "accessibility"}, State: map[string]string{"role": "text", "text_len": "8", "accessibility_role": "text"}},
			{ID: "NameLabel", Type: "lib.core.widgets.Text", Parent: "Column", Bounds: surface.RectReport{X: 20, Y: 52, W: 440, H: 24}, Abilities: []string{"measure", "layout", "draw", "event", "focus", "text", "accessibility"}, State: map[string]string{"role": "label", "text_len": "4", "accessibility_role": "label"}},
			{ID: "NameTextBox", Type: "lib.core.widgets.TextBox", Parent: "Column", Bounds: surface.RectReport{X: 20, Y: 84, W: 440, H: 44}, Abilities: []string{"measure", "layout", "draw", "event", "focus", "text", "accessibility"}, State: map[string]string{"focused": "true", "buffer": "", "text_len": "0", "caret": "0", "accessibility_role": "textbox"}},
			{ID: "EmailLabel", Type: "lib.core.widgets.Text", Parent: "Column", Bounds: surface.RectReport{X: 20, Y: 136, W: 440, H: 24}, Abilities: []string{"measure", "layout", "draw", "event", "focus", "text", "accessibility"}, State: map[string]string{"role": "label", "text_len": "5", "accessibility_role": "label"}},
			{ID: "EmailTextBox", Type: "lib.core.widgets.TextBox", Parent: "Column", Bounds: surface.RectReport{X: 20, Y: 168, W: 440, H: 44}, Abilities: []string{"measure", "layout", "draw", "event", "focus", "text", "accessibility"}, State: map[string]string{"focused": "false", "buffer": "", "text_len": "0", "caret": "0", "accessibility_role": "textbox"}},
			{ID: "ButtonRow", Type: "lib.core.widgets.Row", Parent: "Column", Bounds: surface.RectReport{X: 20, Y: 224, W: 440, H: 44}, Abilities: []string{"measure", "layout", "draw", "event", "focus", "text", "accessibility"}, State: map[string]string{"child_count": "2", "accessibility_role": "row"}},
			{ID: "SaveButton", Type: "lib.core.widgets.Button", Parent: "ButtonRow", Bounds: surface.RectReport{X: 20, Y: 224, W: 132, H: 44}, Abilities: []string{"measure", "layout", "draw", "event", "focus", "text", "accessibility"}, State: map[string]string{"focused": "false", "press_count": "1", "action": "save", "accessibility_role": "button"}},
			{ID: "ResetButton", Type: "lib.core.widgets.Button", Parent: "ButtonRow", Bounds: surface.RectReport{X: 164, Y: 224, W: 132, H: 44}, Abilities: []string{"measure", "layout", "draw", "event", "focus", "text", "accessibility"}, State: map[string]string{"focused": "false", "press_count": "1", "action": "reset", "accessibility_role": "button"}},
			{ID: "StatusText", Type: "lib.core.widgets.Text", Parent: "Column", Bounds: surface.RectReport{X: 20, Y: 280, W: 440, H: 24}, Abilities: []string{"measure", "layout", "draw", "event", "focus", "text", "accessibility"}, State: map[string]string{"role": "status", "status_code": "2", "accessibility_role": "status"}},
		},
		ComponentTree:     accessibilityComponentTreeReport(),
		ComponentTreeAPI:  accessibilityComponentTreeAPIReport(),
		Toolkit:           accessibilityToolkitReport(),
		AccessibilityTree: accessibilityTreeReport(beforeFrame, nameFrame, saveFrame, resetFrame, afterFrame),
		Events: []surface.EventReport{
			{Order: 1, Kind: "mouse_up", TargetComponent: "NameTextBox", DispatchPath: []string{"AccessibilitySettingsApp", "Panel", "Column", "NameTextBox"}, Handled: true, Pass: true, X: 40, Y: 100, Width: 320, Height: 240, BufferSlots: []int{5, 40, 100, 1, 0, 320, 240, 0, 0}, BeforeState: map[string]string{"AccessibilitySettingsApp.focused_id": "-1", "NameTextBox.focused": "false"}, AfterState: map[string]string{"AccessibilitySettingsApp.focused_id": "5", "NameTextBox.focused": "true"}},
			{Order: 2, Kind: "text_input", TargetComponent: "NameTextBox", DispatchPath: []string{"AccessibilitySettingsApp", "Panel", "Column", "NameTextBox"}, Handled: true, Pass: true, Width: 320, Height: 240, TimestampMS: 1, TextLen: 3, TextBytesHex: "416461", BufferSlots: []int{8, 0, 0, 0, 0, 320, 240, 1, 3}, BeforeState: map[string]string{"NameTextBox.buffer": "", "NameTextBox.caret": "0", "EmailTextBox.buffer": ""}, AfterState: map[string]string{"NameTextBox.buffer": "Ada", "NameTextBox.caret": "3", "EmailTextBox.buffer": ""}},
			{Order: 3, Kind: "key_down", TargetComponent: "AccessibilitySettingsApp", DispatchPath: []string{"AccessibilitySettingsApp"}, Handled: true, Pass: true, Key: 9, Width: 320, Height: 240, TimestampMS: 2, BufferSlots: []int{6, 0, 0, 0, 9, 320, 240, 2, 0}, BeforeState: map[string]string{"AccessibilitySettingsApp.focused_id": "5"}, AfterState: map[string]string{"AccessibilitySettingsApp.focused_id": "7"}},
			{Order: 4, Kind: "text_input", TargetComponent: "EmailTextBox", DispatchPath: []string{"AccessibilitySettingsApp", "Panel", "Column", "EmailTextBox"}, Handled: true, Pass: true, Width: 320, Height: 240, TimestampMS: 3, TextLen: 5, TextBytesHex: "7465747261", BufferSlots: []int{8, 0, 0, 0, 0, 320, 240, 3, 5}, BeforeState: map[string]string{"EmailTextBox.buffer": "", "NameTextBox.buffer": "Ada"}, AfterState: map[string]string{"EmailTextBox.buffer": "tetra", "NameTextBox.buffer": "Ada"}},
			{Order: 5, Kind: "key_down", TargetComponent: "AccessibilitySettingsApp", DispatchPath: []string{"AccessibilitySettingsApp"}, Handled: true, Pass: true, Key: 9, Width: 320, Height: 240, TimestampMS: 4, BufferSlots: []int{6, 0, 0, 0, 9, 320, 240, 4, 0}, BeforeState: map[string]string{"AccessibilitySettingsApp.focused_id": "7"}, AfterState: map[string]string{"AccessibilitySettingsApp.focused_id": "9"}},
			{Order: 6, Kind: "key_down", TargetComponent: "SaveButton", DispatchPath: []string{"AccessibilitySettingsApp", "Panel", "Column", "ButtonRow", "SaveButton"}, Handled: true, Pass: true, Key: 32, Width: 320, Height: 240, TimestampMS: 5, BufferSlots: []int{6, 0, 0, 0, 32, 320, 240, 5, 0}, BeforeState: map[string]string{"AccessibilitySettingsApp.focused_id": "9", "AccessibilitySettingsApp.save_count": "0", "StatusText.status_code": "0"}, AfterState: map[string]string{"AccessibilitySettingsApp.focused_id": "9", "AccessibilitySettingsApp.save_count": "1", "StatusText.status_code": "1"}},
			{Order: 7, Kind: "key_down", TargetComponent: "AccessibilitySettingsApp", DispatchPath: []string{"AccessibilitySettingsApp"}, Handled: true, Pass: true, Key: 9, Width: 320, Height: 240, TimestampMS: 6, BufferSlots: []int{6, 0, 0, 0, 9, 320, 240, 6, 0}, BeforeState: map[string]string{"AccessibilitySettingsApp.focused_id": "9"}, AfterState: map[string]string{"AccessibilitySettingsApp.focused_id": "10"}},
			{Order: 8, Kind: "key_down", TargetComponent: "ResetButton", DispatchPath: []string{"AccessibilitySettingsApp", "Panel", "Column", "ButtonRow", "ResetButton"}, Handled: true, Pass: true, Key: 13, Width: 320, Height: 240, TimestampMS: 7, BufferSlots: []int{6, 0, 0, 0, 13, 320, 240, 7, 0}, BeforeState: map[string]string{"AccessibilitySettingsApp.focused_id": "10", "AccessibilitySettingsApp.reset_count": "0", "StatusText.status_code": "1", "NameTextBox.buffer": "Ada", "EmailTextBox.buffer": "tetra"}, AfterState: map[string]string{"AccessibilitySettingsApp.focused_id": "10", "AccessibilitySettingsApp.reset_count": "1", "StatusText.status_code": "2", "NameTextBox.buffer": "", "EmailTextBox.buffer": ""}},
			{Order: 9, Kind: "key_down", TargetComponent: "AccessibilitySettingsApp", DispatchPath: []string{"AccessibilitySettingsApp"}, Handled: true, Pass: true, Key: 9, Width: 320, Height: 240, TimestampMS: 8, BufferSlots: []int{6, 0, 0, 0, 9, 320, 240, 8, 0}, BeforeState: map[string]string{"AccessibilitySettingsApp.focused_id": "10"}, AfterState: map[string]string{"AccessibilitySettingsApp.focused_id": "5"}},
			{Order: 10, Kind: "resize", TargetComponent: "AccessibilitySettingsApp", DispatchPath: []string{"AccessibilitySettingsApp"}, Handled: true, Pass: true, Width: 480, Height: 320, TimestampMS: 9, BufferSlots: []int{2, 0, 0, 0, 0, 480, 320, 9, 0}, BeforeState: map[string]string{"AccessibilitySettingsApp.focused_id": "5", "NameTextBox.bounds.w": "280", "EmailTextBox.bounds.w": "280"}, AfterState: map[string]string{"AccessibilitySettingsApp.focused_id": "5", "NameTextBox.bounds.w": "440", "EmailTextBox.bounds.w": "440"}},
		},
		Frames: []surface.FrameReport{
			{Order: 1, Width: beforeFrame.Width, Height: beforeFrame.Height, Stride: beforeFrame.Stride, Checksum: checksumRGBA(beforeFrame.Pixels), Presented: true},
			{Order: 2, Width: nameFrame.Width, Height: nameFrame.Height, Stride: nameFrame.Stride, Checksum: checksumRGBA(nameFrame.Pixels), Presented: true},
			{Order: 3, Width: saveFrame.Width, Height: saveFrame.Height, Stride: saveFrame.Stride, Checksum: checksumRGBA(saveFrame.Pixels), Presented: true},
			{Order: 4, Width: resetFrame.Width, Height: resetFrame.Height, Stride: resetFrame.Stride, Checksum: checksumRGBA(resetFrame.Pixels), Presented: true},
			{Order: 5, Width: afterFrame.Width, Height: afterFrame.Height, Stride: afterFrame.Stride, Checksum: checksumRGBA(afterFrame.Pixels), Presented: true},
		},
		StateTransitions: []surface.StateTransitionReport{
			{Order: 1, Component: "AccessibilitySettingsApp", Field: "focused_id", Before: "-1", After: "5", Cause: "mouse_up"},
			{Order: 2, Component: "NameTextBox", Field: "buffer", Before: "", After: "Ada", Cause: "text_input"},
			{Order: 3, Component: "AccessibilitySettingsApp", Field: "focused_id", Before: "5", After: "7", Cause: "tab"},
			{Order: 4, Component: "EmailTextBox", Field: "buffer", Before: "", After: "tetra", Cause: "text_input"},
			{Order: 5, Component: "AccessibilitySettingsApp", Field: "focused_id", Before: "7", After: "9", Cause: "tab"},
			{Order: 6, Component: "AccessibilitySettingsApp", Field: "save_count", Before: "0", After: "1", Cause: "key_down"},
			{Order: 7, Component: "StatusText", Field: "status_code", Before: "0", After: "1", Cause: "save"},
			{Order: 8, Component: "AccessibilitySettingsApp", Field: "focused_id", Before: "9", After: "10", Cause: "tab"},
			{Order: 9, Component: "NameTextBox", Field: "buffer", Before: "Ada", After: "", Cause: "reset"},
			{Order: 10, Component: "EmailTextBox", Field: "buffer", Before: "tetra", After: "", Cause: "reset"},
			{Order: 11, Component: "AccessibilitySettingsApp", Field: "reset_count", Before: "0", After: "1", Cause: "key_down"},
			{Order: 12, Component: "StatusText", Field: "status_code", Before: "1", After: "2", Cause: "reset"},
			{Order: 13, Component: "AccessibilitySettingsApp", Field: "focused_id", Before: "10", After: "5", Cause: "tab"},
			{Order: 14, Component: "AccessibilitySettingsApp", Field: "NameTextBox.bounds.w", Before: "280", After: "440", Cause: "resize"},
			{Order: 15, Component: "AccessibilitySettingsApp", Field: "EmailTextBox.bounds.w", Before: "280", After: "440", Cause: "resize"},
		},
		Cases: accessibilityMetadataBaseCases(),
	}
	switch mode {
	case "headless-accessibility-metadata":
		scenario.Cases = append(scenario.Cases,
			surface.CaseReport{Name: "headless event dispatch", Kind: "positive", Ran: true, Pass: true},
			surface.CaseReport{Name: "headless framebuffer checksum", Kind: "positive", Ran: true, Pass: true},
			surface.CaseReport{Name: "headless actual runner trace", Kind: "positive", Ran: true, Pass: true},
		)
	case "linux-x64-real-window-accessibility-metadata":
		scenario.Cases = append(scenario.Cases,
			surface.CaseReport{Name: "linux-x64 Surface Host ABI open/present/close", Kind: "positive", Ran: true, Pass: true},
			surface.CaseReport{Name: "linux-x64 real-window surface", Kind: "positive", Ran: true, Pass: true},
			surface.CaseReport{Name: "linux-x64 native input event pump", Kind: "positive", Ran: true, Pass: true},
			surface.CaseReport{Name: "linux-x64 real-window resize event", Kind: "positive", Ran: true, Pass: true},
			surface.CaseReport{Name: "linux-x64 real-window close event", Kind: "positive", Ran: true, Pass: true},
		)
	case "wasm32-web-browser-canvas-accessibility-metadata":
		scenario.Frames = nil
		scenario.Cases = append(scenario.Cases,
			surface.CaseReport{Name: "wasm32-web browser canvas surface", Kind: "positive", Ran: true, Pass: true},
			surface.CaseReport{Name: "wasm32-web browser canvas RGBA readback", Kind: "positive", Ran: true, Pass: true},
			surface.CaseReport{Name: "wasm32-web browser canvas pointer input", Kind: "positive", Ran: true, Pass: true},
			surface.CaseReport{Name: "wasm32-web browser canvas keyboard input", Kind: "positive", Ran: true, Pass: true},
			surface.CaseReport{Name: "wasm32-web browser canvas resize input", Kind: "positive", Ran: true, Pass: true},
			surface.CaseReport{Name: "wasm32-web browser canvas text input", Kind: "positive", Ran: true, Pass: true},
			surface.CaseReport{Name: "wasm32-web Surface Host ABI imports", Kind: "positive", Ran: true, Pass: true},
			surface.CaseReport{Name: "compiler-owned wasm Surface loader", Kind: "positive", Ran: true, Pass: true},
			surface.CaseReport{Name: "compiler-owned browser canvas Surface host", Kind: "positive", Ran: true, Pass: true},
		)
	}
	return scenario
}
func accessibilityMetadataBaseCases() []surface.CaseReport {
	cases := toolkitReuseBaseCases()
	cases = append(cases,
		surface.CaseReport{Name: "accessibility metadata tree schema", Kind: "positive", Ran: true, Pass: true},
		surface.CaseReport{Name: "accessibility metadata roles labels values states", Kind: "positive", Ran: true, Pass: true},
		surface.CaseReport{Name: "accessibility metadata component tree alignment", Kind: "positive", Ran: true, Pass: true},
		surface.CaseReport{Name: "accessibility metadata focus order alignment", Kind: "positive", Ran: true, Pass: true},
		surface.CaseReport{Name: "accessibility metadata reading order", Kind: "positive", Ran: true, Pass: true},
		surface.CaseReport{Name: "accessibility metadata snapshots update", Kind: "positive", Ran: true, Pass: true},
		surface.CaseReport{Name: "accessibility metadata no DOM ARIA platform host claim", Kind: "positive", Ran: true, Pass: true},
	)
	return cases
}
func toolkitReuseBaseCases() []surface.CaseReport {
	cases := minimalToolkitBaseCases()
	cases = append(cases,
		surface.CaseReport{Name: "toolkit reuse second example evidence", Kind: "positive", Ran: true, Pass: true},
		surface.CaseReport{Name: "toolkit reuse widgets module evidence", Kind: "positive", Ran: true, Pass: true},
		surface.CaseReport{Name: "toolkit reuse multi TextBox routing", Kind: "positive", Ran: true, Pass: true},
		surface.CaseReport{Name: "toolkit reuse focused TextBox only mutates", Kind: "positive", Ran: true, Pass: true},
		surface.CaseReport{Name: "toolkit reuse Save action routed", Kind: "positive", Ran: true, Pass: true},
		surface.CaseReport{Name: "toolkit reuse Reset action routed", Kind: "positive", Ran: true, Pass: true},
		surface.CaseReport{Name: "toolkit reuse StatusText updates", Kind: "positive", Ran: true, Pass: true},
		surface.CaseReport{Name: "toolkit reuse resize relayout", Kind: "positive", Ran: true, Pass: true},
		surface.CaseReport{Name: "toolkit reuse changed frame checksums", Kind: "positive", Ran: true, Pass: true},
		surface.CaseReport{Name: "toolkit reuse no demo-local widget structs", Kind: "positive", Ran: true, Pass: true},
	)
	return cases
}
func minimalToolkitBaseCases() []surface.CaseReport {
	return []surface.CaseReport{
		{Name: "pure Tetra component app", Kind: "positive", Ran: true, Pass: true},
		{Name: "host-provided pointer event dispatch", Kind: "positive", Ran: true, Pass: true},
		{Name: "host event buffer poll_event", Kind: "positive", Ran: true, Pass: true},
		{Name: "pre/post event frame sequence", Kind: "positive", Ran: true, Pass: true},
		{Name: "component hierarchy dispatch", Kind: "positive", Ran: true, Pass: true},
		{Name: "component text input scalar dispatch", Kind: "positive", Ran: true, Pass: true},
		{Name: "host text payload buffer", Kind: "positive", Ran: true, Pass: true},
		{Name: "component focus dispatch", Kind: "positive", Ran: true, Pass: true},
		{Name: "component accessibility metadata", Kind: "positive", Ran: true, Pass: true},
		{Name: "no legacy UI sidecar artifacts", Kind: "positive", Ran: true, Pass: true},
		{Name: "state transition", Kind: "positive", Ran: true, Pass: true},
		{Name: "component tree node count", Kind: "positive", Ran: true, Pass: true},
		{Name: "component tree parent child links", Kind: "positive", Ran: true, Pass: true},
		{Name: "component tree layout bounds", Kind: "positive", Ran: true, Pass: true},
		{Name: "component tree draw traversal", Kind: "positive", Ran: true, Pass: true},
		{Name: "component tree pointer dispatch path", Kind: "positive", Ran: true, Pass: true},
		{Name: "component tree focus traversal", Kind: "positive", Ran: true, Pass: true},
		{Name: "component tree text routed to focused TextBox", Kind: "positive", Ran: true, Pass: true},
		{Name: "component tree button action dispatch", Kind: "positive", Ran: true, Pass: true},
		{Name: "component tree resize relayout", Kind: "positive", Ran: true, Pass: true},
		{Name: "component tree rendered frame update", Kind: "positive", Ran: true, Pass: true},
		{Name: "component tree api builder node creation", Kind: "positive", Ran: true, Pass: true},
		{Name: "component tree api parent child invariants", Kind: "positive", Ran: true, Pass: true},
		{Name: "component tree api layout helper dispatch", Kind: "positive", Ran: true, Pass: true},
		{Name: "component tree api hit test helper", Kind: "positive", Ran: true, Pass: true},
		{Name: "component tree api focus helper traversal", Kind: "positive", Ran: true, Pass: true},
		{Name: "component tree api dispatch path helper", Kind: "positive", Ran: true, Pass: true},
		{Name: "component tree api no manual bookkeeping", Kind: "positive", Ran: true, Pass: true},
		{Name: "reject legacy UI evidence", Kind: "negative", Ran: true, Pass: true, ExpectedError: "legacy UI evidence rejected"},
		{Name: "minimal toolkit reusable widgets", Kind: "positive", Ran: true, Pass: true},
		{Name: "minimal toolkit Text widget evidence", Kind: "positive", Ran: true, Pass: true},
		{Name: "minimal toolkit Button widget evidence", Kind: "positive", Ran: true, Pass: true},
		{Name: "minimal toolkit TextBox widget evidence", Kind: "positive", Ran: true, Pass: true},
		{Name: "minimal toolkit Row Column Panel layout", Kind: "positive", Ran: true, Pass: true},
		{Name: "minimal toolkit tree api reuse", Kind: "positive", Ran: true, Pass: true},
		{Name: "minimal toolkit TextBox focus input editing", Kind: "positive", Ran: true, Pass: true},
		{Name: "minimal toolkit Submit action routed", Kind: "positive", Ran: true, Pass: true},
		{Name: "minimal toolkit Reset action routed", Kind: "positive", Ran: true, Pass: true},
		{Name: "minimal toolkit status text update", Kind: "positive", Ran: true, Pass: true},
		{Name: "minimal toolkit resize relayout", Kind: "positive", Ran: true, Pass: true},
		{Name: "minimal toolkit rendered frame update", Kind: "positive", Ran: true, Pass: true},
	}
}
func minimalToolkitComponentTreeAPIReport() *surface.ComponentTreeAPIReport {
	return &surface.ComponentTreeAPIReport{
		Schema:            "tetra.surface.component-tree-api.v1",
		APILevel:          "builder-layout-dispatch-v1",
		Source:            "examples/surface_toolkit_form.tetra",
		ManualBookkeeping: false,
		Builder: surface.ComponentTreeAPIBuilderReport{
			RootCreatedBy:     "tree_add_root",
			ChildrenCreatedBy: "tree_add_child",
			NodeCount:         9,
			Capacity:          16,
			OverflowChecked:   true,
		},
		Invariants: surface.ComponentTreeAPIInvariantReport{
			TreeValidateRan:         true,
			TreeValidateStatus:      0,
			ParentChildLinksChecked: true,
			ChildIndicesChecked:     true,
			ChildCountChecked:       true,
			FirstChildChecked:       true,
		},
		LayoutHelpers: []surface.ComponentTreeAPILayoutHelperReport{
			{Helper: "widgets.panel_content_rect", Target: "Panel", Pass: "initial", ChangedBounds: true},
			{Helper: "widgets.column_layout", Target: "Column", Pass: "initial", ChangedBounds: true},
			{Helper: "widgets.row_layout", Target: "ButtonRow", Pass: "initial", ChangedBounds: true},
			{Helper: "widgets.column_layout", Target: "Column", Pass: "resize", ChangedBounds: true},
		},
		FocusHelpers: []surface.ComponentTreeAPIFocusHelperReport{
			{Helper: "tree_focus_next", Before: "TextBox", After: "SubmitButton"},
			{Helper: "tree_focus_next", Before: "SubmitButton", After: "ResetButton"},
			{Helper: "tree_focus_next", Before: "ResetButton", After: "TextBox"},
		},
		HitTests: []surface.ComponentTreeAPIHitTestReport{
			{Helper: "widgets.hit_test", X: 40, Y: 72, Target: "TextBox", Path: []int{0, 1, 2, 4}},
			{Helper: "widgets.hit_test", X: 180, Y: 124, Target: "ResetButton", Path: []int{0, 1, 2, 5, 7}},
		},
		DispatchPaths: []surface.ComponentTreeAPIDispatchPathReport{
			{Helper: "tree_build_dispatch_path", Target: "TextBox", Path: []int{0, 1, 2, 4}},
			{Helper: "tree_build_dispatch_path", Target: "SubmitButton", Path: []int{0, 1, 2, 5, 6}},
			{Helper: "tree_build_dispatch_path", Target: "ResetButton", Path: []int{0, 1, 2, 5, 7}},
		},
	}
}
func minimalToolkitReport() *surface.ToolkitReport {
	return &surface.ToolkitReport{
		Schema:                    "tetra.surface.toolkit.v1",
		ToolkitLevel:              "minimal-widgets-v1",
		Source:                    "examples/surface_toolkit_form.tetra",
		Module:                    "lib.core.widgets",
		Experimental:              true,
		ProductionClaim:           false,
		UsesComponentTreeAPI:      true,
		ManualBookkeeping:         false,
		DemoSpecificWidgetStructs: false,
		NoMagicWidgets:            true,
		NoPlatformWidgets:         true,
		NoDOMUI:                   true,
		NoUserJS:                  true,
		Widgets: []surface.ToolkitWidgetReport{
			{Name: "Panel", Kind: "Panel", NodeID: 1, Reusable: true, OrdinaryTetraStruct: true},
			{Name: "Column", Kind: "Column", NodeID: 2, Reusable: true, OrdinaryTetraStruct: true},
			{Name: "NameLabel", Kind: "Text", NodeID: 3, Role: "label", Reusable: true, OrdinaryTetraStruct: true},
			{Name: "TextBox", Kind: "TextBox", NodeID: 4, Reusable: true, OrdinaryTetraStruct: true, Editable: true},
			{Name: "ButtonRow", Kind: "Row", NodeID: 5, Reusable: true, OrdinaryTetraStruct: true},
			{Name: "SubmitButton", Kind: "Button", NodeID: 6, Action: "submit", Reusable: true, OrdinaryTetraStruct: true},
			{Name: "ResetButton", Kind: "Button", NodeID: 7, Action: "reset", Reusable: true, OrdinaryTetraStruct: true},
			{Name: "StatusText", Kind: "Text", NodeID: 8, Role: "status", Reusable: true, OrdinaryTetraStruct: true},
		},
		ReusableSources: []string{
			"lib/core/widgets.tetra:panel_init",
			"lib/core/widgets.tetra:column_init",
			"lib/core/widgets.tetra:text_init",
			"lib/core/widgets.tetra:textbox_init",
			"lib/core/widgets.tetra:row_init",
			"lib/core/widgets.tetra:button_init",
		},
	}
}
func toolkitReuseComponentTreeAPIReport() *surface.ComponentTreeAPIReport {
	return &surface.ComponentTreeAPIReport{
		Schema:            "tetra.surface.component-tree-api.v1",
		APILevel:          "builder-layout-dispatch-v1",
		Source:            "examples/surface_toolkit_settings.tetra",
		ManualBookkeeping: false,
		Builder: surface.ComponentTreeAPIBuilderReport{
			RootCreatedBy:     "tree_add_root",
			ChildrenCreatedBy: "tree_add_child",
			NodeCount:         11,
			Capacity:          20,
			OverflowChecked:   true,
		},
		Invariants: surface.ComponentTreeAPIInvariantReport{
			TreeValidateRan:         true,
			TreeValidateStatus:      0,
			ParentChildLinksChecked: true,
			ChildIndicesChecked:     true,
			ChildCountChecked:       true,
			FirstChildChecked:       true,
		},
		LayoutHelpers: []surface.ComponentTreeAPILayoutHelperReport{
			{Helper: "widgets.panel_content_rect", Target: "Panel", Pass: "initial", ChangedBounds: true},
			{Helper: "widgets.column_layout", Target: "Column", Pass: "initial", ChangedBounds: true},
			{Helper: "widgets.row_layout", Target: "ButtonRow", Pass: "initial", ChangedBounds: true},
			{Helper: "widgets.column_layout", Target: "Column", Pass: "resize", ChangedBounds: true},
		},
		FocusHelpers: []surface.ComponentTreeAPIFocusHelperReport{
			{Helper: "tree_focus_next", Before: "NameTextBox", After: "EmailTextBox"},
			{Helper: "tree_focus_next", Before: "EmailTextBox", After: "SaveButton"},
			{Helper: "tree_focus_next", Before: "SaveButton", After: "ResetButton"},
			{Helper: "tree_focus_next", Before: "ResetButton", After: "NameTextBox"},
		},
		HitTests: []surface.ComponentTreeAPIHitTestReport{
			{Helper: "widgets.hit_test", X: 40, Y: 72, Target: "NameTextBox", Path: []int{0, 1, 2, 4}},
			{Helper: "widgets.hit_test", X: 40, Y: 156, Target: "EmailTextBox", Path: []int{0, 1, 2, 6}},
			{Helper: "widgets.hit_test", X: 180, Y: 208, Target: "ResetButton", Path: []int{0, 1, 2, 7, 9}},
		},
		DispatchPaths: []surface.ComponentTreeAPIDispatchPathReport{
			{Helper: "tree_build_dispatch_path", Target: "NameTextBox", Path: []int{0, 1, 2, 4}},
			{Helper: "tree_build_dispatch_path", Target: "EmailTextBox", Path: []int{0, 1, 2, 6}},
			{Helper: "tree_build_dispatch_path", Target: "SaveButton", Path: []int{0, 1, 2, 7, 8}},
			{Helper: "tree_build_dispatch_path", Target: "ResetButton", Path: []int{0, 1, 2, 7, 9}},
		},
	}
}
func toolkitReuseReport() *surface.ToolkitReport {
	return &surface.ToolkitReport{
		Schema:                    "tetra.surface.toolkit.v1",
		ToolkitLevel:              "toolkit-reuse-v1",
		ReuseLevel:                "multi-form-widget-reuse-v1",
		Source:                    "examples/surface_toolkit_settings.tetra",
		Sources:                   []string{"examples/surface_toolkit_form.tetra", "examples/surface_toolkit_settings.tetra"},
		Module:                    "lib.core.widgets",
		Experimental:              true,
		ProductionClaim:           false,
		UsesComponentTreeAPI:      true,
		ManualBookkeeping:         false,
		DemoSpecificWidgetStructs: false,
		NoMagicWidgets:            true,
		NoPlatformWidgets:         true,
		NoDOMUI:                   true,
		NoUserJS:                  true,
		ExampleCount:              2,
		TextBoxCount:              2,
		ButtonCount:               2,
		MultiTextBoxEvidence:      true,
		MultiFormEvidence:         true,
		Widgets: []surface.ToolkitWidgetReport{
			{Name: "Panel", Kind: "Panel", NodeID: 1, Reusable: true, OrdinaryTetraStruct: true},
			{Name: "Column", Kind: "Column", NodeID: 2, Reusable: true, OrdinaryTetraStruct: true},
			{Name: "TitleText", Kind: "Text", NodeID: 3, Role: "label", Reusable: true, OrdinaryTetraStruct: true},
			{Name: "NameTextBox", Kind: "TextBox", NodeID: 4, Reusable: true, OrdinaryTetraStruct: true, Editable: true},
			{Name: "NameLabel", Kind: "Text", NodeID: 5, Role: "label", Reusable: true, OrdinaryTetraStruct: true},
			{Name: "EmailTextBox", Kind: "TextBox", NodeID: 6, Reusable: true, OrdinaryTetraStruct: true, Editable: true},
			{Name: "ButtonRow", Kind: "Row", NodeID: 7, Reusable: true, OrdinaryTetraStruct: true},
			{Name: "SaveButton", Kind: "Button", NodeID: 8, Action: "save", Reusable: true, OrdinaryTetraStruct: true},
			{Name: "ResetButton", Kind: "Button", NodeID: 9, Action: "reset", Reusable: true, OrdinaryTetraStruct: true},
			{Name: "StatusText", Kind: "Text", NodeID: 10, Role: "status", Reusable: true, OrdinaryTetraStruct: true},
		},
		ReusableSources: []string{
			"lib/core/widgets.tetra:panel_init",
			"lib/core/widgets.tetra:column_init",
			"lib/core/widgets.tetra:text_init",
			"lib/core/widgets.tetra:textbox_init",
			"lib/core/widgets.tetra:row_init",
			"lib/core/widgets.tetra:button_init",
			"lib/core/widgets.tetra:hit_test",
			"lib/core/widgets.tetra:textbox_text_input",
			"lib/core/widgets.tetra:button_key_event",
		},
	}
}
func productionToolkitBaseCases() []surface.CaseReport {
	cases := toolkitReuseBaseCases()
	cases = append(cases,
		surface.CaseReport{Name: "production toolkit required widget set", Kind: "positive", Ran: true, Pass: true},
		surface.CaseReport{Name: "production toolkit style module default theme", Kind: "positive", Ran: true, Pass: true},
		surface.CaseReport{Name: "production toolkit style states normal focused hovered pressed disabled error", Kind: "positive", Ran: true, Pass: true},
		surface.CaseReport{Name: "production toolkit Text Label StatusText evidence", Kind: "positive", Ran: true, Pass: true},
		surface.CaseReport{Name: "production toolkit Button TextBox Checkbox evidence", Kind: "positive", Ran: true, Pass: true},
		surface.CaseReport{Name: "production toolkit Row Column Panel Stack Scroll Spacer layout", Kind: "positive", Ran: true, Pass: true},
		surface.CaseReport{Name: "production toolkit component tree api reuse", Kind: "positive", Ran: true, Pass: true},
		surface.CaseReport{Name: "production toolkit TextBox focus input editing", Kind: "positive", Ran: true, Pass: true},
		surface.CaseReport{Name: "production toolkit Checkbox toggle routed", Kind: "positive", Ran: true, Pass: true},
		surface.CaseReport{Name: "production toolkit Scroll offset routed", Kind: "positive", Ran: true, Pass: true},
		surface.CaseReport{Name: "production toolkit Save action routed", Kind: "positive", Ran: true, Pass: true},
		surface.CaseReport{Name: "production toolkit Reset action routed", Kind: "positive", Ran: true, Pass: true},
		surface.CaseReport{Name: "production toolkit StatusText updates", Kind: "positive", Ran: true, Pass: true},
		surface.CaseReport{Name: "production toolkit safe text storage", Kind: "positive", Ran: true, Pass: true},
		surface.CaseReport{Name: "production toolkit no demo-local widget structs", Kind: "positive", Ran: true, Pass: true},
		surface.CaseReport{Name: "production toolkit browser host separation", Kind: "positive", Ran: true, Pass: true},
		surface.CaseReport{Name: "production toolkit rendered frame update", Kind: "positive", Ran: true, Pass: true},
	)
	return cases
}
func productionToolkitComponentTreeAPIReport() *surface.ComponentTreeAPIReport {
	return &surface.ComponentTreeAPIReport{
		Schema:            "tetra.surface.component-tree-api.v1",
		APILevel:          "builder-layout-dispatch-v1",
		Source:            "examples/surface_release_form.tetra",
		ManualBookkeeping: false,
		Builder: surface.ComponentTreeAPIBuilderReport{
			RootCreatedBy:     "tree_add_root",
			ChildrenCreatedBy: "tree_add_child",
			NodeCount:         18,
			Capacity:          32,
			OverflowChecked:   true,
		},
		Invariants: surface.ComponentTreeAPIInvariantReport{
			TreeValidateRan:         true,
			TreeValidateStatus:      0,
			ParentChildLinksChecked: true,
			ChildIndicesChecked:     true,
			ChildCountChecked:       true,
			FirstChildChecked:       true,
		},
		LayoutHelpers: []surface.ComponentTreeAPILayoutHelperReport{
			{Helper: "widgets.panel_content_rect", Target: "Panel", Pass: "initial", ChangedBounds: true},
			{Helper: "widgets.stack_layout", Target: "Stack", Pass: "initial", ChangedBounds: true},
			{Helper: "widgets.column_layout", Target: "Column", Pass: "initial", ChangedBounds: true},
			{Helper: "widgets.scroll_set_offset", Target: "TermsScroll", Pass: "scroll", ChangedBounds: true},
			{Helper: "widgets.row_layout", Target: "ButtonRow", Pass: "initial", ChangedBounds: true},
			{Helper: "widgets.column_layout", Target: "Column", Pass: "resize", ChangedBounds: true},
		},
		FocusHelpers: []surface.ComponentTreeAPIFocusHelperReport{
			{Helper: "tree_focus_next", Before: "NameTextBox", After: "EmailTextBox"},
			{Helper: "tree_focus_next", Before: "EmailTextBox", After: "SubscribeCheckbox"},
			{Helper: "tree_focus_next", Before: "SubscribeCheckbox", After: "SaveButton"},
			{Helper: "tree_focus_next", Before: "SaveButton", After: "ResetButton"},
			{Helper: "tree_focus_next", Before: "ResetButton", After: "NameTextBox"},
		},
		HitTests: []surface.ComponentTreeAPIHitTestReport{
			{Helper: "widgets.hit_test_release_form", X: 48, Y: 148, Target: "NameTextBox", Path: []int{0, 1, 2, 3, 7}},
			{Helper: "widgets.hit_test_release_form", X: 48, Y: 228, Target: "EmailTextBox", Path: []int{0, 1, 2, 3, 9}},
			{Helper: "widgets.hit_test_release_form", X: 48, Y: 280, Target: "SubscribeCheckbox", Path: []int{0, 1, 2, 3, 10}},
			{Helper: "widgets.hit_test_release_form", X: 192, Y: 376, Target: "ResetButton", Path: []int{0, 1, 2, 3, 13, 15}},
		},
		DispatchPaths: []surface.ComponentTreeAPIDispatchPathReport{
			{Helper: "tree_build_dispatch_path", Target: "NameTextBox", Path: []int{0, 1, 2, 3, 7}},
			{Helper: "tree_build_dispatch_path", Target: "EmailTextBox", Path: []int{0, 1, 2, 3, 9}},
			{Helper: "tree_build_dispatch_path", Target: "SubscribeCheckbox", Path: []int{0, 1, 2, 3, 10}},
			{Helper: "tree_build_dispatch_path", Target: "TermsScroll", Path: []int{0, 1, 2, 3, 11}},
			{Helper: "tree_build_dispatch_path", Target: "SaveButton", Path: []int{0, 1, 2, 3, 13, 14}},
			{Helper: "tree_build_dispatch_path", Target: "ResetButton", Path: []int{0, 1, 2, 3, 13, 15}},
		},
	}
}
func productionToolkitReport() *surface.ToolkitReport {
	return &surface.ToolkitReport{
		Schema:                    "tetra.surface.toolkit.v1",
		ToolkitLevel:              "production-widgets-v1",
		ReleaseScope:              "surface-v1-linux-web",
		Source:                    "examples/surface_release_form.tetra",
		Sources:                   []string{"examples/surface_release_form.tetra", "examples/surface_toolkit_form.tetra", "examples/surface_toolkit_settings.tetra"},
		Module:                    "lib.core.widgets",
		StyleModule:               "lib.core.style",
		Experimental:              false,
		ProductionClaim:           true,
		UsesComponentTreeAPI:      true,
		ManualBookkeeping:         false,
		DemoSpecificWidgetStructs: false,
		NoMagicWidgets:            true,
		NoPlatformWidgets:         true,
		NoDOMUI:                   true,
		NoUserJS:                  true,
		ExampleCount:              3,
		TextBoxCount:              2,
		ButtonCount:               2,
		MultiTextBoxEvidence:      true,
		MultiFormEvidence:         true,
		WidgetSet:                 []string{"Text", "Label", "StatusText", "Button", "TextBox", "Checkbox", "Row", "Column", "Panel", "Stack", "Scroll", "Spacer"},
		StateSet:                  []string{"normal", "focused", "hovered", "pressed", "disabled", "error"},
		LayoutFeatures:            []string{"padding", "margin", "spacing", "min_size", "max_size", "fill", "scroll_offset"},
		Theme:                     true,
		SafeTextStorage:           true,
		Widgets: []surface.ToolkitWidgetReport{
			{Name: "Panel", Kind: "Panel", NodeID: 1, Reusable: true, OrdinaryTetraStruct: true},
			{Name: "Stack", Kind: "Stack", NodeID: 2, Reusable: true, OrdinaryTetraStruct: true},
			{Name: "Column", Kind: "Column", NodeID: 3, Reusable: true, OrdinaryTetraStruct: true},
			{Name: "TitleText", Kind: "Text", NodeID: 4, Role: "label", Reusable: true, OrdinaryTetraStruct: true},
			{Name: "DescriptionText", Kind: "Text", NodeID: 5, Role: "description", Reusable: true, OrdinaryTetraStruct: true},
			{Name: "NameLabel", Kind: "Label", NodeID: 6, Role: "label", Reusable: true, OrdinaryTetraStruct: true},
			{Name: "NameTextBox", Kind: "TextBox", NodeID: 7, Reusable: true, OrdinaryTetraStruct: true, Editable: true},
			{Name: "EmailLabel", Kind: "Label", NodeID: 8, Role: "label", Reusable: true, OrdinaryTetraStruct: true},
			{Name: "EmailTextBox", Kind: "TextBox", NodeID: 9, Reusable: true, OrdinaryTetraStruct: true, Editable: true},
			{Name: "SubscribeCheckbox", Kind: "Checkbox", NodeID: 10, Reusable: true, OrdinaryTetraStruct: true},
			{Name: "TermsScroll", Kind: "Scroll", NodeID: 11, Reusable: true, OrdinaryTetraStruct: true},
			{Name: "TermsText", Kind: "Text", NodeID: 12, Role: "description", Reusable: true, OrdinaryTetraStruct: true},
			{Name: "ButtonRow", Kind: "Row", NodeID: 13, Reusable: true, OrdinaryTetraStruct: true},
			{Name: "SaveButton", Kind: "Button", NodeID: 14, Action: "save", Reusable: true, OrdinaryTetraStruct: true},
			{Name: "ResetButton", Kind: "Button", NodeID: 15, Action: "reset", Reusable: true, OrdinaryTetraStruct: true},
			{Name: "Spacer", Kind: "Spacer", NodeID: 16, Reusable: true, OrdinaryTetraStruct: true},
			{Name: "StatusText", Kind: "StatusText", NodeID: 17, Role: "status", Reusable: true, OrdinaryTetraStruct: true},
		},
		ReusableSources: []string{
			"lib/core/widgets.tetra:panel_init",
			"lib/core/widgets.tetra:column_init",
			"lib/core/widgets.tetra:text_init",
			"lib/core/widgets.tetra:label_init",
			"lib/core/widgets.tetra:status_text_init",
			"lib/core/widgets.tetra:textbox_init",
			"lib/core/widgets.tetra:checkbox_init",
			"lib/core/widgets.tetra:checkbox_toggle",
			"lib/core/widgets.tetra:row_init",
			"lib/core/widgets.tetra:stack_init",
			"lib/core/widgets.tetra:scroll_init",
			"lib/core/widgets.tetra:scroll_set_offset",
			"lib/core/widgets.tetra:spacer_init",
			"lib/core/widgets.tetra:button_init",
			"lib/core/widgets.tetra:hit_test_release_form",
			"lib/core/style.tetra:default_theme",
			"lib/core/style.tetra:style_for_state",
		},
	}
}
func accessibilityComponentTreeReport() *surface.ComponentTreeReport {
	return &surface.ComponentTreeReport{
		Schema:       "tetra.surface.component-tree.v1",
		DynamicLevel: "accessibility-metadata-tree-v1",
		RootID:       0,
		NodeCount:    12,
		FocusedID:    5,
		Nodes: []surface.ComponentTreeNodeReport{
			{ID: 0, Name: "AccessibilitySettingsApp", Kind: "root", ParentID: -1, ChildIndex: 0, FirstChild: 1, ChildCount: 1, Focusable: false, Bounds: surface.RectReport{X: 0, Y: 0, W: 480, H: 320}},
			{ID: 1, Name: "Panel", Kind: "panel", ParentID: 0, ChildIndex: 0, FirstChild: 2, ChildCount: 1, Focusable: false, Bounds: surface.RectReport{X: 0, Y: 0, W: 480, H: 320}},
			{ID: 2, Name: "Column", Kind: "column", ParentID: 1, ChildIndex: 0, FirstChild: 3, ChildCount: 7, Focusable: false, Bounds: surface.RectReport{X: 12, Y: 12, W: 456, H: 296}},
			{ID: 3, Name: "TitleText", Kind: "text", ParentID: 2, ChildIndex: 0, FirstChild: -1, ChildCount: 0, Focusable: false, Bounds: surface.RectReport{X: 20, Y: 20, W: 440, H: 24}},
			{ID: 4, Name: "NameLabel", Kind: "text", ParentID: 2, ChildIndex: 1, FirstChild: -1, ChildCount: 0, Focusable: false, Bounds: surface.RectReport{X: 20, Y: 52, W: 440, H: 24}},
			{ID: 5, Name: "NameTextBox", Kind: "textbox", ParentID: 2, ChildIndex: 2, FirstChild: -1, ChildCount: 0, Focusable: true, Bounds: surface.RectReport{X: 20, Y: 84, W: 440, H: 44}},
			{ID: 6, Name: "EmailLabel", Kind: "text", ParentID: 2, ChildIndex: 3, FirstChild: -1, ChildCount: 0, Focusable: false, Bounds: surface.RectReport{X: 20, Y: 136, W: 440, H: 24}},
			{ID: 7, Name: "EmailTextBox", Kind: "textbox", ParentID: 2, ChildIndex: 4, FirstChild: -1, ChildCount: 0, Focusable: true, Bounds: surface.RectReport{X: 20, Y: 168, W: 440, H: 44}},
			{ID: 8, Name: "ButtonRow", Kind: "row", ParentID: 2, ChildIndex: 5, FirstChild: 9, ChildCount: 2, Focusable: false, Bounds: surface.RectReport{X: 20, Y: 224, W: 440, H: 44}},
			{ID: 9, Name: "SaveButton", Kind: "button", ParentID: 8, ChildIndex: 0, FirstChild: -1, ChildCount: 0, Focusable: true, Bounds: surface.RectReport{X: 20, Y: 224, W: 132, H: 44}},
			{ID: 10, Name: "ResetButton", Kind: "button", ParentID: 8, ChildIndex: 1, FirstChild: -1, ChildCount: 0, Focusable: true, Bounds: surface.RectReport{X: 164, Y: 224, W: 132, H: 44}},
			{ID: 11, Name: "StatusText", Kind: "text", ParentID: 2, ChildIndex: 6, FirstChild: -1, ChildCount: 0, Focusable: false, Bounds: surface.RectReport{X: 20, Y: 280, W: 440, H: 24}},
		},
		LayoutPasses: []surface.ComponentTreeLayoutPassReport{
			{ComponentID: 5, Pass: "initial", Bounds: surface.RectReport{X: 20, Y: 84, W: 280, H: 44}, Measured: surface.SizeReport{W: 280, H: 44}},
			{ComponentID: 7, Pass: "initial", Bounds: surface.RectReport{X: 20, Y: 168, W: 280, H: 44}, Measured: surface.SizeReport{W: 280, H: 44}},
			{ComponentID: 5, Pass: "resize", Bounds: surface.RectReport{X: 20, Y: 84, W: 440, H: 44}, Measured: surface.SizeReport{W: 440, H: 44}},
			{ComponentID: 7, Pass: "resize", Bounds: surface.RectReport{X: 20, Y: 168, W: 440, H: 44}, Measured: surface.SizeReport{W: 440, H: 44}},
			{ComponentID: 11, Pass: "status-update", Bounds: surface.RectReport{X: 20, Y: 280, W: 440, H: 24}, Measured: surface.SizeReport{W: 440, H: 24}},
		},
		DrawOrder:  []int{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11},
		FocusOrder: []int{5, 7, 9, 10},
		DispatchPaths: []surface.ComponentTreeDispatchPathReport{
			{Event: "click", TargetID: 5, X: 40, Y: 100, Path: []int{0, 1, 2, 5}},
			{Event: "click", TargetID: 7, X: 40, Y: 184, Path: []int{0, 1, 2, 7}},
			{Event: "key", TargetID: 9, X: 40, Y: 240, Path: []int{0, 1, 2, 8, 9}},
			{Event: "key", TargetID: 10, X: 180, Y: 240, Path: []int{0, 1, 2, 8, 10}},
		},
	}
}
func accessibilityComponentTreeAPIReport() *surface.ComponentTreeAPIReport {
	return &surface.ComponentTreeAPIReport{
		Schema:            "tetra.surface.component-tree-api.v1",
		APILevel:          "builder-layout-dispatch-v1",
		Source:            "examples/surface_accessibility_settings.tetra",
		ManualBookkeeping: false,
		Builder: surface.ComponentTreeAPIBuilderReport{
			RootCreatedBy:     "tree_add_root",
			ChildrenCreatedBy: "tree_add_child",
			NodeCount:         12,
			Capacity:          24,
			OverflowChecked:   true,
		},
		Invariants: surface.ComponentTreeAPIInvariantReport{
			TreeValidateRan:         true,
			TreeValidateStatus:      0,
			ParentChildLinksChecked: true,
			ChildIndicesChecked:     true,
			ChildCountChecked:       true,
			FirstChildChecked:       true,
		},
		LayoutHelpers: []surface.ComponentTreeAPILayoutHelperReport{
			{Helper: "widgets.panel_content_rect", Target: "Panel", Pass: "initial", ChangedBounds: true},
			{Helper: "widgets.column_layout", Target: "Column", Pass: "initial", ChangedBounds: true},
			{Helper: "widgets.row_layout", Target: "ButtonRow", Pass: "initial", ChangedBounds: true},
			{Helper: "widgets.column_layout", Target: "Column", Pass: "resize", ChangedBounds: true},
		},
		FocusHelpers: []surface.ComponentTreeAPIFocusHelperReport{
			{Helper: "tree_focus_next", Before: "NameTextBox", After: "EmailTextBox"},
			{Helper: "tree_focus_next", Before: "EmailTextBox", After: "SaveButton"},
			{Helper: "tree_focus_next", Before: "SaveButton", After: "ResetButton"},
			{Helper: "tree_focus_next", Before: "ResetButton", After: "NameTextBox"},
		},
		HitTests: []surface.ComponentTreeAPIHitTestReport{
			{Helper: "widgets.hit_test_accessibility_settings", X: 40, Y: 100, Target: "NameTextBox", Path: []int{0, 1, 2, 5}},
			{Helper: "widgets.hit_test_accessibility_settings", X: 40, Y: 184, Target: "EmailTextBox", Path: []int{0, 1, 2, 7}},
			{Helper: "widgets.hit_test_accessibility_settings", X: 180, Y: 240, Target: "ResetButton", Path: []int{0, 1, 2, 8, 10}},
		},
		DispatchPaths: []surface.ComponentTreeAPIDispatchPathReport{
			{Helper: "tree_build_dispatch_path", Target: "NameTextBox", Path: []int{0, 1, 2, 5}},
			{Helper: "tree_build_dispatch_path", Target: "EmailTextBox", Path: []int{0, 1, 2, 7}},
			{Helper: "tree_build_dispatch_path", Target: "SaveButton", Path: []int{0, 1, 2, 8, 9}},
			{Helper: "tree_build_dispatch_path", Target: "ResetButton", Path: []int{0, 1, 2, 8, 10}},
		},
	}
}
func accessibilityToolkitReport() *surface.ToolkitReport {
	return &surface.ToolkitReport{
		Schema:                    "tetra.surface.toolkit.v1",
		ToolkitLevel:              "toolkit-reuse-v1",
		ReuseLevel:                "multi-form-widget-reuse-v1",
		Source:                    "examples/surface_accessibility_settings.tetra",
		Sources:                   []string{"examples/surface_toolkit_form.tetra", "examples/surface_toolkit_settings.tetra", "examples/surface_accessibility_settings.tetra"},
		Module:                    "lib.core.widgets",
		Experimental:              true,
		ProductionClaim:           false,
		UsesComponentTreeAPI:      true,
		ManualBookkeeping:         false,
		DemoSpecificWidgetStructs: false,
		NoMagicWidgets:            true,
		NoPlatformWidgets:         true,
		NoDOMUI:                   true,
		NoUserJS:                  true,
		ExampleCount:              3,
		TextBoxCount:              2,
		ButtonCount:               2,
		MultiTextBoxEvidence:      true,
		MultiFormEvidence:         true,
		Widgets: []surface.ToolkitWidgetReport{
			{Name: "Panel", Kind: "Panel", NodeID: 1, Reusable: true, OrdinaryTetraStruct: true},
			{Name: "Column", Kind: "Column", NodeID: 2, Reusable: true, OrdinaryTetraStruct: true},
			{Name: "TitleText", Kind: "Text", NodeID: 3, Role: "text", Reusable: true, OrdinaryTetraStruct: true},
			{Name: "NameLabel", Kind: "Text", NodeID: 4, Role: "label", Reusable: true, OrdinaryTetraStruct: true},
			{Name: "NameTextBox", Kind: "TextBox", NodeID: 5, Reusable: true, OrdinaryTetraStruct: true, Editable: true},
			{Name: "EmailLabel", Kind: "Text", NodeID: 6, Role: "label", Reusable: true, OrdinaryTetraStruct: true},
			{Name: "EmailTextBox", Kind: "TextBox", NodeID: 7, Reusable: true, OrdinaryTetraStruct: true, Editable: true},
			{Name: "ButtonRow", Kind: "Row", NodeID: 8, Reusable: true, OrdinaryTetraStruct: true},
			{Name: "SaveButton", Kind: "Button", NodeID: 9, Action: "save", Reusable: true, OrdinaryTetraStruct: true},
			{Name: "ResetButton", Kind: "Button", NodeID: 10, Action: "reset", Reusable: true, OrdinaryTetraStruct: true},
			{Name: "StatusText", Kind: "Text", NodeID: 11, Role: "status", Reusable: true, OrdinaryTetraStruct: true},
		},
		ReusableSources: []string{
			"lib/core/widgets.tetra:panel_init",
			"lib/core/widgets.tetra:column_init",
			"lib/core/widgets.tetra:text_init",
			"lib/core/widgets.tetra:textbox_init",
			"lib/core/widgets.tetra:row_init",
			"lib/core/widgets.tetra:button_init",
			"lib/core/widgets.tetra:add_accessible_textbox",
			"lib/core/widgets.tetra:add_accessible_button",
			"lib/core/widgets.tetra:add_accessible_status",
		},
	}
}
func accessibilityTreeReport(beforeFrame rgbaFrame, nameFrame rgbaFrame, saveFrame rgbaFrame, resetFrame rgbaFrame, afterFrame rgbaFrame) *surface.AccessibilityTreeReport {
	return &surface.AccessibilityTreeReport{
		Schema:                   "tetra.surface.accessibility-tree.v1",
		AccessibilityLevel:       "metadata-tree-v1",
		Source:                   "examples/surface_accessibility_settings.tetra",
		Module:                   "lib.core.accessibility",
		WidgetModule:             "lib.core.widgets",
		Experimental:             true,
		ProductionClaim:          false,
		PlatformHostIntegration:  false,
		DOMARIAIntegration:       false,
		ScreenReaderEvidence:     false,
		DerivedFromComponentTree: true,
		UsesComponentTreeAPI:     true,
		UsesWidgetToolkit:        true,
		ManualBookkeeping:        false,
		NoDOMUI:                  true,
		NoUserJS:                 true,
		NoPlatformWidgets:        true,
		NoLegacySidecars:         true,
		ComponentTreeSchema:      "tetra.surface.component-tree.v1",
		ComponentTreeAPISchema:   "tetra.surface.component-tree-api.v1",
		ToolkitSchema:            "tetra.surface.toolkit.v1",
		NodeCount:                12,
		FocusableCount:           4,
		LabelCount:               2,
		TextBoxCount:             2,
		ButtonCount:              2,
		StatusCount:              1,
		RolesPresent:             []string{"root", "panel", "column", "text", "label", "textbox", "row", "button", "status"},
		Nodes:                    accessibilityNodes(),
		Relationships: []surface.AccessibilityRelationshipReport{
			{Kind: "label_for", From: "NameLabel", To: "NameTextBox"},
			{Kind: "labelled_by", From: "NameTextBox", To: "NameLabel"},
			{Kind: "label_for", From: "EmailLabel", To: "EmailTextBox"},
			{Kind: "labelled_by", From: "EmailTextBox", To: "EmailLabel"},
		},
		FocusOrder:   []string{"NameTextBox", "EmailTextBox", "SaveButton", "ResetButton"},
		ReadingOrder: []string{"TitleText", "NameLabel", "NameTextBox", "EmailLabel", "EmailTextBox", "SaveButton", "ResetButton", "StatusText"},
		Actions: []surface.AccessibilityActionReport{
			{Target: "NameTextBox", Action: "edit", Semantic: "text-input"},
			{Target: "EmailTextBox", Action: "edit", Semantic: "text-input"},
			{Target: "SaveButton", Action: "press", Semantic: "save"},
			{Target: "ResetButton", Action: "press", Semantic: "reset"},
		},
		Snapshots: accessibilitySnapshots(beforeFrame, nameFrame, saveFrame, resetFrame, afterFrame),
		NegativeGuards: surface.AccessibilityNegativeGuardsReport{
			NoBorrowedViewStorage:       true,
			ComponentIDAlignmentChecked: true,
			BoundsAlignmentChecked:      true,
			FocusOrderAlignmentChecked:  true,
			ReadingOrderChecked:         true,
			LabelRelationshipsChecked:   true,
			StateUpdatesChecked:         true,
			ArtifactScanChecked:         true,
		},
	}
}
func accessibilityNodes() []surface.AccessibilityNodeReport {
	return []surface.AccessibilityNodeReport{
		{ID: 0, ComponentID: 0, ParentID: -1, Name: "AccessibilitySettingsApp", Role: "root", Bounds: surface.RectReport{X: 0, Y: 0, W: 480, H: 320}, Visible: true, Enabled: true, FocusIndex: -1, ReadingIndex: 0},
		{ID: 1, ComponentID: 1, ParentID: 0, Name: "Panel", Role: "panel", Bounds: surface.RectReport{X: 0, Y: 0, W: 480, H: 320}, Visible: true, Enabled: true, FocusIndex: -1, ReadingIndex: 1},
		{ID: 2, ComponentID: 2, ParentID: 1, Name: "Column", Role: "column", Bounds: surface.RectReport{X: 12, Y: 12, W: 456, H: 296}, Visible: true, Enabled: true, FocusIndex: -1, ReadingIndex: 2},
		{ID: 3, ComponentID: 3, ParentID: 2, Name: "TitleText", Role: "text", Bounds: surface.RectReport{X: 20, Y: 20, W: 440, H: 24}, Visible: true, Enabled: true, ValueKind: "title", FocusIndex: -1, ReadingIndex: 3},
		{ID: 4, ComponentID: 4, ParentID: 2, Name: "NameLabel", Role: "label", Bounds: surface.RectReport{X: 20, Y: 52, W: 440, H: 24}, Visible: true, Enabled: true, LabelFor: "NameTextBox", ValueKind: "name", FocusIndex: -1, ReadingIndex: 4},
		{ID: 5, ComponentID: 5, ParentID: 2, Name: "NameTextBox", Role: "textbox", Bounds: surface.RectReport{X: 20, Y: 84, W: 440, H: 44}, Visible: true, Enabled: true, Focusable: true, Focused: true, Editable: true, LabelledBy: "NameLabel", ValueKind: "empty", Actions: []string{"focus", "edit"}, FocusIndex: 0, ReadingIndex: 5},
		{ID: 6, ComponentID: 6, ParentID: 2, Name: "EmailLabel", Role: "label", Bounds: surface.RectReport{X: 20, Y: 136, W: 440, H: 24}, Visible: true, Enabled: true, LabelFor: "EmailTextBox", ValueKind: "email", FocusIndex: -1, ReadingIndex: 6},
		{ID: 7, ComponentID: 7, ParentID: 2, Name: "EmailTextBox", Role: "textbox", Bounds: surface.RectReport{X: 20, Y: 168, W: 440, H: 44}, Visible: true, Enabled: true, Focusable: true, Editable: true, LabelledBy: "EmailLabel", ValueKind: "empty", Actions: []string{"focus", "edit"}, FocusIndex: 1, ReadingIndex: 7},
		{ID: 8, ComponentID: 8, ParentID: 2, Name: "ButtonRow", Role: "row", Bounds: surface.RectReport{X: 20, Y: 224, W: 440, H: 44}, Visible: true, Enabled: true, FocusIndex: -1, ReadingIndex: 8},
		{ID: 9, ComponentID: 9, ParentID: 8, Name: "SaveButton", Role: "button", Bounds: surface.RectReport{X: 20, Y: 224, W: 132, H: 44}, Visible: true, Enabled: true, Focusable: true, ValueKind: "save", Actions: []string{"focus", "press", "save"}, FocusIndex: 2, ReadingIndex: 9},
		{ID: 10, ComponentID: 10, ParentID: 8, Name: "ResetButton", Role: "button", Bounds: surface.RectReport{X: 164, Y: 224, W: 132, H: 44}, Visible: true, Enabled: true, Focusable: true, ValueKind: "reset", Actions: []string{"focus", "press", "reset"}, FocusIndex: 3, ReadingIndex: 10},
		{ID: 11, ComponentID: 11, ParentID: 2, Name: "StatusText", Role: "status", Bounds: surface.RectReport{X: 20, Y: 280, W: 440, H: 24}, Visible: true, Enabled: true, ValueKind: "reset", FocusIndex: -1, ReadingIndex: 11},
	}
}
func accessibilitySnapshots(beforeFrame rgbaFrame, nameFrame rgbaFrame, saveFrame rgbaFrame, resetFrame rgbaFrame, afterFrame rgbaFrame) []surface.AccessibilitySnapshotReport {
	return []surface.AccessibilitySnapshotReport{
		{Name: "initial", Generation: 1, Focused: "", FocusedComponentID: -1, FocusedAccessibilityNodeID: -1, NameValueLen: 0, EmailValueLen: 0, StatusValue: "idle", BoundsChecksum: checksumText("bounds-initial"), MetadataChecksum: checksumText("metadata-initial"), FrameChecksum: checksumRGBA(beforeFrame.Pixels)},
		{Name: "after_name_focus", Generation: 2, Focused: "NameTextBox", FocusedComponentID: 5, FocusedAccessibilityNodeID: 5, NameValueLen: 0, EmailValueLen: 0, StatusValue: "idle", BoundsChecksum: checksumText("bounds-name-focus"), MetadataChecksum: checksumText("metadata-name-focus"), FrameChecksum: checksumRGBA(nameFrame.Pixels)},
		{Name: "after_name_text", Generation: 3, Focused: "NameTextBox", FocusedComponentID: 5, FocusedAccessibilityNodeID: 5, NameValueLen: 3, EmailValueLen: 0, StatusValue: "idle", BoundsChecksum: checksumText("bounds-name-text"), MetadataChecksum: checksumText("metadata-name-text"), FrameChecksum: checksumRGBA(nameFrame.Pixels)},
		{Name: "after_email_focus", Generation: 4, Focused: "EmailTextBox", FocusedComponentID: 7, FocusedAccessibilityNodeID: 7, NameValueLen: 3, EmailValueLen: 0, StatusValue: "idle", BoundsChecksum: checksumText("bounds-email-focus"), MetadataChecksum: checksumText("metadata-email-focus"), FrameChecksum: checksumText("frame-email-focus")},
		{Name: "after_email_text", Generation: 5, Focused: "EmailTextBox", FocusedComponentID: 7, FocusedAccessibilityNodeID: 7, NameValueLen: 3, EmailValueLen: 5, StatusValue: "idle", BoundsChecksum: checksumText("bounds-email-text"), MetadataChecksum: checksumText("metadata-email-text"), FrameChecksum: checksumText("frame-email-text")},
		{Name: "after_save", Generation: 6, Focused: "SaveButton", FocusedComponentID: 9, FocusedAccessibilityNodeID: 9, NameValueLen: 3, EmailValueLen: 5, StatusValue: "saved", BoundsChecksum: checksumText("bounds-save"), MetadataChecksum: checksumText("metadata-save"), FrameChecksum: checksumRGBA(saveFrame.Pixels)},
		{Name: "after_reset", Generation: 7, Focused: "ResetButton", FocusedComponentID: 10, FocusedAccessibilityNodeID: 10, NameValueLen: 0, EmailValueLen: 0, StatusValue: "reset", BoundsChecksum: checksumText("bounds-reset"), MetadataChecksum: checksumText("metadata-reset"), FrameChecksum: checksumRGBA(resetFrame.Pixels)},
		{Name: "after_resize", Generation: 8, Focused: "NameTextBox", FocusedComponentID: 5, FocusedAccessibilityNodeID: 5, NameValueLen: 0, EmailValueLen: 0, StatusValue: "reset", BoundsChecksum: checksumText("bounds-resize"), MetadataChecksum: checksumText("metadata-resize"), FrameChecksum: checksumRGBA(afterFrame.Pixels)},
	}
}
