package main

import (
	"tetra_language/tools/validators/surface"
)

func runTextFocusInputScenario(mode string) headlessScenario {
	beforeFrame := renderTextFocusInputFrameRGBA(0, 0, 0, 320, 200)
	afterFrame := renderTextFocusInputFrameRGBA(1, 1, 1, 400, 240)
	scenario := headlessScenario{
		Components: []surface.ComponentReport{
			{
				ID:        "TextInputApp",
				Type:      "examples.surface_textbox_app.TextInputApp",
				Bounds:    surface.RectReport{X: 0, Y: 0, W: 400, H: 240},
				Abilities: []string{"measure", "layout", "draw", "event", "focus", "text", "accessibility"},
				State:     map[string]string{"focused_component": "SubmitButton", "width": "400", "height": "240", "resize_count": "1", "accessibility_role": "none"},
			},
			{
				ID:        "TextBox",
				Type:      "examples.surface_textbox_app.TextBox",
				Parent:    "TextInputApp",
				Bounds:    surface.RectReport{X: 32, Y: 64, W: 224, H: 44},
				Abilities: []string{"measure", "layout", "draw", "event", "focus", "text", "accessibility"},
				State:     map[string]string{"focused": "false", "buffer": "Z", "text_len": "1", "caret": "1", "backspace_count": "1", "delete_count": "1", "accessibility_role": "label"},
			},
			{
				ID:        "SubmitButton",
				Type:      "examples.surface_textbox_app.ActionButton",
				Parent:    "TextInputApp",
				Bounds:    surface.RectReport{X: 32, Y: 128, W: 128, H: 44},
				Abilities: []string{"measure", "layout", "draw", "event", "focus", "text", "accessibility"},
				State:     map[string]string{"focused": "true", "press_count": "1", "key_count": "1", "accessibility_role": "button"},
			},
		},
		Events: []surface.EventReport{
			{
				Order:           1,
				Kind:            "mouse_up",
				TargetComponent: "TextBox",
				DispatchPath:    []string{"TextInputApp", "TextBox"},
				Handled:         true,
				Pass:            true,
				X:               48,
				Y:               96,
				Width:           320,
				Height:          200,
				BufferSlots:     []int{5, 48, 96, 1, 0, 320, 200, 0, 0},
				BeforeState:     map[string]string{"TextInputApp.focused_component": "none", "TextBox.focused": "false"},
				AfterState:      map[string]string{"TextInputApp.focused_component": "TextBox", "TextBox.focused": "true"},
			},
			{
				Order:           2,
				Kind:            "text_input",
				TargetComponent: "TextBox",
				DispatchPath:    []string{"TextInputApp", "TextBox"},
				Handled:         true,
				Pass:            true,
				Width:           320,
				Height:          200,
				TimestampMS:     1,
				TextLen:         2,
				TextBytesHex:    "4f4b",
				BufferSlots:     []int{8, 0, 0, 0, 0, 320, 200, 1, 2},
				BeforeState:     map[string]string{"TextBox.buffer": "", "TextBox.caret": "0", "TextBox.text_len": "0"},
				AfterState:      map[string]string{"TextBox.buffer": "OK", "TextBox.caret": "2", "TextBox.text_len": "2"},
			},
			{
				Order:           3,
				Kind:            "key_down",
				TargetComponent: "TextBox",
				DispatchPath:    []string{"TextInputApp", "TextBox"},
				Handled:         true,
				Pass:            true,
				Key:             37,
				Width:           320,
				Height:          200,
				TimestampMS:     2,
				BufferSlots:     []int{6, 0, 0, 0, 37, 320, 200, 2, 0},
				BeforeState:     map[string]string{"TextBox.caret": "2", "TextBox.buffer": "OK"},
				AfterState:      map[string]string{"TextBox.caret": "1", "TextBox.buffer": "OK"},
			},
			{
				Order:           4,
				Kind:            "key_down",
				TargetComponent: "TextBox",
				DispatchPath:    []string{"TextInputApp", "TextBox"},
				Handled:         true,
				Pass:            true,
				Key:             8,
				Width:           320,
				Height:          200,
				TimestampMS:     3,
				BufferSlots:     []int{6, 0, 0, 0, 8, 320, 200, 3, 0},
				BeforeState:     map[string]string{"TextBox.buffer": "OK", "TextBox.caret": "1"},
				AfterState:      map[string]string{"TextBox.buffer": "K", "TextBox.caret": "0"},
			},
			{
				Order:           5,
				Kind:            "key_down",
				TargetComponent: "TextBox",
				DispatchPath:    []string{"TextInputApp", "TextBox"},
				Handled:         true,
				Pass:            true,
				Key:             46,
				Width:           320,
				Height:          200,
				TimestampMS:     4,
				BufferSlots:     []int{6, 0, 0, 0, 46, 320, 200, 4, 0},
				BeforeState:     map[string]string{"TextBox.buffer": "K", "TextBox.caret": "0"},
				AfterState:      map[string]string{"TextBox.buffer": "", "TextBox.caret": "0"},
			},
			{
				Order:           6,
				Kind:            "text_input",
				TargetComponent: "TextBox",
				DispatchPath:    []string{"TextInputApp", "TextBox"},
				Handled:         true,
				Pass:            true,
				Width:           320,
				Height:          200,
				TimestampMS:     5,
				TextLen:         1,
				TextBytesHex:    "5a",
				BufferSlots:     []int{8, 0, 0, 0, 0, 320, 200, 5, 1},
				BeforeState:     map[string]string{"TextBox.buffer": "", "TextBox.caret": "0", "TextBox.text_len": "0"},
				AfterState:      map[string]string{"TextBox.buffer": "Z", "TextBox.caret": "1", "TextBox.text_len": "1"},
			},
			{
				Order:           7,
				Kind:            "key_down",
				TargetComponent: "TextInputApp",
				DispatchPath:    []string{"TextInputApp"},
				Handled:         true,
				Pass:            true,
				Key:             9,
				Width:           320,
				Height:          200,
				TimestampMS:     6,
				BufferSlots:     []int{6, 0, 0, 0, 9, 320, 200, 6, 0},
				BeforeState:     map[string]string{"TextInputApp.focused_component": "TextBox", "TextBox.focused": "true", "SubmitButton.focused": "false"},
				AfterState:      map[string]string{"TextInputApp.focused_component": "SubmitButton", "TextBox.focused": "false", "SubmitButton.focused": "true"},
			},
			{
				Order:           8,
				Kind:            "key_down",
				TargetComponent: "SubmitButton",
				DispatchPath:    []string{"TextInputApp", "SubmitButton"},
				Handled:         true,
				Pass:            true,
				Key:             32,
				Width:           320,
				Height:          200,
				TimestampMS:     7,
				BufferSlots:     []int{6, 0, 0, 0, 32, 320, 200, 7, 0},
				BeforeState:     map[string]string{"SubmitButton.press_count": "0", "TextBox.buffer": "Z"},
				AfterState:      map[string]string{"SubmitButton.press_count": "1", "TextBox.buffer": "Z"},
			},
			{
				Order:           9,
				Kind:            "resize",
				TargetComponent: "TextInputApp",
				DispatchPath:    []string{"TextInputApp"},
				Handled:         true,
				Pass:            true,
				Width:           400,
				Height:          240,
				TimestampMS:     8,
				BufferSlots:     []int{2, 0, 0, 0, 0, 400, 240, 8, 0},
				BeforeState:     map[string]string{"TextInputApp.width": "320", "TextInputApp.focused_component": "SubmitButton"},
				AfterState:      map[string]string{"TextInputApp.width": "400", "TextInputApp.focused_component": "SubmitButton"},
			},
		},
		StateTransitions: []surface.StateTransitionReport{
			{Order: 1, Component: "TextInputApp", Field: "focused_component", Before: "none", After: "TextBox", Cause: "mouse_up"},
			{Order: 2, Component: "TextBox", Field: "buffer", Before: "", After: "OK", Cause: "text_input"},
			{Order: 3, Component: "TextBox", Field: "caret", Before: "2", After: "1", Cause: "key_down"},
			{Order: 4, Component: "TextBox", Field: "buffer", Before: "OK", After: "K", Cause: "backspace"},
			{Order: 5, Component: "TextBox", Field: "buffer", Before: "K", After: "", Cause: "delete"},
			{Order: 6, Component: "TextBox", Field: "buffer", Before: "", After: "Z", Cause: "text_input"},
			{Order: 7, Component: "TextInputApp", Field: "focused_component", Before: "TextBox", After: "SubmitButton", Cause: "tab"},
			{Order: 8, Component: "SubmitButton", Field: "press_count", Before: "0", After: "1", Cause: "key_down"},
			{Order: 9, Component: "TextInputApp", Field: "width", Before: "320", After: "400", Cause: "resize"},
		},
		Cases: []surface.CaseReport{
			{Name: "pure Tetra component app", Kind: "positive", Ran: true, Pass: true},
			{Name: "text focus input click focuses TextBox", Kind: "positive", Ran: true, Pass: true},
			{Name: "text focus input Tab changes focus", Kind: "positive", Ran: true, Pass: true},
			{Name: "text focus input keyboard routes only focused component", Kind: "positive", Ran: true, Pass: true},
			{Name: "text focus input text insertion", Kind: "positive", Ran: true, Pass: true},
			{Name: "text focus input caret movement", Kind: "positive", Ran: true, Pass: true},
			{Name: "text focus input backspace delete", Kind: "positive", Ran: true, Pass: true},
			{Name: "text focus input resize preserves focus", Kind: "positive", Ran: true, Pass: true},
			{Name: "text focus input rendered frame update", Kind: "positive", Ran: true, Pass: true},
			{Name: "host-provided pointer event dispatch", Kind: "positive", Ran: true, Pass: true},
			{Name: "host event buffer poll_event", Kind: "positive", Ran: true, Pass: true},
			{Name: "pre/post event frame sequence", Kind: "positive", Ran: true, Pass: true},
			{Name: "component hierarchy dispatch", Kind: "positive", Ran: true, Pass: true},
			{Name: "component text input scalar dispatch", Kind: "positive", Ran: true, Pass: true},
			{Name: "host text payload buffer", Kind: "positive", Ran: true, Pass: true},
			{Name: "component focus dispatch", Kind: "positive", Ran: true, Pass: true},
			{Name: "component accessibility metadata", Kind: "positive", Ran: true, Pass: true},
			{Name: "no legacy UI sidecar artifacts", Kind: "positive", Ran: true, Pass: true},
			{Name: "state transition", Kind: "positive", Ran: true, Pass: true},
			{Name: "reject legacy UI evidence", Kind: "negative", Ran: true, Pass: true, ExpectedError: "legacy UI evidence rejected"},
		},
	}
	if mode == "headless-text-focus-input" || mode == "linux-x64-real-window-text-focus-input" {
		scenario.Frames = []surface.FrameReport{
			{Order: 1, Width: beforeFrame.Width, Height: beforeFrame.Height, Stride: beforeFrame.Stride, Checksum: checksumRGBA(beforeFrame.Pixels), Presented: true},
			{Order: 2, Width: afterFrame.Width, Height: afterFrame.Height, Stride: afterFrame.Stride, Checksum: checksumRGBA(afterFrame.Pixels), Presented: true},
		}
	}
	switch mode {
	case "headless-text-focus-input":
		scenario.Cases = append(scenario.Cases,
			surface.CaseReport{Name: "headless event dispatch", Kind: "positive", Ran: true, Pass: true},
			surface.CaseReport{Name: "headless framebuffer checksum", Kind: "positive", Ran: true, Pass: true},
			surface.CaseReport{Name: "headless actual runner trace", Kind: "positive", Ran: true, Pass: true},
		)
	case "linux-x64-real-window-text-focus-input":
		scenario.Cases = append(scenario.Cases,
			surface.CaseReport{Name: "linux-x64 Surface Host ABI open/present/close", Kind: "positive", Ran: true, Pass: true},
			surface.CaseReport{Name: "linux-x64 real-window surface", Kind: "positive", Ran: true, Pass: true},
			surface.CaseReport{Name: "linux-x64 native input event pump", Kind: "positive", Ran: true, Pass: true},
			surface.CaseReport{Name: "linux-x64 real-window resize event", Kind: "positive", Ran: true, Pass: true},
			surface.CaseReport{Name: "linux-x64 real-window close event", Kind: "positive", Ran: true, Pass: true},
		)
	case "wasm32-web-browser-canvas-text-focus-input":
		scenario.Cases = append(scenario.Cases,
			surface.CaseReport{Name: "wasm32-web browser canvas surface", Kind: "positive", Ran: true, Pass: true},
			surface.CaseReport{Name: "wasm32-web browser canvas RGBA readback", Kind: "positive", Ran: true, Pass: true},
			surface.CaseReport{Name: "wasm32-web browser canvas pointer input", Kind: "positive", Ran: true, Pass: true},
			surface.CaseReport{Name: "wasm32-web browser canvas keyboard input", Kind: "positive", Ran: true, Pass: true},
			surface.CaseReport{Name: "wasm32-web browser canvas resize input", Kind: "positive", Ran: true, Pass: true},
			surface.CaseReport{Name: "wasm32-web browser canvas text input", Kind: "positive", Ran: true, Pass: true},
			surface.CaseReport{Name: "wasm32-web Surface Host ABI imports", Kind: "positive", Ran: true, Pass: true},
			surface.CaseReport{Name: "compiler-owned wasm Surface loader", Kind: "positive", Ran: true, Pass: true},
			surface.CaseReport{Name: "compiler-owned browser canvas Surface host", Kind: "positive", Ran: true, Pass: true},
		)
	}
	return scenario
}
func runComponentTreeScenario(mode string) headlessScenario {
	beforeFrame := renderComponentTreeFrameRGBA(0, 0, -1, 0, 0, 320, 200)
	afterFrame := renderComponentTreeFrameRGBA(0, 0, 6, 1, 1, 400, 240)
	scenario := headlessScenario{
		Components: []surface.ComponentReport{
			{
				ID:        "TreeApp",
				Type:      "examples.surface_tree_app.TreeApp",
				Bounds:    surface.RectReport{X: 0, Y: 0, W: 400, H: 240},
				Abilities: []string{"measure", "layout", "draw", "event", "focus", "text", "accessibility"},
				State:     map[string]string{"focused_id": "6", "submitted_count": "1", "reset_count": "1", "width": "400", "height": "240", "accessibility_role": "none"},
			},
			{
				ID:        "Column",
				Type:      "examples.surface_tree_app.Column",
				Parent:    "TreeApp",
				Bounds:    surface.RectReport{X: 0, Y: 0, W: 400, H: 240},
				Abilities: []string{"measure", "layout", "draw", "event", "focus", "text", "accessibility"},
				State:     map[string]string{"child_count": "3", "accessibility_role": "none"},
			},
			{
				ID:        "NameLabel",
				Type:      "examples.surface_tree_app.TextLabel",
				Parent:    "Column",
				Bounds:    surface.RectReport{X: 16, Y: 16, W: 288, H: 24},
				Abilities: []string{"measure", "layout", "draw", "event", "focus", "text", "accessibility"},
				State:     map[string]string{"text": "Name", "accessibility_role": "label"},
			},
			{
				ID:        "TextBox",
				Type:      "examples.surface_tree_app.TextBox",
				Parent:    "Column",
				Bounds:    surface.RectReport{X: 16, Y: 48, W: 368, H: 44},
				Abilities: []string{"measure", "layout", "draw", "event", "focus", "text", "accessibility"},
				State:     map[string]string{"focused": "false", "buffer": "", "text_len": "0", "caret": "0", "accessibility_role": "label"},
			},
			{
				ID:        "ButtonRow",
				Type:      "examples.surface_tree_app.Row",
				Parent:    "Column",
				Bounds:    surface.RectReport{X: 16, Y: 104, W: 368, H: 44},
				Abilities: []string{"measure", "layout", "draw", "event", "focus", "text", "accessibility"},
				State:     map[string]string{"child_count": "2", "accessibility_role": "none"},
			},
			{
				ID:        "SubmitButton",
				Type:      "examples.surface_tree_app.Button",
				Parent:    "ButtonRow",
				Bounds:    surface.RectReport{X: 16, Y: 104, W: 132, H: 44},
				Abilities: []string{"measure", "layout", "draw", "event", "focus", "text", "accessibility"},
				State:     map[string]string{"focused": "false", "press_count": "1", "accessibility_role": "button"},
			},
			{
				ID:        "ResetButton",
				Type:      "examples.surface_tree_app.Button",
				Parent:    "ButtonRow",
				Bounds:    surface.RectReport{X: 160, Y: 104, W: 132, H: 44},
				Abilities: []string{"measure", "layout", "draw", "event", "focus", "text", "accessibility"},
				State:     map[string]string{"focused": "true", "press_count": "1", "accessibility_role": "button"},
			},
		},
		ComponentTree: &surface.ComponentTreeReport{
			Schema:       "tetra.surface.component-tree.v1",
			DynamicLevel: "semi-dynamic-child-list",
			RootID:       0,
			NodeCount:    7,
			FocusedID:    6,
			Nodes: []surface.ComponentTreeNodeReport{
				{ID: 0, Name: "TreeApp", Kind: "root", ParentID: -1, ChildIndex: 0, FirstChild: 1, ChildCount: 1, Focusable: false, Bounds: surface.RectReport{X: 0, Y: 0, W: 400, H: 240}},
				{ID: 1, Name: "Column", Kind: "column", ParentID: 0, ChildIndex: 0, FirstChild: 2, ChildCount: 3, Focusable: false, Bounds: surface.RectReport{X: 0, Y: 0, W: 400, H: 240}},
				{ID: 2, Name: "NameLabel", Kind: "text", ParentID: 1, ChildIndex: 0, FirstChild: -1, ChildCount: 0, Focusable: false, Bounds: surface.RectReport{X: 16, Y: 16, W: 288, H: 24}},
				{ID: 3, Name: "TextBox", Kind: "textbox", ParentID: 1, ChildIndex: 1, FirstChild: -1, ChildCount: 0, Focusable: true, Bounds: surface.RectReport{X: 16, Y: 48, W: 368, H: 44}},
				{ID: 4, Name: "ButtonRow", Kind: "row", ParentID: 1, ChildIndex: 2, FirstChild: 5, ChildCount: 2, Focusable: false, Bounds: surface.RectReport{X: 16, Y: 104, W: 368, H: 44}},
				{ID: 5, Name: "SubmitButton", Kind: "button", ParentID: 4, ChildIndex: 0, FirstChild: -1, ChildCount: 0, Focusable: true, Bounds: surface.RectReport{X: 16, Y: 104, W: 132, H: 44}},
				{ID: 6, Name: "ResetButton", Kind: "button", ParentID: 4, ChildIndex: 1, FirstChild: -1, ChildCount: 0, Focusable: true, Bounds: surface.RectReport{X: 160, Y: 104, W: 132, H: 44}},
			},
			LayoutPasses: []surface.ComponentTreeLayoutPassReport{
				{ComponentID: 3, Pass: "initial", Bounds: surface.RectReport{X: 16, Y: 48, W: 288, H: 44}, Measured: surface.SizeReport{W: 288, H: 44}},
				{ComponentID: 3, Pass: "resize", Bounds: surface.RectReport{X: 16, Y: 48, W: 368, H: 44}, Measured: surface.SizeReport{W: 368, H: 44}},
			},
			DrawOrder:  []int{0, 1, 2, 3, 4, 5, 6},
			FocusOrder: []int{3, 5, 6},
			DispatchPaths: []surface.ComponentTreeDispatchPathReport{
				{Event: "click", TargetID: 3, X: 40, Y: 72, Path: []int{0, 1, 3}},
				{Event: "click", TargetID: 5, X: 32, Y: 120, Path: []int{0, 1, 4, 5}},
				{Event: "click", TargetID: 6, X: 176, Y: 120, Path: []int{0, 1, 4, 6}},
			},
		},
		ComponentTreeAPI: componentTreeAPIReport(),
		Events: []surface.EventReport{
			{
				Order:           1,
				Kind:            "mouse_up",
				TargetComponent: "TextBox",
				DispatchPath:    []string{"TreeApp", "Column", "TextBox"},
				Handled:         true,
				Pass:            true,
				X:               40,
				Y:               72,
				Width:           320,
				Height:          200,
				BufferSlots:     []int{5, 40, 72, 1, 0, 320, 200, 0, 0},
				BeforeState:     map[string]string{"TreeApp.focused_id": "-1", "TextBox.focused": "false"},
				AfterState:      map[string]string{"TreeApp.focused_id": "3", "TextBox.focused": "true"},
			},
			{
				Order:           2,
				Kind:            "text_input",
				TargetComponent: "TextBox",
				DispatchPath:    []string{"TreeApp", "Column", "TextBox"},
				Handled:         true,
				Pass:            true,
				Width:           320,
				Height:          200,
				TimestampMS:     1,
				TextLen:         2,
				TextBytesHex:    "4f4b",
				BufferSlots:     []int{8, 0, 0, 0, 0, 320, 200, 1, 2},
				BeforeState:     map[string]string{"TextBox.buffer": "", "TextBox.caret": "0"},
				AfterState:      map[string]string{"TextBox.buffer": "OK", "TextBox.caret": "2"},
			},
			{
				Order:           3,
				Kind:            "key_down",
				TargetComponent: "TreeApp",
				DispatchPath:    []string{"TreeApp"},
				Handled:         true,
				Pass:            true,
				Key:             9,
				Width:           320,
				Height:          200,
				TimestampMS:     2,
				BufferSlots:     []int{6, 0, 0, 0, 9, 320, 200, 2, 0},
				BeforeState:     map[string]string{"TreeApp.focused_id": "3"},
				AfterState:      map[string]string{"TreeApp.focused_id": "5"},
			},
			{
				Order:           4,
				Kind:            "key_down",
				TargetComponent: "SubmitButton",
				DispatchPath:    []string{"TreeApp", "Column", "ButtonRow", "SubmitButton"},
				Handled:         true,
				Pass:            true,
				Key:             32,
				Width:           320,
				Height:          200,
				TimestampMS:     3,
				BufferSlots:     []int{6, 0, 0, 0, 32, 320, 200, 3, 0},
				BeforeState:     map[string]string{"TreeApp.submitted_count": "0", "TreeApp.focused_id": "5"},
				AfterState:      map[string]string{"TreeApp.submitted_count": "1", "TreeApp.focused_id": "5"},
			},
			{
				Order:           5,
				Kind:            "key_down",
				TargetComponent: "TreeApp",
				DispatchPath:    []string{"TreeApp"},
				Handled:         true,
				Pass:            true,
				Key:             9,
				Width:           320,
				Height:          200,
				TimestampMS:     4,
				BufferSlots:     []int{6, 0, 0, 0, 9, 320, 200, 4, 0},
				BeforeState:     map[string]string{"TreeApp.focused_id": "5"},
				AfterState:      map[string]string{"TreeApp.focused_id": "6"},
			},
			{
				Order:           6,
				Kind:            "text_input",
				TargetComponent: "ResetButton",
				DispatchPath:    []string{"TreeApp", "Column", "ButtonRow", "ResetButton"},
				Handled:         false,
				Pass:            true,
				Width:           320,
				Height:          200,
				TimestampMS:     5,
				TextLen:         1,
				TextBytesHex:    "5a",
				BufferSlots:     []int{8, 0, 0, 0, 0, 320, 200, 5, 1},
				BeforeState:     map[string]string{"TreeApp.focused_id": "6", "TextBox.buffer": "OK"},
				AfterState:      map[string]string{"TreeApp.focused_id": "6", "TextBox.buffer": "OK"},
			},
			{
				Order:           7,
				Kind:            "key_down",
				TargetComponent: "ResetButton",
				DispatchPath:    []string{"TreeApp", "Column", "ButtonRow", "ResetButton"},
				Handled:         true,
				Pass:            true,
				Key:             13,
				Width:           320,
				Height:          200,
				TimestampMS:     6,
				BufferSlots:     []int{6, 0, 0, 0, 13, 320, 200, 6, 0},
				BeforeState:     map[string]string{"TreeApp.reset_count": "0", "TextBox.buffer": "OK", "TreeApp.focused_id": "6"},
				AfterState:      map[string]string{"TreeApp.reset_count": "1", "TextBox.buffer": "", "TreeApp.focused_id": "6"},
			},
			{
				Order:           8,
				Kind:            "key_down",
				TargetComponent: "TreeApp",
				DispatchPath:    []string{"TreeApp"},
				Handled:         true,
				Pass:            true,
				Key:             9,
				Width:           320,
				Height:          200,
				TimestampMS:     7,
				BufferSlots:     []int{6, 0, 0, 0, 9, 320, 200, 7, 0},
				BeforeState:     map[string]string{"TreeApp.focused_id": "6"},
				AfterState:      map[string]string{"TreeApp.focused_id": "3"},
			},
			{
				Order:           9,
				Kind:            "key_down",
				TargetComponent: "TreeApp",
				DispatchPath:    []string{"TreeApp"},
				Handled:         true,
				Pass:            true,
				Key:             9,
				Width:           320,
				Height:          200,
				TimestampMS:     8,
				BufferSlots:     []int{6, 0, 0, 0, 9, 320, 200, 8, 0},
				BeforeState:     map[string]string{"TreeApp.focused_id": "3"},
				AfterState:      map[string]string{"TreeApp.focused_id": "5"},
			},
			{
				Order:           10,
				Kind:            "key_down",
				TargetComponent: "TreeApp",
				DispatchPath:    []string{"TreeApp"},
				Handled:         true,
				Pass:            true,
				Key:             9,
				Width:           320,
				Height:          200,
				TimestampMS:     9,
				BufferSlots:     []int{6, 0, 0, 0, 9, 320, 200, 9, 0},
				BeforeState:     map[string]string{"TreeApp.focused_id": "5"},
				AfterState:      map[string]string{"TreeApp.focused_id": "6"},
			},
			{
				Order:           11,
				Kind:            "resize",
				TargetComponent: "TreeApp",
				DispatchPath:    []string{"TreeApp"},
				Handled:         true,
				Pass:            true,
				Width:           400,
				Height:          240,
				TimestampMS:     10,
				BufferSlots:     []int{2, 0, 0, 0, 0, 400, 240, 10, 0},
				BeforeState:     map[string]string{"TreeApp.focused_id": "6", "TextBox.bounds.w": "288"},
				AfterState:      map[string]string{"TreeApp.focused_id": "6", "TextBox.bounds.w": "368"},
			},
		},
		StateTransitions: []surface.StateTransitionReport{
			{Order: 1, Component: "TreeApp", Field: "focused_id", Before: "-1", After: "3", Cause: "mouse_up"},
			{Order: 2, Component: "TextBox", Field: "buffer", Before: "", After: "OK", Cause: "text_input"},
			{Order: 3, Component: "TreeApp", Field: "focused_id", Before: "3", After: "5", Cause: "tab"},
			{Order: 4, Component: "TreeApp", Field: "submitted_count", Before: "0", After: "1", Cause: "key_down"},
			{Order: 5, Component: "TreeApp", Field: "focused_id", Before: "5", After: "6", Cause: "tab"},
			{Order: 6, Component: "TextBox", Field: "buffer", Before: "OK", After: "", Cause: "reset"},
			{Order: 7, Component: "TreeApp", Field: "reset_count", Before: "0", After: "1", Cause: "key_down"},
			{Order: 8, Component: "TreeApp", Field: "focused_id", Before: "6", After: "3", Cause: "tab"},
			{Order: 9, Component: "TreeApp", Field: "focused_id", Before: "3", After: "5", Cause: "tab"},
			{Order: 10, Component: "TreeApp", Field: "focused_id", Before: "5", After: "6", Cause: "tab"},
			{Order: 11, Component: "TreeApp", Field: "TextBox.bounds.w", Before: "288", After: "368", Cause: "resize"},
		},
		Cases: []surface.CaseReport{
			{Name: "pure Tetra component app", Kind: "positive", Ran: true, Pass: true},
			{Name: "host-provided pointer event dispatch", Kind: "positive", Ran: true, Pass: true},
			{Name: "host event buffer poll_event", Kind: "positive", Ran: true, Pass: true},
			{Name: "pre/post event frame sequence", Kind: "positive", Ran: true, Pass: true},
			{Name: "component hierarchy dispatch", Kind: "positive", Ran: true, Pass: true},
			{Name: "component text input scalar dispatch", Kind: "positive", Ran: true, Pass: true},
			{Name: "host text payload buffer", Kind: "positive", Ran: true, Pass: true},
			{Name: "component focus dispatch", Kind: "positive", Ran: true, Pass: true},
			{Name: "component accessibility metadata", Kind: "positive", Ran: true, Pass: true},
			{Name: "no legacy UI sidecar artifacts", Kind: "positive", Ran: true, Pass: true},
			{Name: "state transition", Kind: "positive", Ran: true, Pass: true},
			{Name: "component tree node count", Kind: "positive", Ran: true, Pass: true},
			{Name: "component tree parent child links", Kind: "positive", Ran: true, Pass: true},
			{Name: "component tree layout bounds", Kind: "positive", Ran: true, Pass: true},
			{Name: "component tree draw traversal", Kind: "positive", Ran: true, Pass: true},
			{Name: "component tree pointer dispatch path", Kind: "positive", Ran: true, Pass: true},
			{Name: "component tree focus traversal", Kind: "positive", Ran: true, Pass: true},
			{Name: "component tree text routed to focused TextBox", Kind: "positive", Ran: true, Pass: true},
			{Name: "component tree button action dispatch", Kind: "positive", Ran: true, Pass: true},
			{Name: "component tree resize relayout", Kind: "positive", Ran: true, Pass: true},
			{Name: "component tree rendered frame update", Kind: "positive", Ran: true, Pass: true},
			{Name: "component tree api builder node creation", Kind: "positive", Ran: true, Pass: true},
			{Name: "component tree api parent child invariants", Kind: "positive", Ran: true, Pass: true},
			{Name: "component tree api layout helper dispatch", Kind: "positive", Ran: true, Pass: true},
			{Name: "component tree api hit test helper", Kind: "positive", Ran: true, Pass: true},
			{Name: "component tree api focus helper traversal", Kind: "positive", Ran: true, Pass: true},
			{Name: "component tree api dispatch path helper", Kind: "positive", Ran: true, Pass: true},
			{Name: "component tree api no manual bookkeeping", Kind: "positive", Ran: true, Pass: true},
			{Name: "reject legacy UI evidence", Kind: "negative", Ran: true, Pass: true, ExpectedError: "legacy UI evidence rejected"},
		},
	}
	if mode == "headless-component-tree" || mode == "linux-x64-real-window-component-tree" ||
		mode == "headless-component-tree-api" || mode == "linux-x64-real-window-component-tree-api" {
		scenario.Frames = []surface.FrameReport{
			{Order: 1, Width: beforeFrame.Width, Height: beforeFrame.Height, Stride: beforeFrame.Stride, Checksum: checksumRGBA(beforeFrame.Pixels), Presented: true},
			{Order: 2, Width: afterFrame.Width, Height: afterFrame.Height, Stride: afterFrame.Stride, Checksum: checksumRGBA(afterFrame.Pixels), Presented: true},
		}
	}
	switch mode {
	case "headless-component-tree", "headless-component-tree-api":
		scenario.Cases = append(scenario.Cases,
			surface.CaseReport{Name: "headless event dispatch", Kind: "positive", Ran: true, Pass: true},
			surface.CaseReport{Name: "headless framebuffer checksum", Kind: "positive", Ran: true, Pass: true},
			surface.CaseReport{Name: "headless actual runner trace", Kind: "positive", Ran: true, Pass: true},
		)
	case "linux-x64-real-window-component-tree", "linux-x64-real-window-component-tree-api":
		scenario.Cases = append(scenario.Cases,
			surface.CaseReport{Name: "linux-x64 Surface Host ABI open/present/close", Kind: "positive", Ran: true, Pass: true},
			surface.CaseReport{Name: "linux-x64 real-window surface", Kind: "positive", Ran: true, Pass: true},
			surface.CaseReport{Name: "linux-x64 native input event pump", Kind: "positive", Ran: true, Pass: true},
			surface.CaseReport{Name: "linux-x64 real-window resize event", Kind: "positive", Ran: true, Pass: true},
			surface.CaseReport{Name: "linux-x64 real-window close event", Kind: "positive", Ran: true, Pass: true},
		)
	case "wasm32-web-browser-canvas-component-tree", "wasm32-web-browser-canvas-component-tree-api":
		scenario.Cases = append(scenario.Cases,
			surface.CaseReport{Name: "wasm32-web browser canvas surface", Kind: "positive", Ran: true, Pass: true},
			surface.CaseReport{Name: "wasm32-web browser canvas RGBA readback", Kind: "positive", Ran: true, Pass: true},
			surface.CaseReport{Name: "wasm32-web browser canvas pointer input", Kind: "positive", Ran: true, Pass: true},
			surface.CaseReport{Name: "wasm32-web browser canvas keyboard input", Kind: "positive", Ran: true, Pass: true},
			surface.CaseReport{Name: "wasm32-web browser canvas resize input", Kind: "positive", Ran: true, Pass: true},
			surface.CaseReport{Name: "wasm32-web browser canvas text input", Kind: "positive", Ran: true, Pass: true},
			surface.CaseReport{Name: "wasm32-web Surface Host ABI imports", Kind: "positive", Ran: true, Pass: true},
			surface.CaseReport{Name: "compiler-owned wasm Surface loader", Kind: "positive", Ran: true, Pass: true},
			surface.CaseReport{Name: "compiler-owned browser canvas Surface host", Kind: "positive", Ran: true, Pass: true},
		)
	}
	return scenario
}
func componentTreeAPIReport() *surface.ComponentTreeAPIReport {
	return &surface.ComponentTreeAPIReport{
		Schema:            "tetra.surface.component-tree-api.v1",
		APILevel:          "builder-layout-dispatch-v1",
		Source:            "examples/surface_tree_app.tetra",
		ManualBookkeeping: false,
		Builder: surface.ComponentTreeAPIBuilderReport{
			RootCreatedBy:     "tree_add_root",
			ChildrenCreatedBy: "tree_add_child",
			NodeCount:         7,
			Capacity:          16,
			OverflowChecked:   true,
		},
		Invariants: surface.ComponentTreeAPIInvariantReport{
			TreeValidateRan:         true,
			TreeValidateStatus:      0,
			ParentChildLinksChecked: true,
			ChildIndicesChecked:     true,
			ChildCountChecked:       true,
			FirstChildChecked:       true,
		},
		LayoutHelpers: []surface.ComponentTreeAPILayoutHelperReport{
			{Helper: "tree_layout_column", Target: "Column", Pass: "initial", ChangedBounds: true},
			{Helper: "tree_layout_row", Target: "ButtonRow", Pass: "initial", ChangedBounds: true},
			{Helper: "tree_layout_column", Target: "Column", Pass: "resize", ChangedBounds: true},
		},
		FocusHelpers: []surface.ComponentTreeAPIFocusHelperReport{
			{Helper: "tree_focus_next", Before: "TextBox", After: "SubmitButton"},
			{Helper: "tree_focus_next", Before: "SubmitButton", After: "ResetButton"},
			{Helper: "tree_focus_next", Before: "ResetButton", After: "TextBox"},
		},
		HitTests: []surface.ComponentTreeAPIHitTestReport{
			{Helper: "tree_hit_test", X: 40, Y: 72, Target: "TextBox", Path: []int{0, 1, 3}},
			{Helper: "tree_hit_test", X: 176, Y: 120, Target: "ResetButton", Path: []int{0, 1, 4, 6}},
		},
		DispatchPaths: []surface.ComponentTreeAPIDispatchPathReport{
			{Helper: "tree_build_dispatch_path", Target: "TextBox", Path: []int{0, 1, 3}},
			{Helper: "tree_build_dispatch_path", Target: "SubmitButton", Path: []int{0, 1, 4, 5}},
			{Helper: "tree_build_dispatch_path", Target: "ResetButton", Path: []int{0, 1, 4, 6}},
		},
	}
}
func renderCounterFrameRGBA(count int, focused bool) rgbaFrame {
	frame := newRGBAFrame(320, 200)
	bg := rgbaColor{R: 20, G: 24, B: 26, A: 255}
	fg := rgbaColor{R: 238, G: 241, B: 245, A: 255}
	accent := rgbaColor{R: 32, G: 132, B: 214, A: 255}
	button := rect{X: 32, Y: 80, W: 160, H: 48}

	clearRGBA(frame, bg)
	rectRGBA(frame, rect{X: 32, Y: 28, W: 48, H: 7}, fg)
	rectRGBA(frame, button, accent)
	if count > 0 {
		rectRGBA(frame, rect{X: 88, Y: 28, W: 24, H: 7}, fg)
	}
	if focused {
		rectOutlineRGBA(frame, rect{X: button.X - 4, Y: button.Y - 4, W: button.W + 8, H: button.H + 8}, fg)
	}
	rectOutlineRGBA(frame, button, fg)
	return frame
}
