package main

import (
	"tetra_language/tools/validators/surface"
)

func runHeadlessCounterScenario() headlessScenario {
	beforeFrame := renderCounterFrameRGBA(0, true)
	afterFrame := renderCounterFrameRGBA(1, true)
	return headlessScenario{
		Components: []surface.ComponentReport{
			{
				ID:        "CounterApp",
				Type:      "examples.surface_counter.CounterApp",
				Bounds:    surface.RectReport{X: 0, Y: 0, W: 320, H: 200},
				Abilities: []string{"measure", "layout", "draw", "event", "focus", "text", "accessibility"},
				State:     map[string]string{"count": "1", "text_count": "1", "accessibility_role": "button"},
			},
			{
				ID:        "CounterButton",
				Type:      "examples.surface_counter.CounterButton",
				Parent:    "CounterApp",
				Bounds:    surface.RectReport{X: 32, Y: 80, W: 160, H: 48},
				Abilities: []string{"measure", "layout", "draw", "event", "focus", "text", "accessibility"},
				State:     map[string]string{"pressed": "false", "focused": "true", "text_len_seen": "2", "accessibility_role": "button"},
			},
		},
		Events: []surface.EventReport{
			{
				Order:           1,
				Kind:            "none",
				TargetComponent: "CounterApp",
				DispatchPath:    []string{"CounterApp"},
				Handled:         false,
				Pass:            true,
				X:               0,
				Y:               0,
				BeforeState:     map[string]string{"CounterApp.count": "0"},
				AfterState:      map[string]string{"CounterApp.count": "0"},
			},
			{
				Order:           2,
				Kind:            "mouse_up",
				TargetComponent: "CounterButton",
				DispatchPath:    []string{"CounterApp", "CounterButton"},
				Handled:         true,
				Pass:            true,
				X:               48,
				Y:               96,
				Key:             0,
				Width:           320,
				Height:          200,
				TimestampMS:     0,
				BufferSlots:     []int{5, 48, 96, 1, 0, 320, 200, 0, 0},
				BeforeState:     map[string]string{"CounterApp.count": "0", "CounterButton.pressed": "false"},
				AfterState:      map[string]string{"CounterApp.count": "1", "CounterButton.pressed": "false"},
			},
			{
				Order:           3,
				Kind:            "text_input",
				TargetComponent: "CounterButton",
				DispatchPath:    []string{"CounterApp", "CounterButton"},
				Handled:         true,
				Pass:            true,
				X:               0,
				Y:               0,
				Key:             0,
				Width:           320,
				Height:          200,
				TimestampMS:     1,
				TextLen:         2,
				TextBytesHex:    "4f4b",
				BufferSlots:     []int{8, 0, 0, 0, 0, 320, 200, 1, 2},
				BeforeState:     map[string]string{"CounterApp.text_count": "0", "CounterButton.text_len_seen": "0"},
				AfterState:      map[string]string{"CounterApp.text_count": "1", "CounterButton.text_len_seen": "2"},
			},
		},
		Frames: []surface.FrameReport{
			{Order: 1, Width: beforeFrame.Width, Height: beforeFrame.Height, Stride: beforeFrame.Stride, Checksum: checksumRGBA(beforeFrame.Pixels), Presented: true},
			{Order: 2, Width: afterFrame.Width, Height: afterFrame.Height, Stride: afterFrame.Stride, Checksum: checksumRGBA(afterFrame.Pixels), Presented: true},
		},
		StateTransitions: []surface.StateTransitionReport{
			{Order: 1, Component: "CounterApp", Field: "count", Before: "0", After: "1", Cause: "mouse_up"},
			{Order: 2, Component: "CounterApp", Field: "text_count", Before: "0", After: "1", Cause: "text_input"},
		},
		Cases: []surface.CaseReport{
			{Name: "pure Tetra component app", Kind: "positive", Ran: true, Pass: true},
			{Name: "headless event dispatch", Kind: "positive", Ran: true, Pass: true},
			{Name: "headless framebuffer checksum", Kind: "positive", Ran: true, Pass: true},
			{Name: "headless actual runner trace", Kind: "positive", Ran: true, Pass: true},
			{Name: "host-provided pointer event dispatch", Kind: "positive", Ran: true, Pass: true},
			{Name: "host event buffer poll_event", Kind: "positive", Ran: true, Pass: true},
			{Name: "pre/post event frame sequence", Kind: "positive", Ran: true, Pass: true},
			{Name: "component hierarchy dispatch", Kind: "positive", Ran: true, Pass: true},
			{Name: "component text input scalar dispatch", Kind: "positive", Ran: true, Pass: true},
			{Name: "host text payload buffer", Kind: "positive", Ran: true, Pass: true},
			{Name: "component focus dispatch", Kind: "positive", Ran: true, Pass: true},
			{Name: "component accessibility metadata", Kind: "positive", Ran: true, Pass: true},
			{Name: "no legacy UI sidecar artifacts", Kind: "positive", Ran: true, Pass: true},
			{Name: "state transition", Kind: "positive", Ran: true, Pass: true},
			{Name: "reject legacy UI evidence", Kind: "negative", Ran: true, Pass: true, ExpectedError: "legacy UI evidence rejected"},
		},
	}
}
func runAppModelScenario() headlessScenario {
	beforeFrame := renderCounterFrameRGBA(0, true)
	afterFrame := renderCounterFrameRGBA(1, true)
	return headlessScenario{
		Components: []surface.ComponentReport{
			{
				ID:        "AppModelApp",
				Type:      "examples.surface_app_model.AppModelApp",
				Bounds:    surface.RectReport{X: 0, Y: 0, W: 480, H: 320},
				Abilities: []string{"measure", "layout", "draw", "event", "focus", "text", "accessibility"},
				State:     map[string]string{"route": "settings", "focused": "NameField", "save_count": "1", "pending_task": "0", "history_depth": "1", "redo_depth": "0", "accessibility_role": "none"},
			},
			{
				ID:        "NameField",
				Type:      "examples.surface_app_model.NameField",
				Parent:    "AppModelApp",
				Bounds:    surface.RectReport{X: 32, Y: 80, W: 240, H: 44},
				Abilities: []string{"measure", "layout", "draw", "event", "focus", "text", "accessibility"},
				State:     map[string]string{"focused": "true", "buffer": "Ada", "caret": "3", "accessibility_role": "textbox"},
			},
			{
				ID:        "SaveButton",
				Type:      "examples.surface_app_model.SaveButton",
				Parent:    "AppModelApp",
				Bounds:    surface.RectReport{X: 32, Y: 144, W: 132, H: 44},
				Abilities: []string{"measure", "layout", "draw", "event", "focus", "text", "accessibility"},
				State:     map[string]string{"focused": "false", "press_count": "1", "action": "save", "accessibility_role": "button"},
			},
		},
		Events: []surface.EventReport{
			{
				Order:           1,
				Kind:            "mouse_up",
				TargetComponent: "NameField",
				DispatchPath:    []string{"AppModelApp", "NameField"},
				Handled:         true,
				Pass:            true,
				X:               48,
				Y:               96,
				Width:           480,
				Height:          320,
				BufferSlots:     []int{5, 48, 96, 1, 0, 480, 320, 0, 0},
				BeforeState:     map[string]string{"AppModelApp.focused": ""},
				AfterState:      map[string]string{"AppModelApp.focused": "NameField"},
			},
			{
				Order:           2,
				Kind:            "text_input",
				TargetComponent: "NameField",
				DispatchPath:    []string{"AppModelApp", "NameField"},
				Handled:         true,
				Pass:            true,
				Width:           480,
				Height:          320,
				TimestampMS:     1,
				TextLen:         3,
				TextBytesHex:    "416461",
				BufferSlots:     []int{8, 0, 0, 0, 0, 480, 320, 1, 3},
				BeforeState:     map[string]string{"NameField.buffer": ""},
				AfterState:      map[string]string{"NameField.buffer": "Ada"},
			},
			{
				Order:           3,
				Kind:            "key_down",
				TargetComponent: "SaveButton",
				DispatchPath:    []string{"AppModelApp", "SaveButton"},
				Handled:         true,
				Pass:            true,
				Key:             13,
				Width:           480,
				Height:          320,
				TimestampMS:     2,
				BufferSlots:     []int{6, 0, 0, 0, 13, 480, 320, 2, 0},
				BeforeState:     map[string]string{"AppModelApp.save_count": "0"},
				AfterState:      map[string]string{"AppModelApp.save_count": "1"},
			},
		},
		Frames: []surface.FrameReport{
			{Order: 1, Width: beforeFrame.Width, Height: beforeFrame.Height, Stride: beforeFrame.Stride, Checksum: checksumRGBA(beforeFrame.Pixels), Presented: true},
			{Order: 2, Width: afterFrame.Width, Height: afterFrame.Height, Stride: afterFrame.Stride, Checksum: checksumRGBA(afterFrame.Pixels), Presented: true},
		},
		StateTransitions: []surface.StateTransitionReport{
			{Order: 1, Component: "AppModelApp", Field: "focused", Before: "", After: "NameField", Cause: "focus"},
			{Order: 2, Component: "NameField", Field: "buffer", Before: "", After: "Ada", Cause: "command.insert_text"},
			{Order: 3, Component: "AppModelApp", Field: "route", Before: "home", After: "settings", Cause: "command.navigate"},
			{Order: 4, Component: "AppModelApp", Field: "pending_task", Before: "1", After: "0", Cause: "command.async_complete"},
			{Order: 5, Component: "AppModelApp", Field: "history_depth", Before: "0", After: "1", Cause: "command.undoable"},
			{Order: 6, Component: "AppModelApp", Field: "save_count", Before: "0", After: "1", Cause: "command.save"},
		},
		AppModel: &surface.AppModelReport{
			Schema:                "tetra.surface.app-model.v1",
			AppModelLevel:         "explicit-command-reducer-v1",
			ReleaseScope:          "surface-v1-linux-web",
			Source:                "examples/surface_app_model.tetra",
			Module:                "lib.core.surface_app",
			UsesComponentTreeAPI:  true,
			CallerOwnedState:      true,
			ExplicitEventBindings: true,
			DeterministicReducer:  true,
			StateFields:           []string{"route", "focused", "name_buffer", "save_count", "pending_task", "history_depth", "redo_depth"},
			CommandRegistry:       []string{"focus.name", "text.insert", "nav.push.settings", "nav.back", "async.save.start", "async.save.complete", "async.save.cancel", "history.undo", "history.redo"},
			EventBindings: []surface.AppModelEventBindingReport{
				{Order: 1, EventOrder: 1, EventKind: "mouse_up", Target: "NameField", DispatchPath: []string{"AppModelApp", "NameField"}, Command: "focus.name", Explicit: true},
				{Order: 2, EventOrder: 2, EventKind: "text_input", Target: "NameField", DispatchPath: []string{"AppModelApp", "NameField"}, Command: "text.insert", Explicit: true},
				{Order: 3, EventOrder: 3, EventKind: "key_down", Target: "SaveButton", DispatchPath: []string{"AppModelApp", "SaveButton"}, Command: "async.save.start", Explicit: true},
			},
			CommandDispatches: []surface.AppModelCommandDispatchReport{
				{Order: 1, EventOrder: 1, Command: "focus.name", Kind: "focus", Target: "NameField", Handled: true, BeforeState: map[string]string{"focused": ""}, AfterState: map[string]string{"focused": "NameField"}},
				{Order: 2, EventOrder: 2, Command: "text.insert", Kind: "edit", Target: "NameField", Handled: true, BeforeState: map[string]string{"name_buffer": ""}, AfterState: map[string]string{"name_buffer": "Ada"}, Reversible: true, HistoryIndex: 1},
				{Order: 3, EventOrder: 3, Command: "async.save.start", Kind: "async_start", Target: "SaveButton", Handled: true, BeforeState: map[string]string{"pending_task": "0"}, AfterState: map[string]string{"pending_task": "1"}, AsyncTaskID: "save-1"},
				{Order: 4, Command: "async.save.complete", Kind: "async_complete", Target: "AppModelApp", Handled: true, BeforeState: map[string]string{"pending_task": "1", "save_count": "0"}, AfterState: map[string]string{"pending_task": "0", "save_count": "1"}, AsyncTaskID: "save-1"},
			},
			NavigationTransitions: []surface.AppModelNavigationReport{
				{Order: 1, Command: "nav.push.settings", Operation: "push", BeforeRoute: "home", AfterRoute: "settings", StackBefore: []string{"home"}, StackAfter: []string{"home", "settings"}},
				{Order: 2, Command: "nav.back", Operation: "back", BeforeRoute: "settings", AfterRoute: "home", StackBefore: []string{"home", "settings"}, StackAfter: []string{"home"}},
				{Order: 3, Command: "nav.back", Operation: "back", BeforeRoute: "home", AfterRoute: "home", StackBefore: []string{"home"}, StackAfter: []string{"home"}, UnderflowRejected: true},
			},
			FocusScopeTransitions: []surface.AppModelFocusScopeReport{
				{Order: 1, Scope: "main", BeforeFocus: "", AfterFocus: "NameField"},
				{Order: 2, Scope: "dialog", BeforeFocus: "DialogCancel", AfterFocus: "DialogConfirm", Wrapped: true, ModalTrap: true},
			},
			AsyncTasks: []surface.AppModelAsyncTaskReport{
				{ID: "save-1", Command: "async.save.start", Operation: "start", Status: "pending", BeforeState: map[string]string{"pending_task": "0"}, AfterState: map[string]string{"pending_task": "1"}},
				{ID: "save-1", Command: "async.save.complete", Operation: "complete", Status: "completed", BeforeState: map[string]string{"pending_task": "1"}, AfterState: map[string]string{"pending_task": "0"}, CompletionOrder: 4},
				{ID: "save-2", Command: "async.save.cancel", Operation: "cancel", Status: "canceled", BeforeState: map[string]string{"pending_task": "1", "save_count": "1"}, AfterState: map[string]string{"pending_task": "0", "save_count": "1"}, Canceled: true},
			},
			UndoRedoTransitions: []surface.AppModelUndoRedoReport{
				{Order: 1, Command: "text.insert", HistoryIndex: 1, Operation: "record", Before: "", After: "Ada", MatchedHistoryEntry: true, Applied: true},
				{Order: 2, Command: "history.undo", HistoryIndex: 1, Operation: "undo", Before: "Ada", After: "", MatchedHistoryEntry: true, Applied: true},
				{Order: 3, Command: "history.redo", HistoryIndex: 1, Operation: "redo", Before: "", After: "Ada", MatchedHistoryEntry: true, Applied: true},
			},
			NegativeGuards: surface.AppModelNegativeGuardsReport{
				NoHiddenAppState:              true,
				NoReactHooks:                  true,
				NoDOMEventModel:               true,
				NoUserJS:                      true,
				NoPlatformWidgets:             true,
				AsyncCancelNoMutation:         true,
				NavigationUnderflowRejected:   true,
				FocusScopeEscapeRejected:      true,
				UndoRedoRequiresHistory:       true,
				CommandWithoutBindingRejected: true,
			},
		},
		Cases: []surface.CaseReport{
			{Name: "pure Tetra component app", Kind: "positive", Ran: true, Pass: true},
			{Name: "headless event dispatch", Kind: "positive", Ran: true, Pass: true},
			{Name: "headless framebuffer checksum", Kind: "positive", Ran: true, Pass: true},
			{Name: "headless actual runner trace", Kind: "positive", Ran: true, Pass: true},
			{Name: "host-provided pointer event dispatch", Kind: "positive", Ran: true, Pass: true},
			{Name: "host event buffer poll_event", Kind: "positive", Ran: true, Pass: true},
			{Name: "pre/post event frame sequence", Kind: "positive", Ran: true, Pass: true},
			{Name: "component hierarchy dispatch", Kind: "positive", Ran: true, Pass: true},
			{Name: "component text input scalar dispatch", Kind: "positive", Ran: true, Pass: true},
			{Name: "host text payload buffer", Kind: "positive", Ran: true, Pass: true},
			{Name: "component focus dispatch", Kind: "positive", Ran: true, Pass: true},
			{Name: "component accessibility metadata", Kind: "positive", Ran: true, Pass: true},
			{Name: "no legacy UI sidecar artifacts", Kind: "positive", Ran: true, Pass: true},
			{Name: "state transition", Kind: "positive", Ran: true, Pass: true},
			{Name: "app model explicit event-to-command binding", Kind: "positive", Ran: true, Pass: true},
			{Name: "app model deterministic command reducer", Kind: "positive", Ran: true, Pass: true},
			{Name: "app model navigation stack", Kind: "positive", Ran: true, Pass: true},
			{Name: "app model focus scope modal trap", Kind: "positive", Ran: true, Pass: true},
			{Name: "app model async completion cancellation boundary", Kind: "positive", Ran: true, Pass: true},
			{Name: "app model undo redo history", Kind: "positive", Ran: true, Pass: true},
			{Name: "app model no React hooks DOM event model hidden JS state", Kind: "positive", Ran: true, Pass: true},
			{Name: "reject legacy UI evidence", Kind: "negative", Ran: true, Pass: true, ExpectedError: "legacy UI evidence rejected"},
		},
	}
}
func runLinuxAppShellScenario() headlessScenario {
	features := linuxAppShellFeatureLedgerRows()
	return headlessScenario{
		Components: []surface.ComponentReport{
			{
				ID:        "NotesShellApp",
				Type:      "examples.surface_linux_app_shell_notes.NotesShellApp",
				Bounds:    surface.RectReport{X: 0, Y: 0, W: 720, H: 540},
				Abilities: []string{"measure", "layout", "draw", "event", "focus", "text", "accessibility"},
				State:     map[string]string{"open_windows": "2", "focused_window": "notes-main", "accessibility_role": "application"},
			},
			{
				ID:        "NotesMainWindow",
				Type:      "examples.surface_linux_app_shell_notes.NotesMainWindow",
				Parent:    "NotesShellApp",
				Bounds:    surface.RectReport{X: 0, Y: 0, W: 560, H: 420},
				Abilities: []string{"measure", "layout", "draw", "event", "focus", "text", "accessibility"},
				State:     map[string]string{"title": "Notes", "lifecycle": "reopened", "dpi_scale_milli": "1250", "cursor": "text", "accessibility_role": "document"},
			},
			{
				ID:        "NotesInspectorWindow",
				Type:      "examples.surface_linux_app_shell_notes.NotesInspectorWindow",
				Parent:    "NotesShellApp",
				Bounds:    surface.RectReport{X: 24, Y: 24, W: 320, H: 240},
				Abilities: []string{"measure", "layout", "draw", "event", "focus", "text", "accessibility"},
				State:     map[string]string{"title": "Inspector", "lifecycle": "open", "dpi_scale_milli": "1000", "cursor": "pointer", "accessibility_role": "panel"},
			},
		},
		Events: []surface.EventReport{
			{
				Order:           1,
				Kind:            "mouse_up",
				TargetComponent: "NotesMainWindow",
				DispatchPath:    []string{"NotesShellApp", "NotesMainWindow"},
				Handled:         true,
				Pass:            true,
				X:               40,
				Y:               72,
				Width:           560,
				Height:          420,
				TimestampMS:     0,
				BufferSlots:     []int{5, 40, 72, 1, 0, 560, 420, 0, 0},
				BeforeState:     map[string]string{"NotesShellApp.focused_window": ""},
				AfterState:      map[string]string{"NotesShellApp.focused_window": "notes-main"},
			},
			{
				Order:           2,
				Kind:            "key_down",
				TargetComponent: "NotesMainWindow",
				DispatchPath:    []string{"NotesShellApp", "NotesMainWindow"},
				Handled:         true,
				Pass:            true,
				Key:             78,
				Width:           560,
				Height:          420,
				TimestampMS:     2,
				BufferSlots:     []int{6, 0, 0, 1, 78, 560, 420, 2, 0},
				BeforeState:     map[string]string{"NotesMainWindow.shortcut": ""},
				AfterState:      map[string]string{"NotesMainWindow.shortcut": "new-note"},
			},
			{
				Order:           3,
				Kind:            "text_input",
				TargetComponent: "NotesMainWindow",
				DispatchPath:    []string{"NotesShellApp", "NotesMainWindow"},
				Handled:         true,
				Pass:            true,
				Width:           560,
				Height:          420,
				TimestampMS:     3,
				TextLen:         5,
				TextBytesHex:    "4e6f746573",
				BufferSlots:     []int{8, 0, 0, 0, 0, 560, 420, 3, 5},
				BeforeState:     map[string]string{"NotesMainWindow.buffer": ""},
				AfterState:      map[string]string{"NotesMainWindow.buffer": "Notes"},
			},
			{
				Order:           4,
				Kind:            "resize",
				TargetComponent: "NotesMainWindow",
				DispatchPath:    []string{"NotesShellApp", "NotesMainWindow"},
				Handled:         true,
				Pass:            true,
				Width:           720,
				Height:          540,
				TimestampMS:     4,
				BufferSlots:     []int{7, 0, 0, 0, 0, 720, 540, 4, 0},
				BeforeState:     map[string]string{"NotesMainWindow.size": "560x420", "NotesMainWindow.dpi": "1000"},
				AfterState:      map[string]string{"NotesMainWindow.size": "720x540", "NotesMainWindow.dpi": "1250"},
			},
			{
				Order:           5,
				Kind:            "close",
				TargetComponent: "NotesInspectorWindow",
				DispatchPath:    []string{"NotesShellApp", "NotesInspectorWindow"},
				Handled:         true,
				Pass:            true,
				Width:           320,
				Height:          240,
				TimestampMS:     5,
				BufferSlots:     []int{9, 0, 0, 0, 0, 320, 240, 5, 0},
				BeforeState:     map[string]string{"NotesInspectorWindow.open": "true"},
				AfterState:      map[string]string{"NotesInspectorWindow.open": "false"},
			},
		},
		Frames: []surface.FrameReport{
			{Order: 1, Width: 400, Height: 240, Stride: 1600, Checksum: "1111111111111111111111111111111111111111111111111111111111111111", Presented: true},
			{Order: 5, Width: 560, Height: 420, Stride: 2240, Checksum: "2222222222222222222222222222222222222222222222222222222222222222", Presented: true},
			{Order: 6, Width: 720, Height: 540, Stride: 2880, Checksum: "3333333333333333333333333333333333333333333333333333333333333333", Presented: true},
		},
		StateTransitions: []surface.StateTransitionReport{
			{Order: 1, Component: "NotesShellApp", Field: "focused_window", Before: "", After: "notes-main", Cause: "lifecycle.open"},
			{Order: 2, Component: "NotesInspectorWindow", Field: "open", Before: "true", After: "false", Cause: "lifecycle.close"},
			{Order: 3, Component: "NotesMainWindow", Field: "size", Before: "560x420", After: "720x540", Cause: "resize"},
		},
		LinuxAppShell: &surface.LinuxAppShellReport{
			Schema:          surface.LinuxAppShellSchemaV1,
			AppShellLevel:   "linux-app-shell-subset-v1",
			ReleaseScope:    surface.ReleaseScopeSurfaceV1LinuxWeb,
			Source:          "examples/surface_linux_app_shell_notes.tetra",
			Module:          "lib.core.surface_app_shell",
			HostAdapter:     "wayland-shm-rgba-release-v1",
			ProductionClaim: true,
			Experimental:    false,
			WindowLifecycle: []surface.LinuxAppShellLifecycleReport{
				{Order: 1, WindowID: "notes-main", Operation: "open", HostTrace: true, Pass: true},
				{Order: 2, WindowID: "notes-inspector", Operation: "open", HostTrace: true, Pass: true},
				{Order: 3, WindowID: "notes-inspector", Operation: "close", HostTrace: true, Pass: true},
				{Order: 4, WindowID: "notes-inspector", Operation: "reopen", HostTrace: true, Pass: true},
			},
			Windows: []surface.LinuxAppShellWindowReport{
				{ID: "notes-main", Title: "Notes", Role: "primary", BlockRoot: "NotesMainWindow", RealWindow: true, Presented: true, Width: 720, Height: 540, DPIScaleMilli: 1250},
				{ID: "notes-inspector", Title: "Inspector", Role: "secondary", BlockRoot: "NotesInspectorWindow", RealWindow: true, Presented: true, Width: 320, Height: 240, DPIScaleMilli: 1000},
			},
			ResizeDPI: []surface.LinuxAppShellResizeDPIReport{
				{WindowID: "notes-main", Operation: "resize", BeforeWidth: 560, BeforeHeight: 420, AfterWidth: 720, AfterHeight: 540, DPIScaleMilli: 1250, HostTrace: true, Pass: true},
				{WindowID: "notes-main", Operation: "dpi_scale", BeforeWidth: 720, BeforeHeight: 540, AfterWidth: 720, AfterHeight: 540, DPIScaleMilli: 1250, HostTrace: true, Pass: true},
			},
			CursorTransitions: []surface.LinuxAppShellCursorReport{
				{WindowID: "notes-main", Cursor: "pointer", Target: "NotesMainWindow", HostTrace: true, Pass: true},
				{WindowID: "notes-main", Cursor: "text", Target: "NotesMainWindow", HostTrace: true, Pass: true},
				{WindowID: "notes-main", Cursor: "resize", Target: "NotesMainWindow", HostTrace: true, Pass: true},
			},
			Clipboard:     surface.LinuxAppShellCapabilityReport{Level: "clipboard-text-v1", HostTrace: true, ArtifactKind: "linux-app-shell-host-trace", Read: true, Write: true, Pass: true},
			IME:           surface.LinuxAppShellCapabilityReport{Level: "composition-baseline-v1", HostTrace: true, ArtifactKind: "linux-app-shell-host-trace", Start: true, Update: true, Commit: true, Cancel: true, Pass: true},
			Accessibility: surface.LinuxAppShellCapabilityReport{Level: "platform-bridge-v1", HostTrace: true, ArtifactKind: "linux-accessibility-platform-probe", MetadataTree: true, PlatformExport: true, Pass: true},
			ShellFeatures: features,
			HostTraces: []surface.LinuxAppShellHostTraceReport{
				{Name: "lifecycle", ArtifactKind: "linux-app-shell-host-trace", Path: "surface-linux-app-shell-host-trace.json", Pass: true},
				{Name: "windows", ArtifactKind: "linux-app-shell-window-trace", Path: "surface-linux-app-shell-window-trace.json", Pass: true},
				{Name: "accessibility", ArtifactKind: "linux-accessibility-platform-probe", Path: "surface-linux-accessibility-probe.json", Pass: true},
			},
			NegativeGuards: surface.LinuxAppShellNegativeGuards{
				NoGTK:             true,
				NoQT:              true,
				NoNativeWidgets:   true,
				NoElectronRuntime: true,
				NoReactRuntime:    true,
				NoDOMUI:           true,
				NoUserJS:          true,
				NoPlatformWidgets: true,
			},
		},
		SecurityPermissions: securityPermissionReportForAppShell(features),
		Cases: []surface.CaseReport{
			{Name: "pure Tetra component app", Kind: "positive", Ran: true, Pass: true},
			{Name: "host-provided pointer event dispatch", Kind: "positive", Ran: true, Pass: true},
			{Name: "host event buffer poll_event", Kind: "positive", Ran: true, Pass: true},
			{Name: "pre/post event frame sequence", Kind: "positive", Ran: true, Pass: true},
			{Name: "component hierarchy dispatch", Kind: "positive", Ran: true, Pass: true},
			{Name: "component text input scalar dispatch", Kind: "positive", Ran: true, Pass: true},
			{Name: "host text payload buffer", Kind: "positive", Ran: true, Pass: true},
			{Name: "component focus dispatch", Kind: "positive", Ran: true, Pass: true},
			{Name: "component accessibility metadata", Kind: "positive", Ran: true, Pass: true},
			{Name: "no legacy UI sidecar artifacts", Kind: "positive", Ran: true, Pass: true},
			{Name: "state transition", Kind: "positive", Ran: true, Pass: true},
			{Name: "reject legacy UI evidence", Kind: "negative", Ran: true, Pass: true, ExpectedError: "legacy UI evidence rejected"},
			{Name: "linux-x64 real-window surface", Kind: "positive", Ran: true, Pass: true},
			{Name: "linux-x64 native input event pump", Kind: "positive", Ran: true, Pass: true},
			{Name: "linux-x64 real-window resize event", Kind: "positive", Ran: true, Pass: true},
			{Name: "linux-x64 real-window close event", Kind: "positive", Ran: true, Pass: true},
			{Name: "linux release real window presented frame", Kind: "positive", Ran: true, Pass: true},
			{Name: "linux release accessibility bridge probe", Kind: "positive", Ran: true, Pass: true},
			{Name: "linux app-shell v1 schema", Kind: "positive", Ran: true, Pass: true},
			{Name: "linux app-shell lifecycle open close reopen", Kind: "positive", Ran: true, Pass: true},
			{Name: "linux app-shell multi-window notes reference", Kind: "positive", Ran: true, Pass: true},
			{Name: "linux app-shell resize dpi cursor trace", Kind: "positive", Ran: true, Pass: true},
			{Name: "linux app-shell clipboard ime accessibility adapters", Kind: "positive", Ran: true, Pass: true},
			{Name: "linux app-shell file dialog notification blocked-pass", Kind: "positive", Ran: true, Pass: true},
			{Name: "linux app-shell electron feature ledger", Kind: "positive", Ran: true, Pass: true},
			{Name: "linux app-shell dialog file picker tray blocked-pass", Kind: "positive", Ran: true, Pass: true},
			{Name: "linux app-shell crash error report scoped adapters", Kind: "positive", Ran: true, Pass: true},
			{Name: "linux app-shell rejects GTK Qt native widget UI", Kind: "negative", Ran: true, Pass: true, ExpectedError: "native widget UI rejected"},
			{Name: "linux app-shell no Electron React DOM application scripting", Kind: "negative", Ran: true, Pass: true, ExpectedError: "runtime substitute rejected"},
			{Name: "surface security permission model default deny filesystem network", Kind: "positive", Ran: true, Pass: true},
			{Name: "surface security app-shell feature policy enforcement", Kind: "positive", Ran: true, Pass: true},
			{Name: "surface security IPC process boundary schema validation", Kind: "positive", Ran: true, Pass: true},
			{Name: "surface security asset font image local hash policy", Kind: "positive", Ran: true, Pass: true},
			{Name: "surface security network asset fetch rejected", Kind: "negative", Ran: true, Pass: true, ExpectedError: "network asset fetch rejected"},
			{Name: "surface security notification dialog permission nonclaims", Kind: "positive", Ran: true, Pass: true},
			{Name: "surface performance budget startup first frame", Kind: "positive", Ran: true, Pass: true},
			{Name: "surface performance budget frame p50 p95", Kind: "positive", Ran: true, Pass: true},
			{Name: "surface performance budget memory cache framebuffer rss", Kind: "positive", Ran: true, Pass: true},
			{Name: "surface performance budget binary size", Kind: "positive", Ran: true, Pass: true},
			{Name: "surface performance budget cpu power proxy", Kind: "positive", Ran: true, Pass: true},
			{Name: "surface performance budget faster than electron nonclaim", Kind: "negative", Ran: true, Pass: true, ExpectedError: "unsupported faster than electron claim rejected"},
		},
	}
}
