package main

var requiredOwnershipAuditRequirements = []string{
	"Borrow/consume/inout model",
	"SSA local lifetime analysis",
	"Interprocedural lifetime analysis",
	"Alias/provenance tracking",
	"Move/copy/drop/finalization semantics",
	"Partial moves for struct/enum fields",
	"Ownership-aware generics/interfaces/callables",
	"Heap/global/thread/callback escape analysis",
	"Actor/task/island/resource transfer rules",
	"Stable forbidden-case diagnostics",
	"Spec/docs/examples/tests evidence",
	"Dedicated ownership validator evidence",
	"Feature registry evidence",
	"Release-gate evidence",
}

var forbiddenOwnershipAuditPhrases = []string{
	"mock",
	"placeholder",
	"fake",
}

var requiredOwnershipAuditEvidencePhrases = map[string][]string{
	"Spec/docs/examples/tests evidence": {"examples/ownership_smoke.tetra"},
	"SSA local lifetime analysis": {
		"branch/match/loop task-handle maybe-joined, task-group maybe-closed, island maybe-freed",
		"branch/match/loop resource finalization merge diagnostics with stable TETRA2101 JSON evidence",
	},
	"Interprocedural lifetime analysis": {
		"Local return-resource summaries, typed-error throw-resource summaries including rethrow-through-`try`",
		"same-module and interface-only cross-module per-field interprocedural region summaries for aggregate returns from multiple island parameters, including optional aggregate wrappers, enum payload wrappers, branch aggregate wrappers, match aggregate wrappers, if-let aggregate wrappers",
		"mixed safe/provenance aggregate branch and match returns",
		"optional mixed safe/provenance aggregate branch merges",
		"generated `.t4i` direct/local/aggregate-local-alias/aggregate-field-access/aggregate-field-local-alias resource return, assignment/let/direct-if-let/direct-match/field-local/if-let/match optional and nested/field-local nested optional resource return, typed-error direct/field-local-alias throw, and rethrow-through-`try` direct/field-local-alias provenance stubs",
		"selected same-module/cross-module transitive interprocedural resource cases, including task-handle, task-group, island, struct-field, enum-payload, enum-constructor return, same-module throw/catch enum-payload, if-let/match optional-payload, and nested struct/enum optional-payload return resource aliases",
	},
	"Alias/provenance tracking": {
		"Ownership paths, enum payload aliases, borrowed ptr-leaf aliases for ptr-containing aggregate parameters, borrowed scalar `ptr` assignment into optional `ptr?` payloads, borrowed region-bearing slice assignment into optional `[]u8?` payloads, and pattern-bound enum/optional payloads",
		"optional payload consume aliases, if-let/match optional resource aliases",
		"typed-error throw/catch and rethrow-through-try enum-payload resource aliases with stable TETRA2101 JSON diagnostic evidence",
		"generated `.t4i` direct/local/aggregate-local-alias/aggregate-field-access/aggregate-field-local-alias resource return, assignment/let/direct-if-let/direct-match/field-local/if-let/match optional and nested/field-local nested optional resource return, typed-error direct/field-local-alias throw, and rethrow-through-`try` direct/field-local-alias provenance stubs",
		"optional resource wrapper aliases including nested struct/enum wrappers",
		"same-module/cross-module actor if-let/match optional-payload, struct-field, enum-payload, and transitive interprocedural consume aliases including same-module/cross-module actor struct-field/enum-payload alias transfer diagnostics with stable TETRA2101 JSON diagnostic evidence",
		"same-module/cross-module task-handle/task-group struct-field/enum-payload transfer/join/close aliases including same-module/cross-module task-handle struct-field/enum-payload alias transfer diagnostics with stable TETRA2101 JSON diagnostic evidence, same-module/cross-module task-handle struct-field/enum-payload alias join diagnostics with stable TETRA2101 JSON diagnostic evidence and same-module/cross-module task-group struct-field/enum-payload alias close diagnostics with stable TETRA2101 JSON diagnostic evidence",
		"same-module/cross-module monomorphized generic struct actor consume aliases, same-module/cross-module monomorphized generic struct task-handle/task-group/island resource aliases with stable TETRA2101 CLI JSON evidence",
		"same-module/cross-module transitive interprocedural task-handle/task-group/island resource aliases with stable TETRA2101 CLI JSON evidence",
		"same-module/cross-module enum-constructor return resource aliases with stable TETRA2101 CLI JSON evidence",
		"ambiguous resource provenance",
	},
	"Ownership-aware generics/interfaces/callables": {
		"generic function-typed global consume-marker preservation and ownership mismatch diagnostics",
		"same-module/cross-module generic aggregate and optional-ptr owned/consume/inout instantiations including slice-containing struct/enum aggregate instantiations with stable TETRA2101 CLI JSON evidence",
		"same-module/cross-module generic borrow-aggregate/optional-ptr return diagnostics with stable TETRA2102 CLI JSON evidence",
		"same-module/cross-module monomorphized generic struct actor consume alias diagnostics plus same-module/cross-module monomorphized generic struct task-handle/task-group/island resource aliases with stable TETRA2101 CLI JSON evidence",
		"same-module/cross-module monomorphized generic struct task-handle/task-group/island resource aliases with stable TETRA2101 CLI JSON evidence",
		"same-module/cross-module function-typed value/struct-field/enum-payload optional-ptr owned/consume/inout callback diagnostics with stable TETRA2101 CLI JSON evidence",
		"function-typed value/struct-field/enum-payload callback slice-containing struct/enum owned/consume/inout call rejections with stable TETRA2101 JSON diagnostic evidence",
		"same-module/cross-module protocol parameter ownership matching plus same-module/cross-module protocol impl parameter ownership mismatch diagnostics with stable TETRA2001 CLI JSON evidence",
		"same-module/cross-module generic protocol requirement parameter ownership mismatch diagnostics with stable TETRA2001 JSON diagnostic evidence",
		"generated `.t4i` function-typed parameter local-alias return metadata for interface-only global-storage diagnostics",
		"function type ownership markers parse/format plus function-typed callable ownership-marker diagnostics",
	},
	"Move/copy/drop/finalization semantics": {
		"same-module/cross-module struct/enum whole-value call/let/return rejection after partial consume",
		"same-module/cross-module enum wrapper-constructor rejection after partial field/payload consume",
		"mutable reinitialization",
		"task/island/task-group finalization including stable `TETRA2101` task-group use-after-close",
		"same-module/cross-module optional-payload whole-value rejection after payload consume/free with stable TETRA2101 JSON diagnostic evidence",
		"same-module/cross-module task-handle struct-field/enum-payload alias join diagnostics with stable TETRA2101 JSON diagnostic evidence",
		"same-module/cross-module task-group struct-field/enum-payload alias close diagnostics with stable TETRA2101 JSON diagnostic evidence",
		"same-module/cross-module task-handle/task-group if-let/match optional-payload join/close aliases with stable TETRA2101 CLI JSON evidence",
		"same-module/cross-module nested optional resource wrapper alias use-after-free CLI JSON diagnostics",
		"same-module/cross-module struct-field/enum-payload alias use-after-free CLI JSON diagnostics",
		"same-module/cross-module task_group_cancel return provenance diagnostics with stable TETRA2101 CLI JSON evidence",
		"same-module/cross-module struct-field and enum-payload alias use-after-free with stable TETRA2101 JSON diagnostic evidence",
	},
	"Stable forbidden-case diagnostics": {
		"use-after-move/use-after-consume",
		"partial struct/enum consume whole-value rejection",
		"partial struct/enum whole-copy rejection",
		"partial struct/enum enum-constructor rejection",
		"optional payload consume/free whole-value rejection",
		"actor/task use-after-transfer",
		"same-module/cross-module actor struct-field/enum-payload alias transfer diagnostics with stable TETRA2101 JSON diagnostic evidence",
		"same-module/cross-module task-handle struct-field/enum-payload alias transfer diagnostics with stable TETRA2101 JSON diagnostic evidence",
		"task-handle struct-field/enum-payload alias use-after-transfer/join",
		"task-group use-after-close",
		"branch/match/loop actor consume reuse with stable branch actor CLI JSON",
		"maybe-consumed joins",
		"branch/match/loop task-handle maybe-joined, task-group maybe-closed, and island maybe-freed merge diagnostics",
		"branch/match/loop resource finalization merge diagnostics with stable TETRA2101 JSON evidence",
		"borrow escape",
		"alias conflicts",
		"use-after-free/join/close",
		"double-drop/double-finalization",
		"callable escape diagnostics",
		"CLI JSON ownership/lifetime safety codes",
		"borrow-escape including fixed-array alias return/global assignment/optional global assignment/inout assignment",
		"borrowed string alias return/global assignment",
		"slice-containing struct literal/alias/nested struct/enum-payload return and inout assignment escapes",
		"slice-containing enum direct/alias return escape CLI JSON evidence",
		"slice-containing struct/enum owned/consume/inout call escape CLI JSON evidence including imported direct cases",
		"same-module/cross-module generic borrow-aggregate/optional-ptr return diagnostics with stable TETRA2102 CLI JSON evidence",
		"same-module/cross-module function-typed value/struct-field/enum-payload optional-ptr owned/consume/inout callback diagnostics with stable TETRA2101 CLI JSON evidence",
		"function-typed value/struct-field/enum-payload callback slice-containing struct/enum owned/consume/inout call rejections with stable TETRA2101 JSON diagnostic evidence",
		"ptr/slice optional assignment return/owned/consume/inout escape with stable same-module/cross-module slice optional assignment return/owned/consume/inout CLI JSON evidence",
		"same-module/cross-module slice optional payload binding owned/consume/inout call, `inout` assignment, and global assignment CLI JSON evidence",
		"same-module/cross-module direct slice global assignment with stable TETRA2102 JSON diagnostic evidence",
		"same-module/cross-module optional ptr global assignment with stable TETRA2102 JSON diagnostic evidence",
		"same-module/cross-module optional aggregate global assignment with stable TETRA2102 JSON diagnostic evidence",
		"same-module/cross-module ptr optional assignment if-let/match global escape with stable TETRA2102 JSON diagnostic evidence",
		"same-module/cross-module ptr enum alias return escape with stable TETRA2102 JSON diagnostic evidence",
		"same-module/cross-module ptr-containing aggregate whole/field/alias/nested-field return escapes with stable TETRA2102 JSON diagnostic evidence",
		"same-module/cross-module whole-aggregate global assignment with stable TETRA2102 JSON diagnostic evidence",
		"same-module/cross-module ptr-containing enum whole-value global assignment with stable TETRA2102 JSON diagnostic evidence",
		"same-module/cross-module global field target assignment with stable TETRA2102 JSON diagnostic evidence",
		"same-module/cross-module aggregate and nested-aggregate global field escapes with stable TETRA2102 JSON diagnostic evidence",
		"same-module/cross-module ptr enum-payload return/global/inout assignment escapes with stable TETRA2102 JSON diagnostic evidence",
		"same-module/cross-module ptr optional-payload return/global/inout assignment escapes with stable TETRA2102 JSON diagnostic evidence",
		"same-module/cross-module slice optional-payload inout/global assignment escapes with stable TETRA2102 JSON diagnostic evidence",
		"same-module/cross-module nested slice enum-payload return/inout/global assignment escapes with stable TETRA2102 JSON diagnostic evidence",
		"same-module/cross-module nested slice struct return/inout/global assignment escapes with stable TETRA2102 JSON diagnostic evidence",
		"same-module/cross-module ptr-containing/nested aggregate owned/consume/inout call rejections with stable TETRA2101 JSON diagnostic evidence",
		"same-module/cross-module ptr enum-payload owned/consume/inout call rejections with stable TETRA2101 JSON diagnostic evidence",
		"resource use-after-free/double-join/ambiguous-provenance, island transfer non-local-payload, callable mutable-capture global/heap-escape, callable pointer/resource capture escape, function-typed storage/return unsupported capture rejection, callable global-storage escape, unsupported function-value escape, unsupported function-value call, capturing closure raw-ptr escape, captured closure explicit type-arg rejection, function-typed explicit type-arg rejection, generic closure/generic callback-closure capture, generic closure pointer/direct-call, and imported mutable function-typed global boundary JSON diagnostics",
	},
	"Actor/task/island/resource transfer rules": {
		"branch/match/loop actor consume reuse diagnostics with stable TETRA2101 CLI JSON evidence",
		"actor/task use-after-transfer diagnostics with stable TETRA2101 CLI JSON evidence",
		"island transfer non-local-payload rejection with stable TETRA2101 CLI JSON evidence",
		"same-module/cross-module transitive actor consume alias diagnostics with stable TETRA2101 CLI JSON evidence",
		"same-module/cross-module monomorphized generic struct actor consume alias diagnostics with stable TETRA2101 CLI JSON evidence",
		"same-module/cross-module task_group_cancel return provenance diagnostics with stable TETRA2101 CLI JSON evidence",
		"same-module/cross-module actor struct-field/enum-payload alias transfer diagnostics with stable TETRA2101 JSON diagnostic evidence",
		"same-module/cross-module actor/task if-let/match optional-payload alias transfer diagnostics with stable TETRA2101 JSON diagnostic evidence",
		"same-module/cross-module task-handle struct-field/enum-payload alias transfer diagnostics with stable TETRA2101 JSON diagnostic evidence",
	},
	"Heap/global/thread/callback escape analysis": {
		"same-module/cross-module fixed-array alias return",
		"same-module/cross-module direct fixed-array global assignment",
		"same-module/cross-module optional fixed-array global assignment",
		"same-module/cross-module fixed-array inout assignment",
		"fixed-array escapes including inout assignment with stable TETRA2102 diagnostic evidence",
		"borrowed string alias return/global assignment",
		"same-module/cross-module direct slice global assignment with stable TETRA2102 JSON diagnostic evidence",
		"same-module/cross-module optional ptr global assignment with stable TETRA2102 JSON diagnostic evidence",
		"same-module/cross-module optional aggregate global assignment with stable TETRA2102 JSON diagnostic evidence",
		"same-module/cross-module ptr optional assignment if-let/match global escape with stable TETRA2102 JSON diagnostic evidence",
		"same-module/cross-module ptr enum alias return escape with stable TETRA2102 JSON diagnostic evidence",
		"same-module/cross-module ptr-containing aggregate whole/field/alias/nested-field return escapes with stable TETRA2102 JSON diagnostic evidence",
		"same-module/cross-module ptr enum-payload return/global/inout assignment escapes with stable TETRA2102 JSON diagnostic evidence",
		"same-module/cross-module ptr optional-payload return/global/inout assignment escapes with stable TETRA2102 JSON diagnostic evidence",
		"same-module/cross-module slice optional-payload inout/global assignment escapes with stable TETRA2102 JSON diagnostic evidence",
		"same-module/cross-module nested slice enum-payload return/inout/global assignment escapes with stable TETRA2102 JSON diagnostic evidence",
		"same-module/cross-module nested slice struct return/inout/global assignment escapes with stable TETRA2102 JSON diagnostic evidence",
		"same-module/cross-module whole-aggregate global assignment with stable TETRA2102 JSON diagnostic evidence",
		"same-module/cross-module ptr-containing enum whole-value global assignment with stable TETRA2102 JSON diagnostic evidence",
		"same-module/cross-module global field target assignment with stable TETRA2102 JSON diagnostic evidence",
		"same-module/cross-module aggregate and nested-aggregate global field escapes with stable TETRA2102 JSON diagnostic evidence",
		"same-module/cross-module ptr-containing/nested aggregate owned/consume/inout call rejections with stable TETRA2101 JSON diagnostic evidence",
		"same-module/cross-module ptr enum-payload owned/consume/inout call rejections with stable TETRA2101 JSON diagnostic evidence",
		"same-module/cross-module ptr optional-payload owned/consume/inout call rejections with stable TETRA2101 JSON diagnostic evidence",
		"same-module/cross-module slice optional-payload owned/consume/inout call rejections with stable TETRA2101 JSON diagnostic evidence",
		"imported direct ptr-containing/nested aggregate owned/consume/inout call rejections with stable TETRA2101 JSON diagnostic evidence",
	},
	"Feature registry evidence": {"./tetra features --format=json"},
	"Release-gate evidence": {
		"bash scripts/ci/test-all.sh",
		"docs/generated/v1_0/test-all/summary.json",
		"status: pass",
		"failed_count: 0",
		"exit_code: 0",
		"validate-test-all-summary",
	},
}
