package release_v030

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestReleaseV030GateAcceptsSameRunSecuritySignoffWithFreshReportArtifacts(t *testing.T) {
	root := releaseV030RunnableFakeRepo(t, []string{
		"| compiler | FuzzParser | testdata/fuzz/FuzzParser/bad | flaky | release-a | go test ./compiler/... -run FuzzParser -count=1 |",
	})
	installReleaseV030CanonicalArtifactGo(t, root)

	reportDir := filepath.Join(root, "fresh-report")
	signoffPath := filepath.Join(root, "same-run-security-review.md")
	signoff := `# v0.3.0 Security Review Signoff

Reviewer: Release Reviewer <security@example.invalid>
Reviewed commit: fake-head-for-same-run-test
Report directory: ` + reportDir + `
Decision: approved for v0.3.0 release

## Evidence Commands

- ` + "`go run ./tools/cmd/verify-docs --manifest docs/generated/manifest.json`: pass" + `
- ` + "`go test ./compiler/... -run 'Unsafe|Capability|Effect|MMIO|Mem' -count=1`: pass" + `
- ` + "`go test ./compiler/... -run 'Privacy|Consent|Budget|Effect' -count=1`: pass" + `
- ` + "`go test ./cli/... ./tools/... -run 'Eco|Permission|Capsule|Trust' -count=1`: pass" + `
- ` + "`bash scripts/release/v1_0/wasi-smoke.sh --report <path>`: pass" + `
- ` + "`bash scripts/release/v1_0/web-smoke.sh --report <path>`: pass" + `

## Artifact Hashes

- summary.json: sha256:0000000000000000000000000000000000000000000000000000000000000000
- artifact-hashes.json: sha256:0000000000000000000000000000000000000000000000000000000000000000
- artifacts/release-state.json: sha256:0000000000000000000000000000000000000000000000000000000000000000

## Residual Risks

- None.
`
	if err := os.WriteFile(signoffPath, []byte(signoff), 0o644); err != nil {
		t.Fatal(err)
	}

	out, err := runReleaseV030RunnableGateWithEnv(t, root, reportDir, []string{
		"TETRA_SECURITY_REVIEW_SIGNOFF=" + signoffPath,
	})
	if err != nil {
		t.Fatalf("same-run security signoff should pass with a fresh report dir: %v\n%s", err, out)
	}
	if !strings.Contains(string(out), "release_v0_3_0_gate: passed") {
		t.Fatalf("same-run security signoff did not reach pass output:\n%s", out)
	}

	archivedRaw, err := os.ReadFile(filepath.Join(reportDir, "artifacts", "security-review.md"))
	if err != nil {
		t.Fatalf("read archived security review: %v", err)
	}
	archived := string(archivedRaw)
	finalArtifactHashes := sha256ForTest(t, filepath.Join(reportDir, "artifact-hashes.json"))
	for _, want := range []string{
		"- summary.json: sha256:",
		"- artifact-hashes.json: " + finalArtifactHashes,
		"- artifacts/release-state.json: sha256:",
		"- artifacts/security-review.md is generated by scripts/release/v0_3_0/gate.sh",
	} {
		if !strings.Contains(archived, want) {
			t.Fatalf("archived same-run signoff missing %q:\n%s", want, archived)
		}
	}
	if strings.Contains(archived, "sha256:0000000000000000000000000000000000000000000000000000000000000000") {
		t.Fatalf("archived same-run signoff kept stale placeholder hashes:\n%s", archived)
	}

	hashRaw, err := os.ReadFile(filepath.Join(reportDir, "artifact-hashes.json"))
	if err != nil {
		t.Fatalf("read artifact-hashes.json: %v", err)
	}
	var manifest struct {
		Artifacts []struct {
			Path string `json:"path"`
		} `json:"artifacts"`
	}
	if err := json.Unmarshal(hashRaw, &manifest); err != nil {
		t.Fatalf("decode artifact-hashes.json: %v\n%s", err, hashRaw)
	}
	foundSecurityReview := false
	for _, artifact := range manifest.Artifacts {
		if artifact.Path == "artifacts/security-review.md" {
			foundSecurityReview = true
			break
		}
	}
	if foundSecurityReview {
		t.Fatalf("artifact-hashes.json must exclude artifacts/security-review.md to avoid a stale hash cycle:\n%s", hashRaw)
	}

	var releaseState struct {
		SecurityReview struct {
			Status string `json:"status"`
		} `json:"security_review"`
	}
	releaseStateRaw, err := os.ReadFile(filepath.Join(reportDir, "artifacts", "release-state.json"))
	if err != nil {
		t.Fatalf("read release-state.json: %v", err)
	}
	if err := json.Unmarshal(releaseStateRaw, &releaseState); err != nil {
		t.Fatalf("decode release-state.json: %v\n%s", err, releaseStateRaw)
	}
	if releaseState.SecurityReview.Status != "deferred" {
		t.Fatalf("release-state security_review.status = %q, want deferred to avoid the security-review hash cycle\n%s", releaseState.SecurityReview.Status, releaseStateRaw)
	}
	releaseStateText, err := os.ReadFile(filepath.Join(reportDir, "artifacts", "release-state.txt"))
	if err != nil {
		t.Fatalf("read release-state.txt: %v", err)
	}
	if !strings.Contains(string(releaseStateText), "security review evidence: deferred") {
		t.Fatalf("release-state.txt missing deferred security review evidence state:\n%s", releaseStateText)
	}
}

func TestReleaseV030GateAcceptsSecuritySignoffPathStartingWithDash(t *testing.T) {
	root := releaseV030RunnableFakeRepo(t, []string{
		"| compiler | FuzzParser | testdata/fuzz/FuzzParser/bad | flaky | release-a | go test ./compiler/... -run FuzzParser -count=1 |",
	})
	installReleaseV030CanonicalArtifactGo(t, root)

	reportDir := filepath.Join(root, "dash-signoff-report")
	signoffPath := "-security-review.md"
	signoff := `# v0.3.0 Security Review Signoff

Reviewer: Release Reviewer <security@example.invalid>
Reviewed commit: fake-head-for-dash-signoff-test
Report directory: ` + reportDir + `
Decision: approved for v0.3.0 release

## Evidence Commands

- ` + "`go run ./tools/cmd/verify-docs --manifest docs/generated/manifest.json`: pass" + `

## Artifact Hashes

- summary.json: sha256:0000000000000000000000000000000000000000000000000000000000000000

## Residual Risks

- None.
`
	if err := os.WriteFile(filepath.Join(root, signoffPath), []byte(signoff), 0o644); err != nil {
		t.Fatal(err)
	}

	out, err := runReleaseV030RunnableGateWithEnv(t, root, reportDir, []string{
		"TETRA_SECURITY_REVIEW_SIGNOFF=" + signoffPath,
	})
	if err != nil {
		t.Fatalf("gate should accept dash-prefixed security signoff source path: %v\n%s", err, out)
	}
	if _, err := os.Stat(filepath.Join(reportDir, "artifacts", "security-review.md")); err != nil {
		t.Fatalf("security review artifact was not archived from dash-prefixed source: %v\n%s", err, out)
	}
}

func TestReleaseV030GateWritesDetachedSecurityReviewHashOutsideCanonicalManifest(t *testing.T) {
	root := releaseV030RunnableFakeRepo(t, []string{
		"| compiler | FuzzParser | testdata/fuzz/FuzzParser/bad | flaky | release-a | go test ./compiler/... -run FuzzParser -count=1 |",
	})
	installReleaseV030CanonicalArtifactGo(t, root)

	reportDir := filepath.Join(root, "fresh-report")
	signoffPath := filepath.Join(root, "same-run-security-review.md")
	signoff := `# v0.3.0 Security Review Signoff

Reviewer: Release Reviewer <security@example.invalid>
Reviewed commit: fake-head-for-detached-hash-test
Report directory: ` + reportDir + `
Decision: approved for v0.3.0 release

## Evidence Commands

- ` + "`go run ./tools/cmd/verify-docs --manifest docs/generated/manifest.json`: pass" + `
- ` + "`go test ./compiler/... -run 'Unsafe|Capability|Effect|MMIO|Mem' -count=1`: pass" + `
- ` + "`go test ./compiler/... -run 'Privacy|Consent|Budget|Effect' -count=1`: pass" + `
- ` + "`go test ./cli/... ./tools/... -run 'Eco|Permission|Capsule|Trust' -count=1`: pass" + `
- ` + "`bash scripts/release/v1_0/wasi-smoke.sh --report <path>`: pass" + `
- ` + "`bash scripts/release/v1_0/web-smoke.sh --report <path>`: pass" + `

## Artifact Hashes

- summary.json: sha256:0000000000000000000000000000000000000000000000000000000000000000
- artifact-hashes.json: sha256:0000000000000000000000000000000000000000000000000000000000000000
- artifacts/release-state.json: sha256:0000000000000000000000000000000000000000000000000000000000000000

## Residual Risks

- None.
`
	if err := os.WriteFile(signoffPath, []byte(signoff), 0o644); err != nil {
		t.Fatal(err)
	}

	out, err := runReleaseV030RunnableGateWithEnv(t, root, reportDir, []string{
		"TETRA_SECURITY_REVIEW_SIGNOFF=" + signoffPath,
	})
	if err != nil {
		t.Fatalf("same-run security signoff should pass with detached hash attestation: %v\n%s", err, out)
	}

	securityReviewPath := filepath.Join(reportDir, "artifacts", "security-review.md")
	detachedHashPath := filepath.Join(reportDir, "artifacts", "security-review.md.sha256")
	detachedRaw, err := os.ReadFile(detachedHashPath)
	if err != nil {
		t.Fatalf("read detached security-review hash: %v", err)
	}
	wantDetached := sha256ForTest(t, securityReviewPath) + "  artifacts/security-review.md\n"
	if string(detachedRaw) != wantDetached {
		t.Fatalf("detached security-review hash mismatch:\nwant %q\ngot  %q", wantDetached, detachedRaw)
	}

	hashRaw, err := os.ReadFile(filepath.Join(reportDir, "artifact-hashes.json"))
	if err != nil {
		t.Fatalf("read artifact-hashes.json: %v", err)
	}
	var manifest struct {
		Artifacts []struct {
			Path string `json:"path"`
		} `json:"artifacts"`
	}
	if err := json.Unmarshal(hashRaw, &manifest); err != nil {
		t.Fatalf("decode artifact-hashes.json: %v\n%s", err, hashRaw)
	}
	for _, artifact := range manifest.Artifacts {
		switch artifact.Path {
		case "artifacts/security-review.md", "artifacts/security-review.md.sha256":
			t.Fatalf("artifact-hashes.json must exclude %s to avoid a security-review hash cycle:\n%s", artifact.Path, hashRaw)
		}
	}
}
