package compiler

import (
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
)

func TestExampleHello(t *testing.T) {
	if runtime.GOOS != "linux" || runtime.GOARCH != "amd64" {
		t.Skip("linux/amd64 only")
	}

	root := projectRoot(t)
	stdout, exitCode := buildAndRunFile(t, filepath.Join(root, "examples", "hello.tetra"))
	if stdout != "Hello from Tetra!\n" {
		t.Fatalf("stdout mismatch: %q", stdout)
	}
	if exitCode != 0 {
		t.Fatalf("exit code mismatch: %d", exitCode)
	}
}

func TestExampleGlobalsSmoke(t *testing.T) {
	if runtime.GOOS != "linux" || runtime.GOARCH != "amd64" {
		t.Skip("linux/amd64 only")
	}

	root := projectRoot(t)
	stdout, exitCode := buildAndRunFile(t, filepath.Join(root, "examples", "globals_smoke.tetra"))
	if stdout != "" {
		t.Fatalf("stdout mismatch: %q", stdout)
	}
	// g_x = g_y + 2 = 40 + 2 = 42, store 7 at g_p, out = 7 + 42 = 49
	if exitCode != 49 {
		t.Fatalf("exit code mismatch: %d", exitCode)
	}
}

func TestExampleStructCtorSmoke(t *testing.T) {
	if runtime.GOOS != "linux" || runtime.GOARCH != "amd64" {
		t.Skip("linux/amd64 only")
	}

	root := projectRoot(t)
	stdout, exitCode := buildAndRunFile(t, filepath.Join(root, "examples", "struct_ctor_smoke.tetra"))
	if stdout != "" {
		t.Fatalf("stdout mismatch: %q", stdout)
	}
	// v.x + v.y + 52 = 40 + 2 + 52 = 94
	if exitCode != 94 {
		t.Fatalf("exit code mismatch: %d", exitCode)
	}
}

func TestExampleExperimentalMath(t *testing.T) {
	if runtime.GOOS != "linux" || runtime.GOARCH != "amd64" {
		t.Skip("linux/amd64 only")
	}

	root := projectRoot(t)
	stdout, exitCode := buildAndRunFile(t, filepath.Join(root, "examples", "experimental_math_smoke.tetra"))
	if stdout != "" {
		t.Fatalf("stdout mismatch: %q", stdout)
	}
	// math.add_i32(40, 2) = 42
	if exitCode != 42 {
		t.Fatalf("exit code mismatch: %d", exitCode)
	}
}

func TestExampleExperimentalMemcpy(t *testing.T) {
	if runtime.GOOS != "linux" || runtime.GOARCH != "amd64" {
		t.Skip("linux/amd64 only")
	}

	root := projectRoot(t)
	stdout, exitCode := buildAndRunFile(t, filepath.Join(root, "examples", "experimental_memcpy_smoke.tetra"))
	if stdout != "" {
		t.Fatalf("stdout mismatch: %q", stdout)
	}
	if exitCode != 93 {
		t.Fatalf("exit code mismatch: %d", exitCode)
	}
}

func TestExampleCapMemPtr(t *testing.T) {
	if runtime.GOOS != "linux" || runtime.GOARCH != "amd64" {
		t.Skip("linux/amd64 only")
	}

	root := projectRoot(t)
	stdout, exitCode := buildAndRunFile(t, filepath.Join(root, "examples", "cap_mem_ptr_smoke.tetra"))
	if stdout != "" {
		t.Fatalf("stdout mismatch: %q", stdout)
	}
	if exitCode != 77 {
		t.Fatalf("exit code mismatch: %d", exitCode)
	}
}

func TestExampleCapMemPtrAddLocal(t *testing.T) {
	if runtime.GOOS != "linux" || runtime.GOARCH != "amd64" {
		t.Skip("linux/amd64 only")
	}

	root := projectRoot(t)
	stdout, exitCode := buildAndRunFile(t, filepath.Join(root, "examples", "cap_mem_smoke.tetra"))
	if stdout != "" {
		t.Fatalf("stdout mismatch: %q", stdout)
	}
	if exitCode != 77 {
		t.Fatalf("exit code mismatch: %d", exitCode)
	}
}

func TestMicroserviceExamplesAndBugLedger(t *testing.T) {
	if runtime.GOOS != "linux" || runtime.GOARCH != "amd64" {
		t.Skip("linux/amd64 only")
	}

	root := projectRoot(t)
	for _, name := range []string{
		"inventory_service.tetra",
		"payments_service.tetra",
		"orders_gateway.tetra",
		"memory_cache_service.tetra",
		"parallel_fanout_service.tetra",
		"compiler_pipeline_service.tetra",
		"island_cache_pool_service.tetra",
		"parallel_task_pool_service.tetra",
		"compiler_artifact_router_service.tetra",
		"memory_journal_service.tetra",
		"task_group_service.tetra",
		"typed_task_error_service.tetra",
		"task_group_cancel_service.tetra",
		"wait_select_service.tetra",
		"memory_bounds_probe_service.tetra",
		"callable_router_service.tetra",
		filepath.FromSlash("compiler_modular_gateway/app/main.tetra"),
		"island_slice_matrix_service.tetra",
		"generic_optional_router_service.tetra",
		"actor_deadline_router_service.tetra",
		"typed_task_success_service.tetra",
		"memory_byte_window_service.tetra",
		"callable_return_router_service.tetra",
		filepath.FromSlash("compiler_callable_pack/app/main.tetra"),
		"actor_tagged_loop_service.tetra",
		"task_group_lifecycle_service.tetra",
		"memory_negative_guard_service.tetra",
		"callable_identity_router_service.tetra",
		filepath.FromSlash("compiler_throwing_callable_pack/app/main.tetra"),
		"actor_poll_timeout_service.tetra",
		"task_timeout_recovery_service.tetra",
		"memory_u16_lane_service.tetra",
		"generic_struct_router_service.tetra",
		filepath.FromSlash("compiler_generic_box_pack/app/main.tetra"),
		"task_group_payload_service.tetra",
		"actor_sender_snapshot_service.tetra",
		"memory_copy_window_service.tetra",
		"protocol_bound_generic_service.tetra",
		filepath.FromSlash("compiler_protocol_pack/app/main.tetra"),
		"actor_state_counter_service.tetra",
		"task_group_self_cancel_service.tetra",
		"generic_typed_error_service.tetra",
		filepath.FromSlash("compiler_generic_error_pack/app/main.tetra"),
		"task_group_current_status_service.tetra",
		"actor_dual_mailbox_service.tetra",
		"memory_memset_stride_service.tetra",
		"island_bool_flags_service.tetra",
		filepath.FromSlash("compiler_generic_pair_pack/app/main.tetra"),
		"actor_dual_value_mailbox_service.tetra",
		"task_dual_deadline_service.tetra",
		"memory_zero_copy_service.tetra",
		filepath.FromSlash("compiler_optional_box_pack/app/main.tetra"),
		"actor_timeout_retry_service.tetra",
		"task_poll_deadline_matrix_service.tetra",
		"memory_ptr_table_service.tetra",
		"optional_enum_router_service.tetra",
		"optional_field_update_service.tetra",
		"actor_chain_reply_service.tetra",
		"task_group_poll_service.tetra",
		"memory_i32_stride_service.tetra",
		"actor_value_chain_service.tetra",
		"task_group_typed_success_service.tetra",
		"memory_chained_ptr_stride_service.tetra",
		filepath.FromSlash("compiler_optional_enum_pack/app/main.tetra"),
		"actor_typed_payload_service.tetra",
		"task_select_timeout_service.tetra",
		"memory_mixed_width_service.tetra",
		filepath.FromSlash("compiler_extension_pack/app/main.tetra"),
		"actor_self_mailbox_service.tetra",
		"task_group_cancel_after_spawn_service.tetra",
		"memory_derived_copy_service.tetra",
		filepath.FromSlash("compiler_protocol_extension_pack/app/main.tetra"),
		"actor_typed_chain_service.tetra",
		"task_group_multi_cancel_service.tetra",
		"memory_derived_ptr_table_service.tetra",
		filepath.FromSlash("compiler_generic_function_pack/app/main.tetra"),
		"actor_self_typed_mailbox_service.tetra",
		"actor_task_bridge_service.tetra",
		"memory_aggregate_ptr_service.tetra",
		"compiler_generic_extension_local_service.tetra",
		"actor_typed_task_bridge_service.tetra",
		"task_group_actor_fanout_service.tetra",
		"memory_optional_ptr_service.tetra",
		"compiler_callable_generic_route_service.tetra",
		"task_actor_roundtrip_service.tetra",
		"actor_typed_task_group_service.tetra",
		"memory_function_ptr_service.tetra",
		"task_typed_actor_roundtrip_service.tetra",
		"actor_task_select_service.tetra",
		"compiler_generic_optional_route_service.tetra",
		"memory_global_state_service.tetra",
		"actor_typed_task_error_bridge_service.tetra",
		"actor_task_cancel_select_service.tetra",
		filepath.FromSlash("compiler_generic_optional_import_pack/app/main.tetra"),
		"memory_mutable_ptr_service.tetra",
		"memory_struct_offset_service.tetra",
		"actor_task_recovery_service.tetra",
		filepath.FromSlash("compiler_generic_nested_optional_pack/app/main.tetra"),
		"memory_function_offset_service.tetra",
		"memory_expression_offset_service.tetra",
		"actor_timer_task_matrix_service.tetra",
		filepath.FromSlash("compiler_generic_enum_import_pack/app/main.tetra"),
		"memory_task_result_offset_service.tetra",
		"memory_actor_message_offset_service.tetra",
		"memory_actor_recv_value_offset_service.tetra",
		"memory_actor_poll_value_offset_service.tetra",
		"memory_actor_tag_offset_service.tetra",
		filepath.FromSlash("compiler_actor_wait_memory_pack/app/main.tetra"),
		"memory_actor_recv_error_offset_service.tetra",
		"memory_actor_poll_error_offset_service.tetra",
		"memory_actor_recv_msg_error_offset_service.tetra",
		filepath.FromSlash("compiler_actor_error_memory_pack/app/main.tetra"),
		"actor_task_group_error_recovery_service.tetra",
		filepath.FromSlash("compiler_generic_struct_field_pack/app/main.tetra"),
		"memory_indexed_metadata_offset_service.tetra",
		"parallel_typed_task_payload_handle_service.tetra",
		"actor_typed_dual_mailbox_service.tetra",
		"task_group_nested_service.tetra",
		filepath.FromSlash("compiler_generic_optional_struct_pack/app/main.tetra"),
		"memory_direct_base_offset_service.tetra",
		"parallel_typed_task_wide_payload_service.tetra",
		"actor_typed_wide_payload_service.tetra",
		filepath.FromSlash("compiler_cross_module_runtime_pack/app/main.tetra"),
		"actor_typed_envelope_service.tetra",
		"parallel_time_window_service.tetra",
		"actor_state_status_service.tetra",
		"memory_inline_ptradd_window_service.tetra",
		"parallel_typed_task_struct_payload_service.tetra",
		"actor_typed_struct_payload_service.tetra",
		"memory_callable_ptr_base_service.tetra",
		"memory_callable_optional_ptr_service.tetra",
		"compiler_match_ptr_base_service.tetra",
		"memory_typed_error_ptr_base_service.tetra",
		"parallel_join_until_rejoin_service.tetra",
		"actor_task_result_window_service.tetra",
		"compiler_inout_return_service.tetra",
		"memory_dynamic_base_offset_service.tetra",
		"parallel_group_close_before_join_service.tetra",
		"parallel_group_cancel_after_join_service.tetra",
		filepath.FromSlash("parallel_cross_module_typed_task_pack/app/main.tetra"),
		"memory_struct_base_dynamic_service.tetra",
		"memory_enum_base_dynamic_service.tetra",
		"memory_typed_error_base_dynamic_service.tetra",
		"parallel_select_recovery_service.tetra",
		"compiler_pattern_binding_unique_service.tetra",
		"memory_base_dynamic_copy_service.tetra",
		"parallel_select_rejoin_service.tetra",
		"parallel_group_cancel_select_service.tetra",
		filepath.FromSlash("compiler_interface_jobs_pack/app/main.tetra"),
		"memory_zero_length_derived_helper_service.tetra",
		"parallel_group_spawn_after_cancel_service.tetra",
		"parallel_join_until_poll_service.tetra",
		filepath.FromSlash("compiler_interface_control_pack/app/main.tetra"),
		"memory_zero_length_base_helper_service.tetra",
		"parallel_yield_join_window_service.tetra",
		"parallel_group_status_roundtrip_service.tetra",
		"memory_group_status_direct_offset_service.tetra",
		"memory_group_current_status_offset_service.tetra",
		"parallel_group_cancel_close_direct_service.tetra",
		filepath.FromSlash("compiler_group_status_memory_pack/app/main.tetra"),
		filepath.FromSlash("compiler_import_alias_pack/app/main.tetra"),
		"memory_heap_u16_slice_service.tetra",
		"memory_heap_bool_flags_service.tetra",
		"parallel_actor_yield_mailbox_service.tetra",
		"parallel_group_current_cancel_status_service.tetra",
		filepath.FromSlash("compiler_cross_module_actor_pack/app/main.tetra"),
		"memory_heap_i32_bool_slice_service.tetra",
		"parallel_task_actor_deadline_service.tetra",
		filepath.FromSlash("compiler_actor_resource_pack/app/main.tetra"),
		"memory_heap_u8_slice_service.tetra",
		"parallel_typed_group_cancel_status_service.tetra",
		filepath.FromSlash("compiler_callable_return_pack/app/main.tetra"),
		filepath.FromSlash("compiler_callable_optional_ptr_pack/app/main.tetra"),
		filepath.FromSlash("compiler_async_interface_pack/app/main.tetra"),
		"memory_slice_optional_service.tetra",
		"memory_slice_enum_service.tetra",
		"parallel_task_result_box_service.tetra",
		"parallel_task_result_enum_service.tetra",
		"compiler_test_command_service.tetra",
		"parallel_task_test_command_service.tetra",
		"generic_typed_result_payload_service.tetra",
		"memory_slice_struct_loop_service.tetra",
		"memory_slice_generic_box_service.tetra",
		"parallel_task_result_optional_service.tetra",
		"parallel_nested_task_spawn_service.tetra",
		filepath.FromSlash("compiler_generic_slice_pack/app/main.tetra"),
		"memory_slice_for_loop_service.tetra",
		"memory_slice_inout_mutation_service.tetra",
		"parallel_task_handle_optional_join_service.tetra",
		filepath.FromSlash("compiler_optional_task_pack/app/main.tetra"),
		"memory_bool_for_loop_service.tetra",
		"memory_i32_for_loop_service.tetra",
		"parallel_actor_handle_optional_send_service.tetra",
		filepath.FromSlash("compiler_optional_actor_pack/app/main.tetra"),
		"memory_u16_for_loop_service.tetra",
		"parallel_group_optional_close_service.tetra",
		"parallel_group_optional_cancel_service.tetra",
		filepath.FromSlash("compiler_optional_group_pack/app/main.tetra"),
		"memory_bool_inout_toggle_service.tetra",
		"memory_i32_inout_fill_service.tetra",
		"parallel_group_optional_match_close_service.tetra",
		filepath.FromSlash("compiler_optional_group_match_pack/app/main.tetra"),
		"parallel_group_struct_spawn_service.tetra",
		"parallel_group_enum_spawn_service.tetra",
		"parallel_group_typed_struct_spawn_service.tetra",
		"parallel_group_typed_enum_spawn_service.tetra",
		"memory_u16_inout_stride_service.tetra",
		filepath.FromSlash("compiler_group_aggregate_pack/app/main.tetra"),
		"parallel_group_alias_spawn_service.tetra",
		"parallel_group_generic_box_spawn_service.tetra",
		"memory_optional_generic_u16_box_service.tetra",
		filepath.FromSlash("compiler_group_generic_pack/app/main.tetra"),
		"parallel_task_alias_join_service.tetra",
		"parallel_task_generic_box_join_service.tetra",
		"parallel_task_optional_struct_box_join_service.tetra",
		"parallel_task_optional_generic_box_join_service.tetra",
		"memory_optional_generic_bool_box_service.tetra",
		filepath.FromSlash("compiler_task_generic_pack/app/main.tetra"),
		"parallel_actor_alias_send_service.tetra",
		"parallel_actor_generic_box_send_service.tetra",
		"parallel_actor_optional_struct_box_send_service.tetra",
		"parallel_actor_optional_generic_box_send_service.tetra",
		"memory_optional_generic_i32_box_service.tetra",
		filepath.FromSlash("compiler_actor_generic_pack/app/main.tetra"),
		"memory_island_alias_region_service.tetra",
		"memory_island_generic_box_region_service.tetra",
		"memory_island_optional_struct_box_service.tetra",
		"memory_island_optional_generic_box_service.tetra",
		filepath.FromSlash("compiler_island_generic_pack/app/main.tetra"),
		"memory_ptr_alias_base_service.tetra",
		"memory_ptr_generic_identity_base_service.tetra",
		filepath.FromSlash("compiler_ptr_generic_pack/app/main.tetra"),
		"memory_task_result_optional_offset_service.tetra",
		"parallel_task_result_generic_box_service.tetra",
		filepath.FromSlash("compiler_task_result_generic_pack/app/main.tetra"),
		filepath.FromSlash("compiler_async_optional_pack/app/main.tetra"),
		filepath.FromSlash("compiler_async_memory_pack/app/main.tetra"),
		filepath.FromSlash("compiler_async_resource_pack/app/main.tetra"),
		filepath.FromSlash("compiler_async_throw_resource_pack/app/main.tetra"),
		filepath.FromSlash("compiler_async_resource_wrapper_pack/app/main.tetra"),
		filepath.FromSlash("compiler_async_throw_resource_wrapper_pack/app/main.tetra"),
		filepath.FromSlash("compiler_async_generic_resource_pack/app/main.tetra"),
		filepath.FromSlash("compiler_async_throw_generic_resource_pack/app/main.tetra"),
		filepath.FromSlash("compiler_async_throw_memory_ptr_pack/app/main.tetra"),
		filepath.FromSlash("compiler_async_optional_memory_ptr_pack/app/main.tetra"),
		filepath.FromSlash("compiler_async_generic_memory_ptr_pack/app/main.tetra"),
		filepath.FromSlash("compiler_async_enum_memory_ptr_pack/app/main.tetra"),
		filepath.FromSlash("compiler_async_slice_memory_pack/app/main.tetra"),
		filepath.FromSlash("compiler_async_slice_lane_memory_pack/app/main.tetra"),
		filepath.FromSlash("compiler_async_slice_shape_pack/app/main.tetra"),
		filepath.FromSlash("compiler_async_string_memory_pack/app/main.tetra"),
		filepath.FromSlash("compiler_async_optional_generic_string_pack/app/main.tetra"),
		"memory_ptr_generic_optional_field_service.tetra",
		"parallel_task_result_generic_optional_field_service.tetra",
		filepath.FromSlash("compiler_generic_optional_field_pack/app/main.tetra"),
		"memory_ptr_generic_optional_call_service.tetra",
		"memory_optional_ptr_inout_return_service.tetra",
		filepath.FromSlash("compiler_ptr_optional_generic_call_pack/app/main.tetra"),
		"parallel_actor_optional_alias_send_service.tetra",
		"parallel_task_optional_alias_join_service.tetra",
		"parallel_group_optional_alias_close_service.tetra",
		filepath.FromSlash("compiler_optional_alias_resource_pack/app/main.tetra"),
		"parallel_actor_optional_enum_send_service.tetra",
		"parallel_task_optional_enum_join_service.tetra",
		"parallel_group_optional_enum_close_service.tetra",
		"memory_task_result_optional_enum_offset_service.tetra",
		filepath.FromSlash("compiler_optional_enum_resource_pack/app/main.tetra"),
		"parallel_actor_typed_optional_alias_send_service.tetra",
		"parallel_typed_group_optional_alias_spawn_service.tetra",
		filepath.FromSlash("compiler_typed_optional_alias_resource_pack/app/main.tetra"),
		"parallel_typed_task_match_catch_service.tetra",
		"memory_typed_task_error_offset_service.tetra",
		filepath.FromSlash("compiler_typed_task_match_pack/app/main.tetra"),
		"memory_typed_task_error_struct_offset_service.tetra",
		"memory_typed_task_error_nested_enum_offset_service.tetra",
		"memory_typed_task_error_optional_offset_service.tetra",
		"memory_typed_task_error_guarded_offset_service.tetra",
		filepath.FromSlash("compiler_typed_error_payload_memory_pack/app/main.tetra"),
		"parallel_defer_group_close_service.tetra",
		"memory_defer_store_service.tetra",
		"parallel_defer_group_cancel_checkpoint_service.tetra",
		"memory_defer_task_result_offset_service.tetra",
		filepath.FromSlash("compiler_defer_cleanup_pack/app/main.tetra"),
		"memory_defer_throw_base_store_service.tetra",
		"memory_defer_return_base_store_service.tetra",
		"parallel_typed_task_defer_actor_reply_service.tetra",
		filepath.FromSlash("compiler_defer_unwind_pack/app/main.tetra"),
		"memory_join_until_result_offset_service.tetra",
		"memory_poll_result_offset_service.tetra",
		"memory_select_result_offset_service.tetra",
		filepath.FromSlash("compiler_task_wait_memory_pack/app/main.tetra"),
		"memory_join_until_error_offset_service.tetra",
		"memory_poll_error_offset_service.tetra",
		"memory_select_error_offset_service.tetra",
		filepath.FromSlash("compiler_task_wait_error_memory_pack/app/main.tetra"),
		"memory_typed_error_optional_ptr_base_service.tetra",
		"memory_typed_error_optional_ptr_dynamic_service.tetra",
		filepath.FromSlash("compiler_typed_error_optional_ptr_pack/app/main.tetra"),
		"memory_actor_typed_payload_offset_service.tetra",
		"memory_actor_typed_struct_payload_offset_service.tetra",
		filepath.FromSlash("compiler_typed_actor_payload_memory_pack/app/main.tetra"),
		"memory_actor_typed_enum_payload_offset_service.tetra",
		"memory_actor_typed_enum_struct_payload_offset_service.tetra",
		filepath.FromSlash("compiler_typed_actor_enum_payload_memory_pack/app/main.tetra"),
		"backend_http_pipeline_gateway_service.tetra",
		"backend_postgres_prepared_pipeline_service.tetra",
		"backend_net_epoll_lifecycle_service.tetra",
		"backend_net_epoll_event_bounds_guard_service.tetra",
		"backend_net_port_bounds_guard_service.tetra",
		"backend_postgres_result_guard_service.tetra",
		"backend_postgres_session_state_service.tetra",
		"backend_postgres_cstring_bounds_guard_service.tetra",
		"backend_postgres_cstring_nul_guard_service.tetra",
		"backend_postgres_data_row_length_guard_service.tetra",
		"backend_postgres_ascii_i32_bounds_guard_service.tetra",
		"backend_postgres_ascii_i32_min_guard_service.tetra",
		"backend_postgres_command_tag_bounds_guard_service.tetra",
		"backend_postgres_command_tag_overflow_guard_service.tetra",
		"backend_postgres_command_tag_trailing_guard_service.tetra",
		"backend_postgres_parse_count_guard_service.tetra",
		"backend_postgres_parser_short_guard_service.tetra",
		"backend_postgres_row_description_bounds_guard_service.tetra",
		"backend_postgres_data_row_bounds_guard_service.tetra",
		"backend_postgres_data_row_truncated_value_guard_service.tetra",
		"backend_postgres_frame_header_bounds_guard_service.tetra",
		"backend_postgres_frame_signed_length_guard_service.tetra",
		"backend_postgres_frame_total_overflow_guard_service.tetra",
		"backend_postgres_frame_short_guard_service.tetra",
		"backend_postgres_frame_writer_short_guard_service.tetra",
		"backend_postgres_ready_status_bounds_guard_service.tetra",
		"backend_postgres_ready_status_short_guard_service.tetra",
		"backend_postgres_column_count_bounds_guard_service.tetra",
		"backend_postgres_column_count_signed_guard_service.tetra",
		"backend_postgres_read_bounds_guard_service.tetra",
		"backend_postgres_read_short_guard_service.tetra",
		"backend_postgres_high_bit_read_guard_service.tetra",
		"backend_postgres_write_bounds_guard_service.tetra",
		"backend_postgres_signed_write_guard_service.tetra",
		"backend_postgres_write_short_guard_service.tetra",
		"backend_postgres_text_write_bounds_guard_service.tetra",
		"backend_postgres_text_write_short_guard_service.tetra",
		"backend_postgres_ascii_i32_overflow_guard_service.tetra",
		"backend_http_response_guard_service.tetra",
		"backend_http_response_writer_short_guard_service.tetra",
		"backend_http_negative_content_length_guard_service.tetra",
		"backend_http_status_code_guard_service.tetra",
		"backend_http_header_injection_guard_service.tetra",
		"backend_http_header_control_guard_service.tetra",
		"backend_http_writer_bounds_guard_service.tetra",
		"backend_http_writer_short_guard_service.tetra",
		"backend_http_status_matrix_service.tetra",
		"backend_http_json_i32_min_guard_service.tetra",
		"backend_http_header_whitespace_service.tetra",
		"backend_http_connection_list_service.tetra",
		"backend_http_connection_scope_service.tetra",
		"backend_http_connection_token_boundary_service.tetra",
		"backend_http_version_scope_service.tetra",
		"backend_http_request_target_guard_service.tetra",
		"backend_http_request_target_char_guard_service.tetra",
		"backend_http_request_line_token_guard_service.tetra",
		"backend_http_request_crlf_guard_service.tetra",
		"backend_http_request_short_guard_service.tetra",
		"backend_http_keep_alive_target_guard_service.tetra",
		"backend_http_connection_body_scope_service.tetra",
		"backend_http_keep_alive_method_guard_service.tetra",
		"backend_json_escape_guard_service.tetra",
		"backend_json_control_matrix_service.tetra",
		"backend_json_hex_digit_guard_service.tetra",
		"backend_json_writer_bounds_guard_service.tetra",
		"backend_json_writer_short_guard_service.tetra",
		"backend_network_policy_guard_service.tetra",
		"backend_network_backoff_overflow_guard_service.tetra",
		"backend_crypto_serialization_guard_service.tetra",
		"backend_crypto_mix_min_guard_service.tetra",
		"backend_filesystem_path_policy_service.tetra",
		"backend_filesystem_nul_exists_guard_service.tetra",
		"backend_time_collection_window_service.tetra",
		"backend_time_overflow_guard_service.tetra",
		"backend_time_negative_base_delta_guard_service.tetra",
		"backend_math_testing_decision_service.tetra",
		"backend_slice_capability_window_service.tetra",
		"backend_memory_io_buffer_service.tetra",
		"backend_sync_async_status_service.tetra",
		"backend_experimental_route_policy_service.tetra",
		"backend_experimental_buffer_mirror_service.tetra",
		filepath.FromSlash("backend_modular_web_stack_pack/app/main.tetra"),
	} {
		stdout, exitCode := buildAndRunFile(t, filepath.Join(root, "examples", "microservices", name))
		if stdout != "" {
			t.Fatalf("%s stdout mismatch: %q", name, stdout)
		}
		if exitCode != 0 {
			t.Fatalf("%s exit code mismatch: %d", name, exitCode)
		}
	}
	for _, name := range []string{
		filepath.FromSlash("backend_modular_web_stack_pack/app/main.tetra"),
		filepath.FromSlash("compiler_parallel_jobs_pack/app/main.tetra"),
	} {
		stdout, exitCode := buildAndRunFileWithOptions(t, filepath.Join(root, "examples", "microservices", name), BuildOptions{Jobs: 4})
		if stdout != "" {
			t.Fatalf("%s stdout mismatch: %q", name, stdout)
		}
		if exitCode != 0 {
			t.Fatalf("%s exit code mismatch: %d", name, exitCode)
		}
	}
	for _, name := range []string{
		filepath.FromSlash("backend_modular_web_stack_pack/app/main.tetra"),
		filepath.FromSlash("compiler_interface_jobs_pack/app/main.tetra"),
		filepath.FromSlash("compiler_interface_control_pack/app/main.tetra"),
		filepath.FromSlash("compiler_import_alias_pack/app/main.tetra"),
		filepath.FromSlash("compiler_cross_module_actor_pack/app/main.tetra"),
		filepath.FromSlash("compiler_actor_resource_pack/app/main.tetra"),
		filepath.FromSlash("compiler_callable_return_pack/app/main.tetra"),
		filepath.FromSlash("compiler_callable_optional_ptr_pack/app/main.tetra"),
		filepath.FromSlash("compiler_async_interface_pack/app/main.tetra"),
		filepath.FromSlash("compiler_generic_slice_pack/app/main.tetra"),
		filepath.FromSlash("compiler_optional_task_pack/app/main.tetra"),
		filepath.FromSlash("compiler_optional_actor_pack/app/main.tetra"),
		filepath.FromSlash("compiler_optional_group_pack/app/main.tetra"),
		filepath.FromSlash("compiler_optional_group_match_pack/app/main.tetra"),
		filepath.FromSlash("compiler_group_aggregate_pack/app/main.tetra"),
		filepath.FromSlash("compiler_group_generic_pack/app/main.tetra"),
		filepath.FromSlash("compiler_task_generic_pack/app/main.tetra"),
		filepath.FromSlash("compiler_actor_generic_pack/app/main.tetra"),
		filepath.FromSlash("compiler_island_generic_pack/app/main.tetra"),
		filepath.FromSlash("compiler_ptr_generic_pack/app/main.tetra"),
		filepath.FromSlash("compiler_task_result_generic_pack/app/main.tetra"),
		filepath.FromSlash("compiler_async_optional_pack/app/main.tetra"),
		filepath.FromSlash("compiler_async_memory_pack/app/main.tetra"),
		filepath.FromSlash("compiler_async_resource_pack/app/main.tetra"),
		filepath.FromSlash("compiler_async_throw_resource_pack/app/main.tetra"),
		filepath.FromSlash("compiler_async_resource_wrapper_pack/app/main.tetra"),
		filepath.FromSlash("compiler_async_throw_resource_wrapper_pack/app/main.tetra"),
		filepath.FromSlash("compiler_async_generic_resource_pack/app/main.tetra"),
		filepath.FromSlash("compiler_async_throw_generic_resource_pack/app/main.tetra"),
		filepath.FromSlash("compiler_async_throw_memory_ptr_pack/app/main.tetra"),
		filepath.FromSlash("compiler_async_optional_memory_ptr_pack/app/main.tetra"),
		filepath.FromSlash("compiler_async_generic_memory_ptr_pack/app/main.tetra"),
		filepath.FromSlash("compiler_async_enum_memory_ptr_pack/app/main.tetra"),
		filepath.FromSlash("compiler_async_slice_memory_pack/app/main.tetra"),
		filepath.FromSlash("compiler_async_slice_lane_memory_pack/app/main.tetra"),
		filepath.FromSlash("compiler_async_slice_shape_pack/app/main.tetra"),
		filepath.FromSlash("compiler_async_string_memory_pack/app/main.tetra"),
		filepath.FromSlash("compiler_async_optional_generic_string_pack/app/main.tetra"),
		filepath.FromSlash("compiler_generic_optional_field_pack/app/main.tetra"),
		filepath.FromSlash("compiler_ptr_optional_generic_call_pack/app/main.tetra"),
		filepath.FromSlash("compiler_optional_alias_resource_pack/app/main.tetra"),
		filepath.FromSlash("compiler_optional_enum_resource_pack/app/main.tetra"),
		filepath.FromSlash("compiler_typed_optional_alias_resource_pack/app/main.tetra"),
		filepath.FromSlash("compiler_typed_task_match_pack/app/main.tetra"),
		filepath.FromSlash("compiler_typed_error_payload_memory_pack/app/main.tetra"),
		filepath.FromSlash("compiler_defer_cleanup_pack/app/main.tetra"),
		filepath.FromSlash("compiler_defer_unwind_pack/app/main.tetra"),
		filepath.FromSlash("compiler_task_wait_memory_pack/app/main.tetra"),
		filepath.FromSlash("compiler_task_wait_error_memory_pack/app/main.tetra"),
		filepath.FromSlash("compiler_actor_wait_memory_pack/app/main.tetra"),
		filepath.FromSlash("compiler_actor_error_memory_pack/app/main.tetra"),
		filepath.FromSlash("compiler_group_status_memory_pack/app/main.tetra"),
		filepath.FromSlash("compiler_typed_error_optional_ptr_pack/app/main.tetra"),
		filepath.FromSlash("compiler_typed_actor_payload_memory_pack/app/main.tetra"),
		filepath.FromSlash("compiler_typed_actor_enum_payload_memory_pack/app/main.tetra"),
	} {
		outPath := filepath.Join(t.TempDir(), "interface-only")
		if _, err := BuildFileWithStatsOpt(filepath.Join(root, "examples", "microservices", name), outPath, "linux-x64", BuildOptions{Jobs: 4, InterfaceOnly: true}); err != nil {
			t.Fatalf("%s interface-only build: %v", name, err)
		}
	}
	for _, name := range []string{
		"parallel_selfhost_deadline_service.tetra",
	} {
		stdout, exitCode := buildAndRunFileWithOptions(t, filepath.Join(root, "examples", "microservices", name), BuildOptions{Runtime: RuntimeSelfHost})
		if stdout != "" {
			t.Fatalf("%s stdout mismatch: %q", name, stdout)
		}
		if exitCode != 0 {
			t.Fatalf("%s exit code mismatch: %d", name, exitCode)
		}
	}

	raw, err := os.ReadFile(filepath.Join(root, "Tetra_BUGS.md"))
	if err != nil {
		t.Fatalf("read Tetra_BUGS.md: %v", err)
	}
	text := string(raw)
	for _, want := range []string{
		"# Tetra Bugs",
		"Confirmed Language Bugs",
		"TETRA-BUG-0001",
		"cannot infer generic argument",
		"TETRA-BUG-0002",
		"unknown function 'Unit.score'",
		"TETRA-BUG-0003",
		"count mismatch: expected 1, got 2",
		"TETRA-BUG-0004",
		"Formatter drops function-typed local annotations",
		"TETRA-BUG-0005",
		"unknown function 'Router.run'",
		"TETRA-BUG-0006",
		"global var requires an explicit type annotation",
		"TETRA-BUG-0007",
		"Derived pointer arithmetic loses allocation provenance",
		"TETRA-BUG-0008",
		"Formatter rewrites mutable actor state fields as immutable",
		"TETRA-BUG-0009",
		"Blocking tagged receive fails in dual actor fan-in",
		"TETRA-BUG-0010",
		"Blocking value receive fails in dual actor fan-in",
		"TETRA-BUG-0011",
		"Struct constructors do not wrap scalar values into optional fields",
		"TETRA-BUG-0012",
		"Enum constructors do not wrap scalar values into optional payloads",
		"TETRA-BUG-0013",
		"Derived pointer loop arithmetic fails after pointer parameters",
		"TETRA-BUG-0014",
		"Formatter drops generic protocol requirement type parameters",
		"TETRA-BUG-0015",
		"Imported generic extension static calls do not monomorphize",
		"TETRA-BUG-0016",
		"Match case payload bindings leak across sibling cases",
		"TETRA-BUG-0017",
		"Stored derived pointers lose loadable memory provenance",
		"TETRA-BUG-0018",
		"Struct pointer fields lose memory provenance",
		"TETRA-BUG-0019",
		"Enum derived pointer payloads lose memory provenance",
		"TETRA-BUG-0020",
		"Generic identity over function-typed locals lowers to an unknown fn type",
		"TETRA-BUG-0021",
		"Optional derived pointer payloads lose memory provenance",
		"TETRA-BUG-0022",
		"Generic callback parameters do not accept compatible function symbols",
		"TETRA-BUG-0023",
		"Function returns of derived pointers lose memory provenance",
		"Function-typed callable returns of derived pointers hit the same guard",
		"TETRA-BUG-0024",
		"Global pointer variables lose memory provenance",
		"TETRA-BUG-0025",
		"Global integer offsets break raw pointer arithmetic provenance",
		"TETRA-BUG-0026",
		"Mutable local derived pointer variables lose memory provenance",
		"TETRA-BUG-0027",
		"Struct field offsets break raw pointer arithmetic provenance",
		"TETRA-BUG-0028",
		"Function-call offset operands break raw pointer arithmetic provenance",
		"TETRA-BUG-0029",
		"Expression offset operands break raw pointer arithmetic provenance",
		"TETRA-BUG-0030",
		"Runtime result and message fields break raw pointer arithmetic provenance",
		"TETRA-BUG-0031",
		"Enum payloads reject generic struct instantiations",
		"TETRA-BUG-0032",
		"Indexed and metadata offsets break raw pointer arithmetic provenance",
		"TETRA-BUG-0033",
		"Payload-typed task handles reject explicit task.i32 annotations",
		"TETRA-BUG-0034",
		"Direct pointer base expressions break raw pointer arithmetic provenance",
		"TETRA-BUG-0035",
		"Typed actor receives silently reinterpret mismatched enum message types",
		"TETRA-BUG-0036",
		"Typed error payloads of derived pointers lose memory provenance",
		"TETRA-BUG-0037",
		"Global fixed-array element writes do not round-trip at runtime",
		"TETRA-BUG-0038",
		"Scalar inout writes do not propagate back to caller locals",
		"TETRA-BUG-0039",
		"Dynamic ptr_add offsets from derived pointer locals lose memory provenance",
		"TETRA-BUG-0040",
		"Explicit selfhost task-group builds fail with raw missing ABI symbol",
		"TETRA-BUG-0041",
		"Scoped if-let and catch payload bindings remain reserved after scope exit",
		"TETRA-BUG-0042",
		"Stdlib byte helpers fail on valid derived memory windows",
		"TETRA-BUG-0043",
		"Formatter drops public visibility modifiers from declarations",
		"TETRA-BUG-0044",
		"Formatter corrupts selective import declarations",
		"TETRA-BUG-0045",
		"Spawning through an optional task-group payload returns the wrong worker value",
		"TETRA-BUG-0046",
		"Generic identity over actor/task/island resources loses usable provenance",
		"TETRA-BUG-0047",
		"Island parameters cannot be returned inside aggregate constructors",
		"TETRA-BUG-0048",
		"Function-typed local, field, and payload calls returning optionals fail as unknown functions",
		"TETRA-BUG-0049",
		"Generic inference fails on generic struct field selections",
		"TETRA-BUG-0050",
		"Task spawns inside match expressions miss required runtime symbols",
		"TETRA-BUG-0051",
		"Formatter corrupts nested catch cases inside match expression arms",
		"TETRA-BUG-0052",
		"Formatter corrupts nested match cases inside catch expression arms",
		"TETRA-BUG-0053",
		"Awaited optional resource locals lose provenance",
		"TETRA-BUG-0054",
		"Awaited resource aggregate locals lose provenance",
		"TETRA-BUG-0055",
		"Direct awaited pointer returns ignore await and try",
		"TETRA-BUG-0056",
		"Go workspace validation fails the SCRAM local benchmark package",
		"tetra_language/compiler@v0.0.0: malformed module path",
		"TETRA-BUG-0057",
		"Zero-length heap slice constructors call mmap with length 0",
		"TETRA-BUG-0058",
		"Explicit source-file CLI inputs inherit capsule source roots",
		"module 'examples.projects.dogfood_cli.src.main' must be in",
		"TETRA-BUG-0059",
		"HTTP Connection-close detection is case-sensitive",
		"service exited with status `22`",
		"TETRA-BUG-0060",
		"HTTP Connection-close detection rejects optional whitespace",
		"service exited with status `3`",
		"TETRA-BUG-0061",
		"HTTP Connection-close detection ignores close after comma",
		"service exited with status `4`",
		"TETRA-BUG-0062",
		"HTTP Connection-close detection matches suffix headers",
		"service exited with status `1`",
		"TETRA-BUG-0063",
		"HTTP Connection-close detection accepts close token prefixes",
		"Connection: closex",
		"TETRA-BUG-0064",
		"HTTP/1.1 detection scans beyond the request line",
		"X-Debug: HTTP/1.1",
		"TETRA-BUG-0065",
		"HTTP route helper classifies empty request targets as not found",
		"GET  /json HTTP/1.1",
		"TETRA-BUG-0066",
		"HTTP/1.1 detection accepts extra request-line tokens",
		"GET /json debug HTTP/1.1",
		"TETRA-BUG-0067",
		"HTTP keep-alive detection accepts malformed request targets",
		"GET noslash HTTP/1.1",
		"TETRA-BUG-0068",
		"HTTP Connection-close detection scans request bodies",
		"Connection: close` in the request body",
		"TETRA-BUG-0069",
		"HTTP keep-alive detection accepts malformed method tokens",
		"GE:T /json HTTP/1.1",
		"TETRA-BUG-0070",
		"JSON lowercase hex digit helper returns non-hex bytes out of range",
		"hex_digit_lower(-1)",
		"TETRA-BUG-0071",
		"Time duration helpers wrap positive overflow",
		"millis_from_seconds(2147484)",
		"TETRA-BUG-0072",
		"PostgreSQL C-string scan traps on negative start",
		"cstring_end_at(payload, -1, 6)",
		"TETRA-BUG-0073",
		"PostgreSQL signed DataRow length leaks malformed negative values",
		"0xfffffffe",
		"TETRA-BUG-0074",
		"PostgreSQL ASCII i32 parser traps on negative start",
		"parse_ascii_i32_at(bytes, -1, 2)",
		"TETRA-BUG-0075",
		"PostgreSQL CommandComplete parser traps on negative start",
		"command_complete_affected_rows(update_tag, -1, 4)",
		"TETRA-BUG-0076",
		"PostgreSQL RowDescription type-OID scan traps on negative start",
		"row_description_type_oid_at(desc, -1, i, 0)",
		"TETRA-BUG-0077",
		"PostgreSQL DataRow value helpers trap on negative start",
		"data_row_value_len_at(row, -1, 0)",
		"TETRA-BUG-0078",
		"PostgreSQL frame header readers trap on negative start",
		"frame_type_at(frame, -1)",
		"TETRA-BUG-0079",
		"PostgreSQL ReadyForQuery status reader traps on negative start",
		"ready_for_query_status(states, -1)",
		"TETRA-BUG-0080",
		"PostgreSQL column-count readers trap on negative start",
		"row_description_column_count(desc, -1)",
		"TETRA-BUG-0081",
		"PostgreSQL big-endian readers trap on negative start",
		"read_i32_be(bytes, -1)",
		"TETRA-BUG-0082",
		"PostgreSQL big-endian writers trap on negative start",
		"write_i32_be_at(bytes, -1, 1)",
		"TETRA-BUG-0083",
		"PostgreSQL text writers trap on negative start",
		"write_ascii_at(bytes, -1, \"Z\")",
		"TETRA-BUG-0084",
		"HTTP writer helpers trap on negative start",
		"write_ascii_at(out, -1, \"Z\")",
		"TETRA-BUG-0085",
		"JSON writers trap on negative start",
		"write_json_string_at(buf, -1, \"Z\")",
		"TETRA-BUG-0086",
		"HTTP/JSON i32 digit helpers collapse minimum value",
		"http.digits_i32(min_i32)",
		"TETRA-BUG-0087",
		"Crypto mix_seed overflows normalizing i32 minimum",
		"crypto.mix_seed(-65075262, -2)",
		"TETRA-BUG-0088",
		"Networking retry backoff overflows before cap",
		"retry_backoff_ms(1, 1073741824, 2147483647)",
		"TETRA-BUG-0089",
		"Epoll event extractors trap on short buffers",
		"net.epoll_event_fd(...)",
		"TETRA-BUG-0090",
		"PostgreSQL frame header readers trap on short buffers",
		"frame_length_at(...)",
		"TETRA-BUG-0091",
		"PostgreSQL big-endian readers trap on short buffers",
		"read_i32_be(...)",
		"TETRA-BUG-0092",
		"PostgreSQL big-endian writers trap on short buffers",
		"write_i32_be_at(...)",
		"TETRA-BUG-0093",
		"PostgreSQL text writers trap on short buffers",
		"write_cstring_pair_at(...)",
		"TETRA-BUG-0094",
		"HTTP writer helpers trap on short buffers",
		"write_header_at(...)",
		"TETRA-BUG-0095",
		"JSON writers trap on short buffers",
		"write_message_object_at(...)",
		"TETRA-BUG-0096",
		"PostgreSQL frame writers trap on short buffers",
		"write_startup_message(...)",
		"TETRA-BUG-0097",
		"PostgreSQL bounded parsers trap on short buffers",
		"parse_ascii_i32_at(...)",
		"TETRA-BUG-0098",
		"PostgreSQL ReadyForQuery status reader traps on short buffers",
		"ready_for_query_status(...)",
		"TETRA-BUG-0099",
		"HTTP request scanners trap on short buffers",
		"request_head_len_bytes_at(...)",
		"TETRA-BUG-0100",
		"HTTP response writers trap or partially write on short buffers",
		"write_response_head(...)",
		"TETRA-BUG-0101",
		"PostgreSQL big-endian writers encode negative values incorrectly",
		"write_i32_be_at(...)",
		"TETRA-BUG-0102",
		"PostgreSQL frame length reader leaks malformed signed lengths",
		"frame_length_at(...)",
		"TETRA-BUG-0103",
		"PostgreSQL big-endian reader leaks high-bit i32 values",
		"read_i32_be(...)",
		"TETRA-BUG-0104",
		"Time duration addition clamps negative base before applying positive delta",
		"add_duration_ms(-5, 10)",
		"TETRA-BUG-0105",
		"HTTP request-line scanner accepts LF-only or bare-CR HTTP/1.1 terminators",
		"HTTP/1.1\\n",
		"TETRA-BUG-0106",
		"filesystem.exists accepts embedded-NUL paths and checks only the prefix",
		"filesystem.exists",
		"TETRA-BUG-0107",
		"HTTP request-target scanners accept control bytes as route misses or keep-alive requests",
		"GET /json\\t HTTP/1.1",
		"TETRA-BUG-0108",
		"PostgreSQL ASCII i32 parser wraps out-of-range values",
		"parse_ascii_i32_at(\"2147483648\")",
		"TETRA-BUG-0109",
		"PostgreSQL CommandComplete affected-row parser wraps out-of-range values",
		"command_complete_affected_rows(\"UPDATE 2147483648\")",
		"TETRA-BUG-0110",
		"PostgreSQL CommandComplete parser returns non-trailing digit runs",
		"command_complete_affected_rows(\"UPDATE 12 rows\")",
		"TETRA-BUG-0111",
		"PostgreSQL DataRow helpers accept truncated positive value windows",
		"data_row_value_len_at(row, 0, 0)",
		"TETRA-BUG-0112",
		"PostgreSQL frame total length overflows at max signed length",
		"frame_total_len_at(frame, 0)",
		"TETRA-BUG-0113",
		"HTTP response writer accepts negative Content-Length",
		"response_head_len(200, \"OK\", \"Tetra\", date, \"text/plain\", -1, true)",
		"TETRA-BUG-0114",
		"HTTP response writer accepts non-three-digit status codes",
		"response_head_len(99, \"Bad\", \"Tetra\", date, \"text/plain\", 0, true)",
		"TETRA-BUG-0115",
		"HTTP header writers accept CR/LF header injection",
		"write_header_at(header, 0, \"X\\rBad\", \"ok\")",
		"TETRA-BUG-0116",
		"HTTP header writers accept non-HTAB control bytes",
		"ASCII 0x1f",
		"TETRA-BUG-0117",
		"PostgreSQL Parse writer wraps parameter counts above signed i16 range",
		"parse_payload_len(\"\", \"SELECT 1\", many)",
		"TETRA-BUG-0118",
		"TCP loopback bind accepts out-of-range ports",
		"bind_tcp4_loopback(fd, 65536, io_cap)",
		"TETRA-BUG-0119",
		"PostgreSQL column-count readers accept high-bit signed counts",
		"row_description_column_count(malformed, 0)",
		"TETRA-BUG-0120",
		"PostgreSQL C-string writers accept embedded NUL fields",
		"write_cstring_at(bytes, 0, bad)",
		"Microservice Bug-Hunt Runs",
		"Added backend HTTP/JSON pipeline and PostgreSQL prepared wire-frame microservice examples;",
		"Added backend net epoll lifecycle and PostgreSQL result guard microservice examples;",
		"Added backend HTTP response guard and JSON escape guard microservice examples;",
		"Added backend networking policy and crypto/serialization guard microservice examples;",
		"Added backend filesystem path-policy and time/collection window microservice examples;",
		"Added backend math/testing decision and slice/capability window microservice examples;",
		"Added backend memory/io buffer and sync/async status microservice examples;",
		"Added backend experimental route-policy and buffer mirror microservice examples;",
		"Added backend modular web-stack pack microservice example;",
		"Added backend capsule source-root microservice project;",
		"Added backend PostgreSQL session-state wire microservice example;",
		"Added backend HTTP status/header matrix microservice example;",
		"Added backend JSON control-character matrix microservice example;",
		"Added backend HTTP header-whitespace microservice example;",
		"Added backend HTTP Connection token-list microservice example;",
		"Added backend HTTP Connection header-scope microservice example;",
		"Added backend HTTP Connection token-boundary microservice example;",
		"Added backend HTTP request-version scope microservice example;",
		"Added backend HTTP request-target guard microservice example;",
		"Added backend HTTP request-line token guard microservice example;",
		"Added backend HTTP keep-alive request-target guard microservice example;",
		"Added backend HTTP Connection header/body scope microservice example;",
		"Added backend HTTP keep-alive method-token guard microservice example;",
		"Added backend JSON hex-digit guard microservice example;",
		"Added backend time overflow guard microservice example;",
		"Added backend PostgreSQL C-string bounds guard microservice example;",
		"Added backend PostgreSQL DataRow signed-length guard microservice example;",
		"Added backend PostgreSQL ASCII i32 bounds guard microservice example;",
		"Added backend PostgreSQL CommandComplete bounds guard microservice example;",
		"Added backend PostgreSQL RowDescription bounds guard microservice example;",
		"Added backend PostgreSQL DataRow bounds guard microservice example;",
		"Added backend PostgreSQL frame-header bounds guard microservice example;",
		"Added backend PostgreSQL ReadyForQuery status bounds guard microservice example;",
		"Added backend PostgreSQL column-count bounds guard microservice example;",
		"Added backend PostgreSQL big-endian reader bounds guard microservice example;",
		"Added backend PostgreSQL big-endian writer bounds guard microservice example;",
		"Added backend PostgreSQL text writer bounds guard microservice example;",
		"Added backend HTTP writer bounds guard microservice example;",
		"Added backend JSON writer bounds guard microservice example;",
		"Added backend HTTP/JSON i32 minimum guard microservice example;",
		"Added backend crypto mix i32 minimum guard microservice example;",
		"Added backend networking backoff overflow guard microservice example;",
		"Added backend net epoll event bounds guard microservice example;",
		"Added backend PostgreSQL short frame-header guard microservice example;",
		"Added backend PostgreSQL big-endian reader short-buffer guard microservice example;",
		"Added backend PostgreSQL big-endian writer short-buffer guard microservice example;",
		"Added backend PostgreSQL text writer short-buffer guard microservice example;",
		"Added backend HTTP writer short-buffer guard microservice example;",
		"Added backend JSON writer short-buffer guard microservice example;",
		"Added backend PostgreSQL frame writer short-buffer guard microservice example;",
		"Added backend PostgreSQL bounded parser short-buffer guard microservice example;",
		"Added backend PostgreSQL ReadyForQuery status short-buffer guard microservice example;",
		"Added backend HTTP request short-buffer guard microservice example;",
		"Added backend HTTP response writer short-buffer guard microservice example;",
		"Added backend PostgreSQL signed big-endian writer guard microservice example;",
		"Added backend PostgreSQL signed frame-length guard microservice example;",
		"Added backend PostgreSQL high-bit big-endian reader guard microservice example;",
		"Added backend PostgreSQL ASCII i32 minimum guard microservice example;",
		"Added backend time negative-base duration guard microservice example;",
		"Added backend HTTP request-line CRLF guard microservice example;",
		"Added backend filesystem embedded-NUL exists guard microservice example;",
		"Added backend HTTP request-target character guard microservice example;",
		"Added backend PostgreSQL ASCII i32 overflow guard microservice example;",
		"Added backend PostgreSQL CommandComplete affected-row overflow guard microservice example;",
		"Added backend PostgreSQL CommandComplete trailing-count guard microservice example;",
		"Added backend PostgreSQL DataRow truncated-value guard microservice example;",
		"Added backend PostgreSQL frame total-length overflow guard microservice example;",
		"Added backend HTTP negative Content-Length guard microservice example;",
		"Added backend HTTP status-code guard microservice example;",
		"Added backend HTTP header injection guard microservice example;",
		"Added backend HTTP header control-byte guard microservice example;",
		"Added backend PostgreSQL Parse parameter-count guard microservice example;",
		"Added backend net TCP port bounds guard microservice example;",
		"Added backend PostgreSQL signed column-count guard microservice example;",
		"Added backend PostgreSQL embedded-NUL C-string guard microservice example;",
	} {
		if !strings.Contains(text, want) {
			t.Fatalf("Tetra_BUGS.md missing %q", want)
		}
	}
}
