package scriptstest

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestReleaseV013GateIsCanonicalPatchGate(t *testing.T) {
	root := repoRoot(t)
	assertLegacyFileRemoved(t, "scripts/release_v0_1_3_gate.sh", "scripts/release/v0_1_3/gate.sh directly")
	raw, err := os.ReadFile(filepath.Join(root, "scripts", "release", "v0_1_3", "gate.sh"))
	if err != nil {
		t.Fatalf("read v0.1.3 release gate: %v", err)
	}
	text := string(raw)
	for _, want := range []string{
		"Usage: bash scripts/release/v0_1_3/gate.sh [--report-dir DIR]",
		`release_version="${TETRA_RELEASE_GATE_VERSION:-v0.1.3}"`,
		`release_artifact="${TETRA_RELEASE_GATE_ARTIFACT:-tetra.release.v0_1_3.gate-report.v1}"`,
		`release_gate_command="${TETRA_RELEASE_GATE_COMMAND:-bash scripts/release/v0_1_3/gate.sh}"`,
		`echo "== $release_version preflight =="`,
		`# Tetra $release_version Release Gate Report`,
		`run_step "version preflight ($release_version required)" check_release_version`,
		`expected $release_version version`,
		`--expected-version "$release_version"`,
		"Generated by",
		"scripts/release/v0_1_3/gate.sh",
	} {
		if !strings.Contains(text, want) {
			t.Fatalf("v0.1.3 release gate missing %q", want)
		}
	}
}

func TestReleaseV013GateValidatesPerformanceEvidenceArtifact(t *testing.T) {
	raw, err := os.ReadFile(filepath.Join(repoRoot(t), "scripts", "release", "v0_1_3", "gate.sh"))
	if err != nil {
		t.Fatalf("read v0.1.3 release gate: %v", err)
	}
	text := string(raw)
	for _, want := range []string{
		`check_performance_regression_artifact()`,
		`go run ./tools/cmd/validate-performance-report --report "$dst"`,
		`run_step "performance regression evidence" check_performance_regression_artifact`,
	} {
		if !strings.Contains(text, want) {
			t.Fatalf("v0.1.3 release gate missing %q", want)
		}
	}
}

func TestReleaseV013GateRejectsNonDirectoryReportPathBeforeSideEffects(t *testing.T) {
	root := releaseOldGateMinimalRoot(t, "scripts/release/v0_1_3/gate.sh")
	reportDir := filepath.Join(root, "report-file")
	if err := os.WriteFile(reportDir, []byte("not a directory\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	assertOldGateRejectsNonDirectoryReportPath(t, root, "scripts/release/v0_1_3/gate.sh", "release_v0_1_3_gate:", reportDir)
}

func TestReleaseV013GateRejectsDanglingReportDirSymlinkBeforeSideEffects(t *testing.T) {
	root := releaseOldGateMinimalRoot(t, "scripts/release/v0_1_3/gate.sh")
	reportDir := filepath.Join(root, "dangling-report-link")
	if err := os.Symlink(filepath.Join(root, "missing-report-target"), reportDir); err != nil {
		t.Fatal(err)
	}

	assertOldGateRejectsNonDirectoryReportPath(t, root, "scripts/release/v0_1_3/gate.sh", "release_v0_1_3_gate:", reportDir)
}

func TestReleaseV013GateRejectsNonEmptyReportDirBeforeSideEffects(t *testing.T) {
	root := releaseOldGateMinimalRoot(t, "scripts/release/v0_1_3/gate.sh")
	reportDir := filepath.Join(root, "report")
	if err := os.MkdirAll(reportDir, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(reportDir, "summary.json"), []byte("{}\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	assertOldGateRejectsNonEmptyReportDir(t, root, "scripts/release/v0_1_3/gate.sh", "release_v0_1_3_gate:", reportDir)
}

func TestReleaseV013GateRejectsDashPrefixedNonEmptyReportDirBeforeSideEffects(t *testing.T) {
	root := releaseOldGateMinimalRoot(t, "scripts/release/v0_1_3/gate.sh")
	reportDirArg := "-stale-report"
	reportDir := filepath.Join(root, reportDirArg)
	if err := os.MkdirAll(reportDir, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(reportDir, "summary.json"), []byte("{}\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	assertOldGateRejectsNonEmptyReportDirWithArg(t, root, "scripts/release/v0_1_3/gate.sh", "release_v0_1_3_gate:", reportDirArg, reportDir)
}
